### ISSUE TITLE
MongoDB underprivileged container fails during postInstall hook.

### ISSUE THREAD

**Issue by dennybaa** [bitnami/bitnami-docker-mongodb#102]
**Description**

When the unprivileged container runs postInstall hook it tries to find user `mongo` which is not there.

**Steps to reproduce the issue:**

1. configuration

on aws

```yaml
mongodbRootPassword: admin
mongodbUsername: test
mongodbPassword: test
mongodbDatabase: test
image:
  repository: bitnami/mongodb
  tag: 3.6
  pullPolicy: IfNotPresent
existingSecret: false
replicaSet:
  key: mystrongkey
  enabled: true
  replicas:
    arbiter: 1
    secondary: 1
persistence:
  enabled: true
```

2. `helm install stable/mongodb --name test -f values.yaml`
3. `kubectl logs -f ticker-mongodb-arbiter-0`

```
Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues

nami    INFO  Initializing mongodb
mongodb INFO  ==> Deploying MongoDB from scratch...
mongodb INFO  ==> No injected configuration files found. Creating default config files...
mongodb INFO  ==> Writing keyfile for replica set authentication
Error executing 'postInstallation': User 'mongo' not found
```

**Version**

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional details**

Privileged container `bitnami/mongodb:3.6-debian-8` which drops to mongo with `gosu` works fine. **Generally it's not not very clear** how to run bitnami unprivileged containers, there's no any details in mongodb chart documentation.
