### ISSUE TITLE
Replica set configuration improvements proposal

### ISSUE THREAD

**Issue by abinet** [bitnami/bitnami-docker-mongodb#111]
Hello all,

first of all I would like to thank you for a fantastic job you are doing here.
Your mongo image is pretty flexible and allow a lot of automation in terms of the user and replica configuration.I like a lot the idea of the user and database pre-configuration.

For the replica set config on K8s I prefer to use additionally sidecar https://github.com/cvallance/mongo-k8s-sidecar because it allows to define mongo replicaset with K8s statefulset without providing specific roles to the separate pods. The replica set configuration in this case is much more dynamic and requires a single stateful set for a whole replica. It is not about replacing current solution rather providing an additional usage scenario.  
And bitnami mongo image almost covers this approach. Only one small modification is needed: start mongo with `replicaSetMode = primary` but skip `rs.initiate` steps. In this case sidecar can takeover the replica set configuration and assign the roles dynamically. One just need to introduce some let's say `dynamic` replicset mode value to trigger this behavior.

Another replica set aspect is coupled with snapshot backup/recovery.  Let's imagine you want to create a mongo replica set "green" based on file system snapshots from existing replica set "blue". The replica set config in this case will be restored as well and we'll get another replicas trying to connect to rs "blue". Official mongo documentation suggests to delete "local" database in this case and re-configure the replica set with "green". 

If somebody is interested in this functionality I can provide changes for helper.js and main.js files to cover this.

**Comment by beltran-rubo** [comment]
Yes thanks! It is a good feature to add to the MongoDB chart. It would be great if you can send us the required changes in the helper.js/main.js files so we can fully test & release this improvement.

**Comment by abinet** [comment]
1. So, here are the changes in `helper.js` needed to run mongo image with sidecar:

```
$app.helpers.configureReplicaSet = function(replicaSetProperties, connectionProperties) {
  $app.info('==> Configuring MongoDB replica set');
  this.configure({replication: '', replSetName: replicaSetProperties.name});
  $app.restart();
  const node = networkFunctions.getMachineIp();
  switch (replicaSetProperties.mode) {
    case 'primary': {
      this.configurePrimary(node, _.assign({}, connectionProperties, {host: '127.0.0.1', port: $app.mongodbPort}));
      break;
    }
    case 'secondary': {
      this.configureSecondary(node, connectionProperties);
      break;
    }
    case 'arbiter': {
      this.configureArbiter(node, connectionProperties);
      break;
    }
    case 'dynamic': {
      //do nothing
      break;
    }
    default: {
      throw new Error('Invalid replica set mode. Available options are \'primary/secondary/arbiter/dynamic\'');
    }
  }
};
```

In this case we start each replica in replicaSet mode and let the sidecar (I'm using https://github.com/cvallance/mongo-k8s-sidecar) re-configure the replicas dynamically.


2. Here are the changes in main.js to support replica set reset in case if replica set names are not equal:


```
$app.postInstallation = function() {
  const keyFile = $file.join($app.confDir, 'keyfile');

  $os.addGroup($app.systemGroup);
  $os.addUser($app.systemUser, {gid: $app.systemGroup});
  _.each([$app.tmpDir, $app.logsDir], function(folder) {
    $file.mkdir(folder, {owner: $app.systemUser, group: $app.systemGroup});
  });
  if (!volumeFunctions.isInitialized($app.persistDir)) {
    $app.helpers.validateInputs();
    // MongoDB recommends to place the database in a XFS filesystem.
    // Moving the data to the persistent volumes first,
    // which can be formatted to XFS, solves this.
    volumeFunctions.prepareDataToPersist($app.dataToPersist);
    $file.mkdir($file.join($app.dataDir, 'db'), {owner: $app.systemUser});
    $hb.renderToFile('mongodb.conf.tpl', $app.confFile);

    // Configure arbiter to use mmapv1 before starting
    if ($app.replicaSetMode === 'arbiter') {
      $app.helpers.configure({
        engine: 'mmapv1',
        mmapv1: '',
        smallFiles: 'true',
      });
    }

    $app.start();
    $app.helpers.createUser();
    if (!_.isEmpty($app.replicaSetMode)) {
      const connectionProperties = {
        host: $app.primaryHost,
        port: $app.primaryPort,
        database: 'admin',
        user: 'root',
        password: $app.primaryRootPassword || $app.rootPassword || '',
      };
      const replicaSetProperties = {
        name: $app.replicaSetName,
        mode: $app.replicaSetMode,
      };
      // https://docs.mongodb.com/manual/tutorial/deploy-replica-set-with-keyfile-access-control/
      if (!_.isEmpty($app.replicaSetKey)) $app.helpers.configureKeyFile(keyFile, $app.replicaSetKey);
      $app.helpers.configureReplicaSet(replicaSetProperties, connectionProperties);
    }
    $app.stop();
  } else {
    volumeFunctions.restorePersistedData($app.dataToPersist);
    //we reset rs config in case of the different replica set names 
    if (!_.isEmpty($app.replicaSetMode) && !$file.contains($app.confFile, /^[\s]*replSetName: $app.replicaSetName/)) {
      $hb.renderToFile('mongodb.conf.tpl', $app.confFile);
      $app.restart()
      $app.helpers.dropLocalDatabase();
      const connectionProperties = {
        host: $app.primaryHost,
        port: $app.primaryPort,
        database: 'admin',
        user: 'root',
        password: $app.primaryRootPassword || $app.rootPassword || '',
      };
      const replicaSetProperties = {
        name: $app.replicaSetName,
        mode: $app.replicaSetMode,
      };
      // https://docs.mongodb.com/manual/tutorial/deploy-replica-set-with-keyfile-access-control/
      if (!_.isEmpty($app.replicaSetKey)) $app.helpers.configureKeyFile(keyFile, $app.replicaSetKey);
      $app.helpers.configureReplicaSet(replicaSetProperties, connectionProperties);
      $app.helpers.enableAuth();
      $app.stop();
    }
  }
``` 

here is the implementation of `dropLocalDatabase` in `helper.js`:

```
$app.helpers.dropLocalDatabase = function() {
  $app.info('==> Drop local database to reset replica set setup');
    mongodbFunctions.execute(`db.getSiblingDB('local').dropDatabase()`)
};
```

**Comment by beltran-rubo** [comment]
That is great! Thanks @abinet We will review & test the changes. We will keep you in the loop.

**Comment by rafariossaa** [comment]
Hi @abinet, 
  I was assigned this task, I am reviewing and testing it.
  I hope to have news soon.

Best regards
Rafael Rios

**Comment by rafariossaa** [comment]
@abinet , sorry the long delay

 I am reviewing this and adapting it. It seems that you are using an old version with a different helper.js and main.js than the current one. 
 Could you give me an example of how to use the sidecar you indicated with the solution you provided ?

 Thanks forehand,
Rafael Rios

**Comment by abinet** [comment]
@rafariossaa 

Here you can find an example of the StatefulSet which uses bitnami  image extended with changes and sidecar

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
spec:
  replicas: 3
  selector:
    matchLabels:
      role: mongo
  serviceName: mongo
  template:
    metadata:
      labels:
        role: mongo
    spec:
      containers:
      - env:
        - name: MONGODB_REPLICA_SET_NAME
          value: mongo-rs0
        - name: MONGODB_REPLICA_SET_MODE
          value: dynamic
        - name: MONGODB_REPLICA_SET_KEY
          value: secret
        - name: MONGODB_ROOT_PASSWORD
          value: root
        - name: MONGODB_USERNAME
          value: mongo
        - name: MONGODB_DATABASE
          value: mongo
        - name: MONGODB_PASSWORD
          value: mongo
        image: <patched bitnami/mongo-3.6.3-r3 image>
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - db.adminCommand('ping')
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: mongo
        ports:
        - containerPort: 27017
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - db.adminCommand('ping')
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /bitnami/mongodb
          name: mongo-pvc
      - env:
        - name: MONGO_SIDECAR_POD_LABELS
          value: role=mongo
        - name: KUBERNETES_MONGO_SERVICE_NAME
          value: mongo
        - name: MONGODB_USERNAME
          value: root
        - name: MONGODB_DATABASE
          value: admin
        - name: MONGODB_PASSWORD
          value: root
        image: cvallance/mongo-k8s-sidecar:latest
        imagePullPolicy: IfNotPresent
        name: mongo-sidecar
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: mongo-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
```

All three instances are starting as  "dynamic" so the configuration via bitnami will be skipped. Sidecar dynamically makes first instance to primary and the rest to secondary.
