### ISSUE TITLE
Error in heartbeat (requestId: 385) to 172.19.0.4:27017, response status: HostUnreachable: Error connecting to 172.19.0.4:27017 :: caused by :: Connection refused

### ISSUE THREAD

**Issue by Sandeeprao69** [bitnami/bitnami-docker-mongodb#119]
I am a begginer and i am trying get replicaset up and running .

I am getting error when i do `docker-compose up --scale mongodb-primary=1 --scale mongodb-secondary=3 --scale mongodb-arbiter=1`

My Docker-compose.yml
version: '3.4'

```
services:
  server:
    image: us.gcr.io/test/web-service
    build: .
    environment:
      NODE_ENV: development
      IS_DEV_MACHINE: "yes"
    ports:
      - 1338:1337 # HOST_PORT is 1338 to avoid conflicts with other Sails.js apps running on host
    volumes:
      - ../:/usr/src/app
    entrypoint: nodemon

  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
    volumes:
      - 'mongodb_master_data:/bitnami'

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017

  mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017

volumes:
  mongodb_master_data:
    driver: local
```
