### ISSUE TITLE
 MONGODB_PORT_NUMBER ignored in replicaset

### ISSUE THREAD

**Issue by creativearmenia** [bitnami/bitnami-docker-mongodb#126]
**Description**
I am trying to run replicaset of 3 instances and each instance has its own unique port number set by 
MONGODB_PORT_NUMBER

here is compose file
```
version: '3.7'
services:
  mongodb1:
    image: bitnami/mongodb:4.1.4
    stop_grace_period: 1s
    volumes:
      - mongo-data:/data/db
    networks:
      - database-network
    ports:
      - "28888:28888"
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_PORT_NUMBER=28888
      - MONGODB_ADVERTISED_HOSTNAME=mongodb1

  mongodb2:
    image: bitnami/mongodb:4.1.4
    stop_grace_period: 1s
    networks:
      - database-network
    ports:
      - "28887:28887"
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_PORT_NUMBER=28887
      - MONGODB_PRIMARY_HOST=mongodb1
      - MONGODB_PRIMARY_PORT_NUMBER=28888
      - MONGODB_ADVERTISED_HOSTNAME=mongodb2

  mongodb3:
    image: bitnami/mongodb:4.1.4
    stop_grace_period: 1s
    networks:
      - database-network
    ports:
      - "28886:28886"
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_PORT_NUMBER=28886
      - MONGODB_PRIMARY_HOST=mongodb1
      - MONGODB_PRIMARY_PORT_NUMBER=28888
      - MONGODB_ADVERTISED_HOSTNAME=mongodb3
      
networks:
  database-network:
    driver : bridge

volumes:
  mongo-data:
```

from primary instance log I saw that the secondary "mongodb2" added to replicaset with missing port number in host which cause the primary trying to connect on default port 27017, same for arbiter instance, am I doing something wrong?

part of log below 

```
mongodb1_1   | 2018-12-29T07:09:43.502+0000 I REPL     [conn8] replSetReconfig admin command received from client; new config: { _id: "rs0", version: 2, protocolVersion: 1, writeConcernMajorityJournalDefault: true, members: [ { _id: 0, host: "mongodb1:28888", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 5.0, tags: {}, slaveDelay: 0, votes: 1 }, _**{ _id: 1.0, host: "mongodb2" }**_ ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: -1, catchUpTakeoverDelayMillis: 30000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('5c271dad8f5e4252d8eaa182') } }

Dropping all pooled connections to mongodb2:27017 due to HostUnreachable: Error connecting to mongodb2:27017
```

**Comment by andresbono** [comment]
Hi @creativearmenia, thanks for submitting this issue. We'll include the fix that you are proposing in future releases of the container.

Just a note, you may want to tweak the exposed ports in the docker-compose instead of mounting a patched file:

```diff
@@ -7,11 +7,10 @@ services:
     networks:
       - database-network
     ports:
-      - "28888:28888"
+      - "28888:27017"
     environment:
       - MONGODB_REPLICA_SET_MODE=primary
       - MONGODB_REPLICA_SET_NAME=rs0
-      - MONGODB_PORT_NUMBER=28888
       - MONGODB_ADVERTISED_HOSTNAME=mongodb1

   mongodb2:
@@ -20,13 +19,11 @@ services:
     networks:
       - database-network
     ports:
-      - "28887:28887"
+      - "28887:27017"
     environment:
       - MONGODB_REPLICA_SET_MODE=secondary
       - MONGODB_REPLICA_SET_NAME=rs0
-      - MONGODB_PORT_NUMBER=28887
       - MONGODB_PRIMARY_HOST=mongodb1
-      - MONGODB_PRIMARY_PORT_NUMBER=28888
       - MONGODB_ADVERTISED_HOSTNAME=mongodb2

   mongodb3:
@@ -35,13 +32,11 @@ services:
     networks:
       - database-network
     ports:
-      - "28886:28886"
+      - "28886:27017"
     environment:
       - MONGODB_REPLICA_SET_MODE=arbiter
       - MONGODB_REPLICA_SET_NAME=rs0
-      - MONGODB_PORT_NUMBER=28886
       - MONGODB_PRIMARY_HOST=mongodb1
-      - MONGODB_PRIMARY_PORT_NUMBER=28888
       - MONGODB_ADVERTISED_HOSTNAME=mongodb3

 networks:
```

**Comment by creativearmenia** [comment]
Hi @andresbono, Thanks for suggestion, but it wont work for my case, I am using java driver with auto-discovery to connect to replica in docker from my host, thats why I want to change default ports to unique for all instances

**Comment by andresbono** [comment]
Hi @creativearmenia, the latest releases of the container include the fix to this issue. We are going to close it.

Let us know if you find any issues with it!

**Comment by diavrank** [comment]
Hello, I have the same problema with `bitnami/mongodb:4.4.7` . 

Any solution?

Thanks in advance.

**Comment by juan131** [comment]
Hi @diavrank 

Could you share the Docker Compose (or equivalent commands) you're using so I can reproduce the issue?

**Comment by diavrank** [comment]
Yes, is this:

```
version: '3'

services:
  mongo-primary:
    container_name: mongo-primary
    image: bitnami/mongodb:4.4.7
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0 
      - MONGODB_ROOT_PASSWORD=rootPassword
      - MONGODB_REPLICA_SET_KEY=replicasetkey
      - MONGODB_USERNAME=developer
      - MONGODB_PASSWORD=otherPassword
      - MONGODB_DATABASE=db
    volumes:
      - $PWD/data:/bitnami
    networks:
      - rematch-net
  mongo-secondary:
    container_name: mongo-secondary
    image: bitnami/mongodb:4.4.7
    restart: always
    ports:
      - 28017:28017
    depends_on:
      - mongo-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_PORT_NUMBER=28017
      - MONGODB_INITIAL_PRIMARY_HOST=mongo-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=rootPassword
      - MONGODB_REPLICA_SET_KEY=replicasetkey
    networks:
      - rematch-net
  mongo-arbiter:
      container_name: mongo-arbiter
      image: bitnami/mongodb:4.4.7
      restart: always
      ports:
        - 29017:29017
      depends_on:
        - mongo-primary
      environment:
        - MONGODB_ADVERTISED_HOSTNAME=mongo-arbiter
        - MONGODB_REPLICA_SET_MODE=arbiter
        - MONGODB_REPLICA_SET_NAME=rs0
        - MONGODB_PORT_NUMBER=29017
        - MONGODB_INITIAL_PRIMARY_HOST=mongo-primary
        - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
        - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=rootPassword
        - MONGODB_REPLICA_SET_KEY=replicasetkey
      networks:
        - rematch-net
networks:
  rematch-net:

```
