### ISSUE TITLE
Cannot create a regular user when my own config file is provided

### ISSUE THREAD

**Issue by hedayat** [bitnami/bitnami-docker-mongodb#132]
**Description**
I try to run the image in k8s using provided helm chart. I do provide my own configuration file with authentication enabled and with enableLocalhostAuthBypass set to true; and provide both root password and a regular user/pass and db.

Now, since the localhost auth exception is turned on, the bitnami image can successfully create the root user. But since there is a user, the localhost exception no longer applies, so it cannot create the regular user. However, the image already knows credentials to log in with root user, so it should authenticate with root user and then create the regular user.

**Steps to reproduce the issue:**

1. Run helm chart with a regular user & root pass configured, and your own config file with auth enabled & local exception enabled

**Describe the results you received:**
```
app-entrypoint.sh 16:07:18.40 
app-entrypoint.sh 16:07:18.40 Welcome to the Bitnami mongodb container
app-entrypoint.sh 16:07:18.41 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
app-entrypoint.sh 16:07:18.41 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
app-entrypoint.sh 16:07:18.41 
nami    INFO  Initializing mongodb
mongodb INFO  ==> Deploying MongoDB from scratch...
mongodb INFO  ==> Configuration files found...
mongodb TRACE [runProgram] Executing: null /opt/bitnami/mongodb/bin/mongod --config /opt/bitnami/mongodb/conf/mongodb.conf
mongodb TRACE code: 0
mongodb TRACE stdout:

mongodb TRACE stderr:

mongodb INFO  ==> Creating root user...
mongodb TRACE [runProgram] Executing: /opt/bitnami/mongodb/bin/mongo --quiet,admin,--port,27017,--eval,db.getSiblingDB('admin').createUser({"user":"root","pwd":"EWMXjHfuX.wD7HegFytB","roles":["root"]})
mongodb TRACE {
  "code": 0,
  "stdout": "Successfully added user: { \"user\" : \"root\", \"roles\" : [ \"root\" ] }\n",
  "stderr": ""
}
mongodb INFO  ==> Creating mango user...
mongodb TRACE [runProgram] Executing: /opt/bitnami/mongodb/bin/mongo --quiet,admin,--port,27017,--eval,db.getSiblingDB('mango').createUser({"user":"mango","pwd":"hHbaP4Y,zRygzCs.VBf,","roles":[{"role":"readWrite","db":"mango"}]})
mongodb TRACE {
  "code": 252,
  "stdout": "2019-02-24T16:07:35.222+0000 E QUERY    [js] Error: couldn't add user: command createUser requires authentication :\n_getErrorWithCode@src/mongo/shell/utils.js:25:13\nDB.prototype.createUser@src/mongo/shell/db.js:1491:15\n@(shell eval):1:1\n",
  "stderr": ""
}
mongodb WARN  ==> You are mounting a configuration file and setting the mongodb password or root password.
mongodb WARN  ==> Remember to enable authentication in your config file for those password to be valid.
mongodb TRACE [prepareDataToPersist] Preparing /opt/bitnami/mongodb/data to persist in /bitnami/mongodb/data
mongodb TRACE [configurePermissions] File to chmod: /bitnami/mongodb/data
mongodb INFO 
mongodb INFO  ########################################################################
mongodb INFO   Installation parameters for mongodb:
mongodb INFO     Root Password: **********
mongodb INFO     Username: mango
mongodb INFO     Password: **********
mongodb INFO     Database: mango
mongodb INFO   (Passwords are not shown for security reasons)
mongodb INFO  ########################################################################
mongodb INFO 
nami    INFO  mongodb successfully initialized
app-entrypoint.sh 16:07:40.56 INFO  ==> Starting mongodb... 
sed: couldn't open temporary file /opt/bitnami/mongodb/conf/sedJTYn8D: Permission denied
run.sh 16:07:40.65 INFO  ==> Starting mongod...
2019-02-24T16:07:40.766+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2019-02-24T16:07:40.843+0000 I CONTROL  [initandlisten] MongoDB starting : pid=111 port=27017 dbpath=/opt/bitnami/mongodb/data/db 64-bit host=default-mangolm-db-594fb7d855-rtm84
2019-02-24T16:07:40.843+0000 I CONTROL  [initandlisten] db version v4.0.6
```

**Describe the results you expected:**
Creating the second user should succeed

**Comment by hedayat** [comment]
I just discovered that even if I don't create the root user, it still doesn't allow to create a regular user. So it just doesn't work with provided config file unless I disable auth for the first run & enable again afterwards, which is not appropriate for automatic deployments.

**Comment by javsalgar** [comment]
Hi,

It would be great if you could provide us with the exact custom config file you are using

**Comment by hedayat** [comment]
```
      # Where and how to store data.
      storage:
        dbPath: /opt/bitnami/mongodb/data/db
        directoryPerDB: true
        journal:
          enabled: true
        engine: "wiredTiger"
        wiredTiger:
          collectionConfig:
            blockCompressor: zlib
          engineConfig:
            directoryForIndexes: true
      # where to write logging data.
      systemLog:
        destination: file
        logAppend: true
        path:
        quiet: false
        logRotate: reopen
      # network interfaces
      net:
        port: 27017
        bindIpAll: true
        ipv6: false
        unixDomainSocket:
          enabled: true
          pathPrefix: /opt/bitnami/mongodb/tmp
      # process management options
      processManagement:
         fork: false
         pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
         timeZoneInfo: /usr/share/zoneinfo
      # set parameter options
      setParameter:
         enableLocalhostAuthBypass: true
      # security options
      security:
        authorization: enabled
        #keyFile: /opt/bitnami/mongodb/conf/keyfile
```

**Comment by juan131** [comment]
I think I can see where's the issue @hedayat 

Here you have the function used to create both the root user and the one you requested:

```
$app.helpers.createUser = function() {
  if (!_.isEmpty($app.rootPassword) && !$app.replicaSetMode.match(/secondary|arbiter/)) {
    $app.info('==> Creating root user...');
    mongodbFunctions.createUser('root', $app.rootPassword, 'admin', 'root', {port: $app.mongodbPort});
  }
  if (!_.isEmpty($app.username)) {
    if (!_.isEmpty($app.password) && !_.isEmpty($app.database)) {
      $app.info(`==> Creating ${$app.username} user...`);
      mongodbFunctions.createUser(
        $app.username,
        $app.password,
        $app.database,
        {role: 'readWrite', db: $app.database},
        {port: $app.mongodbPort}
      );
    } else {
      throw new Error('If you defined an username you must define a password and a database too');
    }
  } else if (!_.isEmpty($app.password) || !_.isEmpty($app.database)) {
    throw new Error('If you defined a password or a database you should define an username too');
  }
  $app.helpers.enableAuth();
};
```

As you can see it assumes that it can create the user without authentication since the call to the function `$app.helpers.enableAuth();` is done after both users are created. The logic should be sth like: 

 - Create root user
 - Enable Auth
 - Create custom user *using authentication*

I'm going to open a task to fix it asap @hedayat !! Thanks for reporting it

**Comment by hedayat** [comment]
> The logic should be sth like:
> 
>     * Create root user
> 
>     * Enable Auth
> 
>     * Create custom user _using authentication_
Yeah. And IMHO it should be noted somewhere in the docs that provided config file must enable `enableLocalhostAuthBypass` for it to work if authentication is enabled in the config.
 
> 
> I'm going to open a task to fix it asap @hedayat !! Thanks for reporting it

:"> You're welcome.

**Comment by juan131** [comment]
Hi @hedayat 

I just released a new version of MongoDB that should address the issue. Could you please try using the image `bitnami/mongodb:4.1.8-r13`:

```
helm install stable/mongodb -f values.yaml --set image.tag=4.1.8-r13
```

**Comment by hedayat** [comment]
Yeah, thanks. Works fine :)

**Comment by juan131** [comment]
Great @hedayat !! I'm closing this issue. Please let us know if you face issues again with authentication.

**Comment by guanzo** [comment]
Hey sorry to necro this issue but I'm running into some weird authentication issues that're related to me providing a configmap.

It all started when I tried various ways to disable the journal.

In my helm values I set
```yml
# mongodb-values.yaml 
extraFlags:
- "--nojournal"
```

Then `helm upgrade --install -f mongodb-values.yaml  mongodb bitnami/mongodb --version 10.12.1`

When mongo started it would complain "cannot set both --journal and --nojournal" then crash. 

Then I tried
```yml
# mongodb-values.yaml 
configuration: |-
    storage:
      journal:
        enabled: false
```

Mongo didn't like that either, it kept crashing. I assume it's because my config overwrote some necessary config. I was hoping it'd perform some sort of config "patch" but I guess not. 

Then I decided to exec into the container and copy the contents of `/opt/bitnami/mongodb/mongodb.conf`, disable the journal, and put that as my `configuration` value.

```yml
# mongodb-values.yaml 
auth:
  database: test
  username: test
  existingSecret: mongodb-creds

# Disable journal as mongo is used as a cache and can tolerate data loss.
# The WiredTiger engine saves snapshots to disk every 60 seconds anyways.
configuration: |-
    # mongod.conf
    # for documentation of all options, see:
    #   http://docs.mongodb.org/manual/reference/configuration-options/

    storage:
      dbPath: /bitnami/mongodb/data/db
      journal:
        enabled: false # <--------- I change this from true to false
      directoryPerDB: false

    # where to write logging data.
    systemLog:
      destination: file
      quiet: false
      logAppend: true
      logRotate: reopen
      path: /opt/bitnami/mongodb/logs/mongodb.log
      verbosity: 0

    # network interfaces
    net:
      port: 27017
      unixDomainSocket:
        enabled: true
        pathPrefix: /opt/bitnami/mongodb/tmp
      ipv6: false
      bindIpAll: true

    # process management options
    processManagement:
       fork: false
       pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid

    setParameter:
       enableLocalhostAuthBypass: false

    security:
      authorization: enabled
```

Now mongo would start up, but I couldn't authenticate as "root", or as my "test" user. I'm 100% sure the credentials were correct and that I deleted the pvc/pv every time I'd redeploy. After I saw this issue, I set `enableLocalhostAuthBypass: true` and then I had no problems with authentication. 

Is this intended behavior? Is there an easier way to disable the journal? Thanks.
