### ISSUE TITLE
[helm chart]error opening file: /opt/bitnami/mongodb/conf/keyfile: Permission denied

### ISSUE THREAD

**Issue by SgtDaJim** [bitnami/bitnami-docker-mongodb#135]
Last year I deployed a mongodb using this helm chart on k8s,
then the day before yesterday the mongodb crashed.
And it cannot recovery.
Here is the log:
Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
 nami    INFO  Initializing mongodb
mongodb INFO  ==&gt; Deploying MongoDB with persisted data...
mongodb INFO  ==&gt; No injected configuration files found. Creating default config files...
mongodb INFO  ==&gt; Writing keyfile for replica set authentication
mongodb INFO  ==&gt; Enabling MongoDB replica set name
mongodb INFO  ==&gt; Enabling authentication...
mongodb INFO 
mongodb INFO  ########################################################################
mongodb INFO   Installation parameters for mongodb:
mongodb INFO     Persisted data and properties have been restored.
mongodb INFO     Any input specified will not take effect.
mongodb INFO   This installation requires no credentials.
mongodb INFO  ########################################################################
mongodb INFO 
nami    INFO  mongodb successfully initialized
INFO  ==&gt; Starting mongodb... 
INFO  ==&gt; Starting mongod...
2019-03-08T07:03:16.036+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2019-03-08T07:03:16.044+0000 I ACCESS   [main] error opening file: /opt/bitnami/mongodb/conf/keyfile: Permission denied

i am using replicaSet mode.
So how can i solve the problem?

**Version**

helm chart 5.0.0
helm 2.10.0
k8s
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by javsalgar** [comment]
Hi,

Could you let us know if you changed the image or upgraded the chart? Which is the image version and the chart version you are using?

**Comment by SgtDaJim** [comment]
@javsalgar 
helm chart version 5.0.0
image tag 4.0.3

**Comment by javsalgar** [comment]
Hi,

I have tried to reproduce the issue but was unable. However, we can try the following. Maybe that file is inside a persistent volume, and therefore we could try changing its permissions.

- First find the PVC name of the failing mongodb pod
- Create this file

```
kind: Pod
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
       claimName: PUT_HERE_YOUR_PVC_NAME
  containers:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
      volumeMounts:
        - mountPath: "/mnt/vol"
          name: task-pv-storage
```

- Then enter the container with 

```
kubectl exec -ti task-pv-pod sh
```
- Check if the keyfile is there, and try changing its permissions with chmod for example
