### ISSUE TITLE
MongoDB root user is not initialized correctly

### ISSUE THREAD

**Issue by philippfreyer** [bitnami/bitnami-docker-mongodb#137]
**Description**
Short summary: I tried deploying the Bitnami MongoDB Docker image in our kubernetes cluster using an adapted configuration mostly based on the production version of the bitnami mongodb helm chart and it fails creating a replica set. I am quite sure that I used the correct environment variables but am happy to be proven wrong. Looking at the startup with NAMI_DEBUG=1, I notice that the root user is not created successfully. 

Backstory:
I tried to switch from the official MongoDB docker images to the Bitnami ones since Bitnami provides replica set creation via environment variables and I was having trouble with that when switching to MongoDB 4.0 on our Kubernetes cluster. The goal is to create multiple replica sets and then create a sharded cluster.

**Steps to reproduce the issue:**

1. Deploy the master, replica and arbiter nodes using the YAML files quoted below
2. show the logs of the master node
3. observe the error message quoted below

**Describe the results you received:**

When starting up the primary node, I get the following output, containing a MongoDB error in the root user creation stage:
```
[38;5;6mapp-entrypoint.sh [38;5;5m16:08:45.74 [0m
[38;5;6mapp-entrypoint.sh [38;5;5m16:08:45.74 [0m[1mWelcome to the Bitnami mongodb container[0m
[38;5;6mapp-entrypoint.sh [38;5;5m16:08:45.74 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-mongodb[0m
[38;5;6mapp-entrypoint.sh [38;5;5m16:08:45.74 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-mongodb/issues[0m
[38;5;6mapp-entrypoint.sh [38;5;5m16:08:45.75 [0m
nami    INFO  Initializing mongodb
mongodb INFO  ==> Deploying MongoDB from scratch...
mongodb INFO  ==> No injected configuration files found. Creating default config files...
mongodb TRACE [runProgram] Executing: null /opt/bitnami/mongodb/bin/mongod --config /opt/bitnami/mongodb/conf/mongodb.conf
mongodb TRACE code: 0
mongodb TRACE stdout:

mongodb TRACE stderr:

mongodb INFO  ==> Creating root user...
mongodb TRACE [runProgram] Executing: /opt/bitnami/mongodb/bin/mongo --quiet,admin,--port,27017,--eval,db.getSiblingDB('admin').createUser({"user":"root","pwd":"YnWEct05OtbS8cLb9oTygYrIRsABqunE\n","roles":["root"]})
mongodb TRACE {
  "code": 252,
  "stdout": "2019-04-03T16:08:55.865+0000 E QUERY    [js] Error: couldn't add user: Error preflighting normalization: U_STRINGPREP_PROHIBITED_ERROR :\n_getErrorWithCode@src/mongo/shell/utils.js:25:13\nDB.prototype.createUser@src/mongo/shell/db.js:1491:15\n@(shell eval):1:1\n",
  "stderr": ""
}
mongodb INFO  ==> Enabling authentication...
mongodb INFO  ==> Creating okmapgo
 user...
mongodb TRACE [runProgram] Executing: /opt/bitnami/mongodb/bin/mongo --quiet,admin,--port,27017,-u,root,-p,YnWEct05OtbS8cLb9oTygYrIRsABqunE
,--eval,db.getSiblingDB('omg
').createUser({"user":"okmapgo\n","pwd":"srHkpUChKwB6Qm3yLc02cm6YOAMsEKOQ\n","roles":[{"role":"readWrite","db":"omg\n"}]})
mongodb TRACE {
  "code": 1,
  "stdout": "2019-04-03T16:08:56.043+0000 E QUERY    [js] Error: Authentication failed. :\nconnect@src/mongo/shell/mongo.js:343:13\n@(connect):3:6\n",
  "stderr": "exception: connect failed\n"
}
mongodb INFO  ==> Writing keyfile for replica set authentication
mongodb TRACE [configurePermissions] File to chmod: /opt/bitnami/mongodb/conf/keyfile
mongodb INFO  ==> Configuring MongoDB replica set
mongodb INFO  ==> Enabling MongoDB replica set name
mongodb TRACE [runProgram] Executing: null /opt/bitnami/mongodb/bin/mongod --config /opt/bitnami/mongodb/conf/mongodb.conf
mongodb TRACE code: 0
mongodb TRACE stdout:

mongodb TRACE stderr:

mongodb INFO  ==> Configuring MongoDB primary node
mongodb DEBUG Waiting for service at 127.0.0.1:27017...
mongodb TRACE [runProgram] Executing: /opt/bitnami/mongodb/bin/mongo --quiet,admin,--host,127.0.0.1,--port,27017,-u,root,-p,YnWEct05OtbS8cLb9oTygYrIRsABqunE
,--eval,rs.initiate({"_id":"mongodb-rs-config-replica","members":[{"_id":0,"host":"mongo-config-primary-0.mongo-rs-config-headless.liquid-dev.svc.cluster.local:27017","priority":5}]})
mongodb TRACE {
  "code": 1,
  "stdout": "2019-04-03T16:09:05.531+0000 E QUERY    [js] Error: Authentication failed. :\nconnect@src/mongo/shell/mongo.js:343:13\n@(connect):3:6\n",
  "stderr": "exception: connect failed\n"
}
```
The deployment info for all nodes can be found below. The root password is inserted into the pod using a kubernetes secret.

**Describe the results you expected:**

I hoped for the cluster to start up with a root user as well as a database user created with the given passwords.

**Additional information you deem important (e.g. issue happens only occasionally):**

Primary node deployment YAML:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongodb
    chart: mongodb
    release: "1.0"
    rsnum: "config"
  name: mongo-config-primary
  namespace: test-deployments
spec:
  selector:
    matchLabels:
      app: mongodb
      release: "1.0"
      component: primary
      rsnum: "config"
  serviceName: mongo-rs-config-headless
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongodb
        chart: mongodb
        release: "1.0"
        component: primary
        rsnum: "config"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9216"
    spec:
      securityContext:
        fsGroup: 1001
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: rsnum
                      operator: In
                      values:
                        - "config"
                topologyKey: kubernetes.io/hostname
      containers:
        - name: mongodb-primary
          image: bitnami/mongodb:4.0
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          ports:
          - containerPort: 27017
            name: mongodb
          env:
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
          - name: MONGODB_DISABLE_SYSTEM_LOG
            value: "no"
          - name: MONGODB_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MONGODB_REPLICA_SET_MODE
            value: "primary"
          - name: MONGODB_REPLICA_SET_NAME
            value: "mongodb-rs-config-replica"
          - name: MONGODB_ADVERTISED_HOSTNAME
            value: "$(MONGODB_POD_NAME).mongo-rs-config-headless.test-deployments.svc.cluster.local"
          - name: NAMI_DEBUG
            value: "1"
          - name: MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: mongodb-user
          - name: MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: mongodb-db
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: mongodb-password
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: mongodb-root-password
          - name: MONGODB_REPLICA_SET_KEY
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: mongodb-replica-set-key
          - name: MONGODB_ENABLE_IPV6
            value: "no"
          - name: MONGODB_ENABLE_DIRECTORY_PER_DB
            value: "no"
          - name: MONGODB_EXTRA_FLAGS
            value: ""
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            - name: mongo-config-master-persistent-storage-claim
              mountPath: /bitnami/mongodb
          resources:
            requests:
              cpu: 4
              memory: 32Gi
  volumeClaimTemplates:
    - metadata:
        name: mongo-config-master-persistent-storage-claim
      spec:
        storageClassName: "normal"
        accessModes:
        - "ReadWriteOnce"
        selector:
          matchLabels:
            node: config.primary
            system: mongodb
            namespace: test-deployments
            type: local
            size: 1Gi
        resources:
          requests:
            storage: 1Gi

```

Secondary node deployment YAML:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongodb
    chart: mongodb
    release: "1.0"
    rsnum: "config"
  name: mongo-config-secondary
  namespace: test-deployments
spec:
  selector:
    matchLabels:
      app: mongodb
      release: "1.0"
      component: secondary
      rsnum: "config"
  podManagementPolicy: "Parallel"
  serviceName: mongo-rs-config-headless
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongodb
        chart: mongodb
        release: "1.0"
        component: secondary
        rsnum: "config"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9216"
    spec:
      securityContext:
        fsGroup: 1001
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: rsnum
                      operator: In
                      values:
                        - "config"
                topologyKey: kubernetes.io/hostname
      containers:
        - name: mongodb-secondary
          image: bitnami/mongodb:4.0
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          ports:
          - containerPort: 27017
            name: mongodb
          env:
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
          - name: MONGODB_DISABLE_SYSTEM_LOG
            value: "no"
          - name: MONGODB_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MONGODB_PRIMARY_HOST
            value: mongodb-rs-config.test-deployments.svc.cluster.local
          - name: MONGODB_REPLICA_SET_MODE
            value: "secondary"
          - name: MONGODB_REPLICA_SET_NAME
            value: "mongodb-rs-config-replica"
          - name: NAMI_DEBUG
            value: "1"
          - name: MONGODB_ADVERTISED_HOSTNAME
            value: "$(MONGODB_POD_NAME).mongo-rs-config-headless.test-deployments.svc.cluster.local"
          - name: MONGODB_PRIMARY_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: mongodb-root-password
          - name: MONGODB_REPLICA_SET_KEY
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: mongodb-replica-set-key
          - name: MONGODB_ENABLE_IPV6
            value: "no"
          - name: MONGODB_ENABLE_DIRECTORY_PER_DB
            value: "no"
          - name: MONGODB_EXTRA_FLAGS
            value: ""
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            - name: mongo-config-replica-persistent-storage-claim
              mountPath: /bitnami/mongodb
          resources:
            requests:
              cpu: 4
              memory: 32Gi
  volumeClaimTemplates:
    - metadata:
        name: mongo-config-replica-persistent-storage-claim
      spec:
        storageClassName: "normal"
        accessModes:
        - "ReadWriteOnce"
        selector:
          matchLabels:
            node: config.primary
            system: mongodb
            namespace: test-deployments
            type: local
            size: 1Gi
        resources:
          requests:
            storage: 1Gi
```

Arbiter node deployment YAML:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongodb
    chart: mongodb
    release: "1.0"
    rsnum: "config"
  name: mongo-config-arbiter
  namespace: test-deployments
spec:
  selector:
    matchLabels:
      app: mongodb
      release: "1.0"
      component: arbiter
      rsnum: "config"
  serviceName: mongo-rs-config-headless
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongodb
        chart: mongodb
        release: "1.0"
        component: arbiter
        rsnum: "config"
    spec:
      securityContext:
        fsGroup: 1001
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: rsnum
                      operator: In
                      values:
                        - "config"
                topologyKey: kubernetes.io/hostname
      containers:
        - name: mongodb-arbiter
          image: bitnami/mongodb:4.0
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          ports:
          - containerPort: 27017
            name: mongodb
          env:
          - name: MONGODB_SYSTEM_LOG_VERBOSITY
            value: "0"
          - name: MONGODB_DISABLE_SYSTEM_LOG
            value: "no"
          - name: MONGODB_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MONGODB_REPLICA_SET_MODE
            value: "arbiter"
          - name: MONGODB_PRIMARY_HOST
            value: mongodb-rs-config.test-deployments.svc.cluster.local
          - name: MONGODB_REPLICA_SET_NAME
            value: "mongodb-rs-config-replica"
          - name: MONGODB_ADVERTISED_HOSTNAME
            value: "$(MONGODB_POD_NAME).mongo-rs-config-headless.test-deployments.svc.cluster.local"
          - name: MONGODB_PRIMARY_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: mongodb-root-password
          - name: MONGODB_REPLICA_SET_KEY
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: mongodb-replica-set-key
          - name: MONGODB_ENABLE_IPV6
            value: "no"
          - name: MONGODB_ENABLE_DIRECTORY_PER_DB
            value: "no"
          - name: MONGODB_EXTRA_FLAGS
            value: ""
          livenessProbe:
            tcpSocket:
              port: mongodb
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: mongodb
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          resources:
            requests:
              cpu: 4
              memory: 32Gi
```

User secret (values are randomly generated and inserted into the secret, the shown values are plain text for readability):
```
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: test-deployments
  labels:
    app: mongodb
    chart: mongodb
    release: "1.0"
type: Opaque
data:
  mongodb-root-password:  YnWEct05OtbS8cLb9oTygYrIRsABqunE
  mongodb-user: testuser
  mongodb-db: testdb
  mongodb-password:  srHkpUChKwB6Qm3yLc02cm6YOAMsEKOQ
  mongodb-replica-set-key:  jvDanryT67FpO8DKVQYuQ3w9wxlEByxE

```

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:22:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Output of `docker info`:

```
Containers: 21
 Running: 11
 Paused: 0
 Stopped: 10
Images: 797
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 125.8GiB
Name: k8s00001
ID: NGJY:57EC:UALT:MN5Z:UOCR:EK3Q:4SZ7:WXXO:OCK4:NOIX:EVAQ:2VJ5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

- Output of `kubelet --version` 

```
Kubernetes v1.12.1
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
We are using a bare-metal Kubernetes cluster with Docker.
