### ISSUE TITLE
docker-compose-replicaset cant be started twice

### ISSUE THREAD

**Issue by oktacon95** [bitnami/bitnami-docker-mongodb#142]
**Description**

When using docker-compose to create a replicaset on my local system, the replicaset runs just fine for the first time, but when I stop the replicaset and restart it, the secondary + arbiter can't connect to the primary anymore.

**Steps to reproduce the issue:**

1. Run "docker-compose up" with the following configuration:
```
version: '2'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:4.0'
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami'

  mongodb-secondary:
    image: 'bitnami/mongodb:4.0'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: 'bitnami/mongodb:4.0'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
```
2. Stop the Database by running "docker-compose down"
3. Restart the database by running "docker-compose up"

**Describe the results you received:**

The second time you start the db, the secondary and arbiter container write the following error over and over again until they are terminated:
```
mongodb-arbiter_1    | mongodb INFO  Cannot connect to MongoDB server. Retrying in 5 seconds...:
mongodb-arbiter_1    | 2019-05-02T09:59:46.095+0000 E QUERY    [js] Error: not master and slaveOk=false :
mongodb-arbiter_1    | _getErrorWithCode@src/mongo/shell/utils.js:25:13
mongodb-arbiter_1    | DB.prototype.getUsers@src/mongo/shell/db.js:1763:1
mongodb-arbiter_1    | @(shell eval):1:1
```
**Describe the results you expected:**
When you start the replicaset with "docker-compose up" and stop it with "docker-compose down", the database should be restartable as often as you wish.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 18.09.2, build 6247962
```
