### ISSUE TITLE
Connecting to the local instance of a replica set fails in MacOS

### ISSUE THREAD

**Issue by Bexanderthebex** [bitnami/bitnami-docker-mongodb#149]
**Description**

I am having problem in connecting applications running on the local host of my Mac.

**Steps to reproduce the issue:**

I have the following docker-compose file: 

``` yaml
version: "3.1"
services:
  mongodb-primary:
    image: "bitnami/mongodb:latest"
    ports:
      - 30001:27017
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=sprylms
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
    volumes:
      - "mongodb_master_data:/bitnami"

  mongodb-secondary:
    image: "bitnami/mongodb:latest"
    depends_on:
      - mongodb-primary
    ports:
      - 30002:27017
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_REPLICA_SET_NAME=sprylms
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary

  mongodb-arbiter:
    image: "bitnami/mongodb:latest"
    depends_on:
      - mongodb-primary
    ports:
      - 30003:27017
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_REPLICA_SET_NAME=sprylms
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter

  redis:
    image: redis:4.0.10
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
  mongodb_master_data:
    driver: local
  mongodb_arbiter_data:
    driver: local
  mongodb_secondary_data:
    driver: local
```

**Describe the results you received:**

Whenever I connect to the replicaset using the node.js app that I am developing and the studio3t app, I get a timeout error.

```
Timed out after 30000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@5b655576. Client view of cluster state is {type=REPLICA_SET, servers=[{address=mongodb-secondary:27017, type=UNKNOWN, state=CONNECTING}, {address=mongodb-primary:27017, type=UNKNOWN, state=CONNECTING}, {address=mongodb-arbiter:27017, type=UNKNOWN, state=CONNECTING}]
```

**Describe the results you expected:**

I should be able to connect to the instance easily like I do in Ubuntu

**Version**

- Output of `docker version`:

```
Docker version 18.09.2, build 6247962
```

- Output of `docker info`:

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: N55Y:7LTW:ZCLX:NMUS:NGNM:RE7B:SMEI:GP53:GFD6:XQ2E:NX2U:PIFE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 64
 Goroutines: 101
 System Time: 2019-06-17T02:53:19.0848905Z
 EventsListeners: 3
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi @Bexanderthebex ,

By the error it is giving you: 
> Timed out after 30000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@5b655576. Client view of cluster state is {type=REPLICA_SET, servers=[{address=mongodb-secondary:27017, type=UNKNOWN, state=CONNECTING}, {address=mongodb-primary:27017, type=UNKNOWN, state=CONNECTING}, {address=mongodb-arbiter:27017, type=UNKNOWN, state=CONNECTING}]

My guess is that client is using the names (mongodb-primary, mongodb-secondary, ...) but it is not able to resolve those names.

Could you try to add them to the client /etc/hosts file ?

Best regards,
Rafael Rios Saavedra

**Comment by Bexanderthebex** [comment]
I am relatively new to docker, would it be okay for you to send me the commands to do that?

btw, the it is automatically resolving to those addresses. I am using this:

`mongodb://mongodb-primary:30001,mongodb-secondary:30002,mongodb-aribiter:30003/SLS?replicaSet=sprylms`

**Comment by rafariossaa** [comment]
You have to edit the /etc/host, for example with vi:

`$ sudo vi /etc/hosts`

and add this to it
```
127.0.0.1  mongodb-secondary
127.0.0.1  mongodb-primary
127.0.0.1  mongodb-arbiter
```

Then you should be able to connect to it. I think that the problem is that when the client connects to one of the nodes, for example: `localhost:30001`, then it retrieves the list of nodes of the cluster so it gets: `mongodb-primary, mongodb-secondary, mongodb-arbiter`. Latter it will use these names to connect, and it is not able to resolve the ip of the nodes hence the error you got.

> NOTE: If you change the name of the nodes in the docker-compose you have to change it accordingly in `/etc/hosts`. And remove these entries when not longer needed.

Best regards,
Rafael Rios Saavedra

**Comment by Bexanderthebex** [comment]
so I do have this:

<img width="574" alt="Screen Shot 2019-06-17 at 4 03 13 PM" src="https://user-images.githubusercontent.com/22711718/59588212-ac27a500-9119-11e9-8a88-49eb584a2cc4.png">

<img width="554" alt="Screen Shot 2019-06-17 at 4 02 58 PM" src="https://user-images.githubusercontent.com/22711718/59588219-b184ef80-9119-11e9-94b1-7e02760ecf48.png">

and when I try to test the connection, the same error occurs.

this is what I have in my docker logs: 

<img width="1020" alt="Screen Shot 2019-06-17 at 4 06 04 PM" src="https://user-images.githubusercontent.com/22711718/59588295-d711f900-9119-11e9-81b9-11d37bd11f6b.png">

will it help pruning the containers as well? then try it again?

**Comment by Bexanderthebex** [comment]
A little update with the situation:

<img width="498" alt="Screen Shot 2019-06-17 at 10 08 13 PM" src="https://user-images.githubusercontent.com/22711718/59610734-89fb4a80-914c-11e9-85b4-9d62f897c644.png">

``` yaml
version: "3.1"
services:
  mongodb-primary:
    image: "bitnami/mongodb:latest"
    ports:
      - 30001:27017
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=sprylms
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
    volumes:
      - "mongodb_master_data:/bitnami"
    container_name: mongodb-primary
    networks:
      - mongodb-replica

  mongodb-secondary:
    image: "bitnami/mongodb:latest"
    depends_on:
      - mongodb-primary
    ports:
      - 30002:27018
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PORT_NUMBER=27018
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_REPLICA_SET_NAME=sprylms
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
    container_name: mongodb-secondary
    networks:
      - mongodb-replica

  mongodb-arbiter:
    image: "bitnami/mongodb:latest"
    depends_on:
      - mongodb-primary
    ports:
      - 30003:27019
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PORT_NUMBER=27019
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_REPLICA_SET_NAME=sprylms
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
    container_name: mongodb-arbiter
    networks:
      - mongodb-replica

  redis:
    image: redis:4.0.10
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
  mongodb_master_data:
    driver: local
  mongodb_arbiter_data:
    driver: local
  mongodb_secondary_data:
    driver: local

networks:
  mongodb-replica:

```

**Comment by rafariossaa** [comment]
Hi, 
  In this last example you set a network, so the client must be in that network and the entries you set in the /etc/host are not longer valid.

I used this docker-compose.yaml:
```
version: '2'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    ports:
      - 30001:27017
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami'
    networks:
      - app-tier        

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    ports:
      - 30002:27017
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    networks:
      - app-tier        

  mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    ports:
      - 30003:27017
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    networks:
      - app-tier        

volumes:
  mongodb_master_data:
      driver: local

networks:
  app-tier:
```
Start that docker compose with: docker-compose up
And then, as I don't have a client application I used the mongo client in other container, so I run:

`docker run -it --rm     --network mongo_app-tier     bitnami/mongodb:latest mongo --host mongodb-primary -u root -p password123
`

> Note: Notice that you have to replace mongo_app-tier by the correct name of the network, you can get your current network with: `docker network ls`

Could you try this and build up from this point ?
