### ISSUE TITLE
replica set primary cannot be reach in MacOS

### ISSUE THREAD

**Issue by Bexanderthebex** [bitnami/bitnami-docker-mongodb#150]
**Description**

I created a replica set using docker compose with this image. The problem is, it is unreachable (replicaset) in macos. 

**Steps to reproduce the issue:**

1. Create a docker compose file:
``` yaml
version: "3.1"
services:
  mongodb-primary:
    image: "bitnami/mongodb:latest"
    ports:
      - 30001:27017
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=sprylms
    volumes:
      - "mongodb_master_data:/bitnami"

  mongodb-secondary:
    image: "bitnami/mongodb:latest"
    depends_on:
      - mongodb-primary
    ports:
      - 30002:27017
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_REPLICA_SET_NAME=sprylms

  mongodb-arbiter:
    image: "bitnami/mongodb:latest"
    depends_on:
      - mongodb-primary
    ports:
      - 30003:27017
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_REPLICA_SET_NAME=sprylms

  redis:
    image: redis:4.0.10
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
  mongodb_master_data:
    driver: local
  mongodb_arbiter_data:
    driver: local
  mongodb_secondary_data:
    driver: local

```

2. sudo docker-compose up
3. connect using mongo shell: `mongo mongodb://mongodb-primary:27017,mongodb-secondary:27017/SLS?replicaSet=sprylms`

**Describe the results you received:**
<img width="1369" alt="Screen Shot 2019-06-18 at 1 07 12 PM" src="https://user-images.githubusercontent.com/22711718/59654714-113ad380-91ca-11e9-9b34-6a267649cd4e.png">

It seems like it is unreachable.

Here is the contents of my /etc/hosts file:

``` 
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost mongodb-primary mongodb-secondary mongodb-arbiter
255.255.255.255	broadcasthost
::1             localhost

```

**Describe the results you expected:**

I should be able to properly connect to the replicaSet as compared to my ubuntu machine.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost mongodb-primary mongodb-secondary mongodb-arbiter
255.255.255.255	broadcasthost
::1             localhost
192.168.16.3	localhost
192.168.16.4	localhost
Melbex-MBP:~ melbexdeleon$ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: 77UD:HQU3:ADFH:TZ2B:PZUA:ZDGM:4FGZ:QIQK:Z6OJ:5BLY:CJQF:5MIJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 64
 Goroutines: 101
 System Time: 2019-06-18T05:10:10.8811119Z
 EventsListeners: 3
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Using Docker for MAc

**Comment by rafariossaa** [comment]
Hi,

> 3.  connect using mongo shell: mongo mongodb://mongodb-primary:27017,mongodb-secondary:27017/SLS?replicaSet=sprylms

Have into account that when you connect from the host, the is port 30001

**Comment by Bexanderthebex** [comment]
So here, I changed the ports as I am using that in the mongodb replica set that I created locally using mongodb for MacOS and do not want that to interfere with what I currently have

What I did was: 
`mongo mongodb://mongodb-primary:20001,mongodb-secondary:20002/SLS?replicaSet=sprylms`

<img width="1441" alt="Screen Shot 2019-06-18 at 10 40 48 PM" src="https://user-images.githubusercontent.com/22711718/59693882-36573280-921a-11e9-8cde-3784fca0f261.png">

but now, now nodes can be discovered...

**Comment by Bexanderthebex** [comment]
I do think it is important to point out that this happens for the image when in a replicaset but on individual nodes, I can reach it

**Comment by Bexanderthebex** [comment]
@rafariossaa can we have any updates on this?

**Comment by Bexanderthebex** [comment]
This is just a wild guess but isn't it because docker for mac cannot route traffic to the docker bridge?

**Comment by rafariossaa** [comment]
@Bexanderthebex , yes that could be the problem. [Link](https://docs.docker.com/docker-for-mac/networking/) for further refence.

Could you try on a linux machine ?

**Comment by Bexanderthebex** [comment]
I did try on a linux machine and it works. But I would like to confirm as
well that it is the right explanation

**Comment by rafariossaa** [comment]
Hi @Bexanderthebex,
    I have good news, there is a way to workaround this. 

   You need to find which interface is used for docker in macos, typically is `en0` and have a private IP like `192.168.x.y` or `10.x.y.z`. eg. 192.168.200.194

   The you have to add it to `/etc/hosts` for mongodb-primary, mongodb-secondary, mongodb-arbiter:
`192.168.200.194  mongodb-primary  mongodb-secondary  mongodb-arbiter`
 
  And you have to use the following docker compose file:
```
version: '2'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    ports:
      - 30001:30001
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_PORT_NUMBER=30001
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami'

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    ports:
      - 30002:30002
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=30001
      - MONGODB_PORT_NUMBER=30002
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    ports:
      - 30003:30003
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=30001
      - MONGODB_PORT_NUMBER=30002
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  mongodb_master_data:
      driver: local
``` 
Is very important that you use the same port inside and outside (30001:30001), the reason for this is that the internal hostnames and ports are returned to the client when it make the first connection. Later those will be used by the client to connect to all the elements of the replicaset.

Right now this won't work because we have detected a bug in the image, but we are working in fixing it.
I will reach you as soon as the bug is fixed.

Best regards, 
Rafael Rios Saavedra
