### ISSUE TITLE
Containers automatically stops after the first install 

### ISSUE THREAD

**Issue by Bexanderthebex** [bitnami/bitnami-docker-mongodb#152]
**Description**
I am having an issue with the image wherein the image automatically stops after the first initialization.

I have the following docker-compose file:

``` yaml
version: "2"

services:
  mongodb-primary:
    image: "bitnami/mongodb:latest"
    ports:
      - 30001:30001
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=sprylms
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_PORT_NUMBER=30001
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - "mongodb_master_data:/bitnami"

  mongodb-secondary:
    image: "bitnami/mongodb:latest"
    ports:
      - 30002:30002
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_REPLICA_SET_NAME=sprylms
      - MONGODB_PRIMARY_PORT_NUMBER=30001
      - MONGODB_PORT_NUMBER=30002
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: "bitnami/mongodb:latest"
    ports:
      - 30003:30003
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_NAME=sprylms
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=30001
      - MONGODB_PORT_NUMBER=30002
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  redis:
    image: redis:4.0.10
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  mongodb_master_data:
    driver: local
  redis-data:
    driver: local
```

**Steps to reproduce the issue:**

1. run `docker-compose up`
2. After the containers have been successfully initialized stop the containers
3. Run the containers again

**Describe the results you received:**
```
mongodb-primary_1    | INFO  ==> Writing keyfile for replica set authentication: replicasetkey123 /opt/bitnami/mongodb/conf/keyfile
mongodb-primary_1    | INFO  ==> 
mongodb-primary_1    | INFO  ==> ########################################################################
mongodb-primary_1    | INFO  ==>  Installation parameters for MongoDB:
mongodb-primary_1    | INFO  ==>    Persisted data and properties have been restored.
mongodb-primary_1    | INFO  ==>    Any input specified will not take effect.
mongodb-primary_1    | INFO  ==> (Passwords are not shown for security reasons)
mongodb-primary_1    | INFO  ==> ########################################################################
mongodb-primary_1    | INFO  ==> 
mongodb-primary_1    | INFO  ==> Stopping MongoDB...
mongodb-arbiter_1    | INFO  ==> 
mongodb-arbiter_1    | INFO  ==> ########################################################################
mongodb-arbiter_1    | INFO  ==>  Installation parameters for MongoDB:
mongodb-arbiter_1    | INFO  ==>    Persisted data and properties have been restored.
mongodb-arbiter_1    | INFO  ==>    Any input specified will not take effect.
mongodb-arbiter_1    | INFO  ==> (Passwords are not shown for security reasons)
mongodb-arbiter_1    | INFO  ==> ########################################################################
mongodb-arbiter_1    | INFO  ==> 
mongodb-arbiter_1    | INFO  ==> Stopping MongoDB...
mongodb-secondary_1  | INFO  ==> Validating settings in MONGODB_* env vars...
mongodb-secondary_1  | INFO  ==> Initializing MongoDB...
mongodb-secondary_1  | INFO  ==> Deploying MongoDB with persisted data...
mongodb-secondary_1  | INFO  ==> Custom configuration /opt/bitnami/mongodb/conf/mongodb.conf detected!
mongodb-secondary_1  | INFO  ==> Writing keyfile for replica set authentication: replicasetkey123 /opt/bitnami/mongodb/conf/keyfile
mongodb-secondary_1  | INFO  ==> 
mongodb-secondary_1  | INFO  ==> ########################################################################
mongodb-secondary_1  | INFO  ==>  Installation parameters for MongoDB:
mongodb-secondary_1  | INFO  ==>    Persisted data and properties have been restored.
mongodb-secondary_1  | INFO  ==>    Any input specified will not take effect.
mongodb-secondary_1  | INFO  ==> (Passwords are not shown for security reasons)
mongodb-secondary_1  | INFO  ==> ########################################################################
mongodb-secondary_1  | INFO  ==> 
mongodb-secondary_1  | INFO  ==> Stopping MongoDB...
```

**Describe the results you expected:**
The containers should be able to start again without issue

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
Melbex-MBP:~ melbexdeleon$ docker info
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 8
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: AAW4:E6ZP:TLUL:UWT4:FU5E:RIEW:KKPO:W36N:DMU4:JSBK:VZWO:36TM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 35
 Goroutines: 60
 System Time: 2019-06-26T00:05:40.1166427Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Docker for Mac

**Comment by andresbono** [comment]
Hi @Bexanderthebex, could you please tell us the version of the container that you are executing?

You can run the following command in order to obtain it:

```
docker run --rm bitnami/mongodb:latest env | grep BITNAMI_IMAGE_VERSION
```

**Comment by antmarot** [comment]
I have the exact same issue.

`BITNAMI_IMAGE_VERSION=4.0.10-debian-9-r32`

Docker for Mac as well.

**Comment by natha-gomes** [comment]
I have the exact same issue.

`BITNAMI_IMAGE_VERSION=4.0.10-debian-9-r33`

My `docker-compose.yml`

```
version: "3.4"

services:
  mongodb01:
    image: bitnami/mongodb:4.0
    ports:
      - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb01
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=xxx
      - MONGODB_REPLICA_SET_KEY=xxx
    volumes:
      - mongodb01:/bitnami

  mongodb02:
    image: bitnami/mongodb:4.0
    depends_on:
      - mongodb01
    ports:
      - 27018:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb02
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb01
      - MONGODB_PRIMARY_ROOT_PASSWORD=xxx
      - MONGODB_REPLICA_SET_KEY=xxx

  mongodb03:
    image: bitnami/mongodb:4.0
    depends_on:
      - mongodb01
    ports:
      - 27019:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb03
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb01
      - MONGODB_PRIMARY_ROOT_PASSWORD=xxx
      - MONGODB_REPLICA_SET_KEY=xxx```

**Comment by Villefrance** [comment]
Same issue.. Switching back to older version of the bitnami-docker image (4.1.13-r13) made the issue go away (it seems that they did some major refactoring to the way their containers run about a week ago, which may have caused this issue)..

**Comment by carrodher** [comment]
Hi all, thanks for reporting it, we're investigating the issue.

As you rightly said, we implemented some changes in order to decrease the size of the container as Node.js is not necessary anymore, the configuration moved to bash scripts in the _rootfs/_ folder so apart from the size improvement is easier to receive contributions from the community.

It seems something doesn't work as expected in the transition, but we're taking a look and will provide a solution.

**Comment by marcosbc** [comment]
Hi all, we have identified the reason why this issue was occurring, and a revision with the changes was released for all versions.

Don't forget to pull the latest version of the MongoDB container branch and make sure you're using it.

I'm closing this issue as it was solved, but please let us know if you continue to find related errors.

**Comment by maksimenka** [comment]
A have the same issue  in circleCI:

Part of CI config
```
docker:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: database
```
Console output:
```
Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting MongoDB setup **
INFO  ==> Validating settings in MONGODB_* env vars...
INFO  ==> Initializing MongoDB...
INFO  ==> Deploying MongoDB from scratch...
INFO  ==> No injected configuration files found. Creating default config files...
INFO  ==> Creating users...
INFO  ==> Enabling authentication...
INFO  ==> Creating 'user' user...
INFO  ==> Users created
INFO  ==> Stopping MongoDB...
INFO  ==> Stopping MongoDB...

Exited with code 1
```

One month ago, it was OK

**Comment by rafariossaa** [comment]
Hi @maksimenka,
  I removed all the mongodb images I had, and used this docker-compose.yml file:

```
$ cat docker-compose.yml
version: '3'
services:
  mongo:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: database
    ports:
      - 27017:27017
    networks:
      - network
    volumes:
      - mongodb-data:/bitnami
networks:
  network:
volumes:
  mongodb-data:
```

and it started without errors:

```
$ docker-compose up
Pulling mongo (bitnami/mongodb:latest)...
latest: Pulling from bitnami/mongodb
9b45c3f14f97: Pull complete
f03e14c862fc: Pull complete
1612546e6cc2: Pull complete
eea226bca03f: Pull complete
fb2a5c0d5e41: Pull complete
349c7a72d1e7: Pull complete
012d9853ca35: Pull complete
51e6f0d4f9d0: Pull complete
Digest: sha256:8985c23d65b4f9ed5374ed6b8b1a1fda44eccd81244e7faa65cad8488aee117f
Status: Downloaded newer image for bitnami/mongodb:latest
Creating mongodb_mongo_1 ... done
Attaching to mongodb_mongo_1
mongo_1  | 
mongo_1  | Welcome to the Bitnami mongodb container
mongo_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongo_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongo_1  | Send us your feedback at containers@bitnami.com
mongo_1  | 
mongo_1  | INFO  ==> ** Starting MongoDB setup **
mongo_1  | INFO  ==> Validating settings in MONGODB_* env vars...
mongo_1  | INFO  ==> Initializing MongoDB...
mongo_1  | INFO  ==> Deploying MongoDB with persisted data...
mongo_1  | INFO  ==> No injected configuration files found. Creating default config files...
mongo_1  | INFO  ==> 
mongo_1  | INFO  ==> ########################################################################
mongo_1  | INFO  ==>  Installation parameters for MongoDB:
mongo_1  | INFO  ==>    Persisted data and properties have been restored.
mongo_1  | INFO  ==>    Any input specified will not take effect.
mongo_1  | INFO  ==> (Passwords are not shown for security reasons)
mongo_1  | INFO  ==> ########################################################################
mongo_1  | INFO  ==> 
mongo_1  | INFO  ==> ** MongoDB setup finished! **
mongo_1  | 
mongo_1  | INFO  ==> ** Starting MongoDB **
mongo_1  | 2019-07-11T06:51:01.509+0000 I CONTROL  [main] ***** SERVER RESTARTED *****
mongo_1  | 2019-07-11T06:51:01.511+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
mongo_1  | 2019-07-11T06:51:01.514+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/bitnami/mongodb/data/db 64-bit host=4087c8c2e664
mongo_1  | 2019-07-11T06:51:01.514+0000 I CONTROL  [initandlisten] db version v4.0.10
mongo_1  | 2019-07-11T06:51:01.514+0000 I CONTROL  [initandlisten] git version: c389e7f69f637f7a1ac3cc9fae843b635f20b766
mongo_1  | 2019-07-11T06:51:01.514+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.0k  28 May 2019
mongo_1  | 2019-07-11T06:51:01.514+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo_1  | 2019-07-11T06:51:01.514+0000 I CONTROL  [initandlisten] modules: none
mongo_1  | 2019-07-11T06:51:01.514+0000 I CONTROL  [initandlisten] build environment:
mongo_1  | 2019-07-11T06:51:01.515+0000 I CONTROL  [initandlisten]     distmod: debian92
mongo_1  | 2019-07-11T06:51:01.515+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongo_1  | 2019-07-11T06:51:01.515+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mongo_1  | 2019-07-11T06:51:01.515+0000 I CONTROL  [initandlisten] options: { config: "/opt/bitnami/mongodb/conf/mongodb.conf", net: { bindIpAll: true, ipv6: false, port: 27017, unixDomainSocket: { enabled: true, pathPrefix: "/opt/bitnami/mongodb/tmp" } }, processManagement: { fork: false, pidFilePath: "/opt/bitnami/mongodb/tmp/mongodb.pid" }, security: { authorization: "disabled" }, setParameter: { enableLocalhostAuthBypass: "true" }, storage: { dbPath: "/bitnami/mongodb/data/db", directoryPerDB: false, journal: { enabled: true } }, systemLog: { destination: "file", logAppend: true, logRotate: "reopen", path: "/opt/bitnami/mongodb/logs/mongodb.log", quiet: false, verbosity: 0 } }
mongo_1  | 2019-07-11T06:51:01.515+0000 I STORAGE  [initandlisten] Detected data files in /bitnami/mongodb/data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
mongo_1  | 2019-07-11T06:51:01.515+0000 I STORAGE  [initandlisten] 
mongo_1  | 2019-07-11T06:51:01.515+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
mongo_1  | 2019-07-11T06:51:01.515+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
mongo_1  | 2019-07-11T06:51:01.515+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=29678M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
mongo_1  | 2019-07-11T06:51:02.275+0000 I STORAGE  [initandlisten] WiredTiger message [1562827862:275366][1:0x7fb217367080], txn-recover: Main recovery loop: starting at 2/5248 to 3/256
mongo_1  | 2019-07-11T06:51:02.387+0000 I STORAGE  [initandlisten] WiredTiger message [1562827862:387521][1:0x7fb217367080], txn-recover: Recovering log 2 through 3
mongo_1  | 2019-07-11T06:51:02.456+0000 I STORAGE  [initandlisten] WiredTiger message [1562827862:456682][1:0x7fb217367080], txn-recover: Recovering log 3 through 3
mongo_1  | 2019-07-11T06:51:02.511+0000 I STORAGE  [initandlisten] WiredTiger message [1562827862:511262][1:0x7fb217367080], txn-recover: Set global recovery timestamp: 0
mongo_1  | 2019-07-11T06:51:02.525+0000 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
mongo_1  | 2019-07-11T06:51:02.535+0000 I CONTROL  [initandlisten] 
mongo_1  | 2019-07-11T06:51:02.535+0000 I CONTROL  [initandlisten] ** WARNING: You are running on a NUMA machine.
mongo_1  | 2019-07-11T06:51:02.535+0000 I CONTROL  [initandlisten] **          We suggest launching mongod like this to avoid performance problems:
mongo_1  | 2019-07-11T06:51:02.535+0000 I CONTROL  [initandlisten] **              numactl --interleave=all mongod [other options]
mongo_1  | 2019-07-11T06:51:02.535+0000 I CONTROL  [initandlisten] 
mongo_1  | 2019-07-11T06:51:02.554+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/bitnami/mongodb/data/db/diagnostic.data'
mongo_1  | 2019-07-11T06:51:02.557+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
```

This is the version I am running:

```
$ docker run --rm bitnami/mongodb:latest env | grep BITNAMI_IMAGE_VERSION

Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
Send us your feedback at containers@bitnami.com

BITNAMI_IMAGE_VERSION=4.0.10-debian-9-r47
```

Could you check that ?

**Comment by maksimenka** [comment]
CI start docker containers in parallel in one network. I don't use docker-compose for it.
This example from CircleCI documentation, i do the same with your image and your ENV variables:
```yaml
version: 2
jobs:
  build:
    working_directory: ~/appName
    docker:
      - image: ruby:2.3.1-jessie
        environment:
          PG_HOST: localhost
          PG_USER: ubuntu
          RAILS_ENV: test
          RACK_ENV: test
      # The following example uses the official postgres 9.6 image, you may also use circleci/postgres:9.6 
      # which includes a few enhancements and modifications. It is possible to use either image.
      - image: postgres:9.6-jessie
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: db_name
    steps:
      - checkout
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run: 
          name: Set up DB
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate
        environment:
          DATABASE_URL: "postgres://ubuntu@localhost:5432/db_name"
```
