### ISSUE TITLE
Connecting mongodb with domain not with ip address

### ISSUE THREAD

**Issue by rizwan92** [bitnami/bitnami-docker-mongodb#156]
hey, MongoDB bitnami,

I have successfully deployed MongoDB container using bitnami image I quite happy with that and I have successfully connected with that using mongo compass, 

Now I want to connect to my container not using the hostname as my server IP address instead I want to connect it to using my domain name.
` like hostname = "connect.mysite.com" not like hostname = "192.xx.xx.x"`

please suggest me any idea like nginx, nginx mostly use for HTTP, not for TCP.
is there any MongoDB container configuration which accepts DNS

**Comment by juan131** [comment]
Hi @rizwan92 

Are you connecting to your MongoDB container from another container? I mean, where are you running your MongoDB client? Please note that you can create a `docker-compose.yaml` like the one below:

```yaml
version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:4.0'
    volumes:
      - 'mongodb_data:/bitnami'
  client-container:
    image: 'your-client-image'
    depends_on:
      - mongodb
volumes:
  mongodb_data:
    driver: local
```

Using this scenario, you should be able to use the hostname 'mongodb' to access MongoDB from the 'client-container'. Docker itself will resolve the hostname 'mongodb' with the IP of the corresponding container.

**Comment by rizwan92** [comment]
any example of client image? I have no idea

**Comment by rizwan92** [comment]
I have already installed a client in my system now my requirement is to connect with a domain, not with IP address

**Comment by juan131** [comment]
> any example of client image? I have no idea

You can use another `bitnami/mongodb` image as a client. For instance, using the `docker-compose.yaml` below:

```yaml
version: '2'
services:
  mongo-server:
    image: 'bitnami/mongodb:4.0'
    volumes:
      - 'mongodb_data:/bitnami'
  client-container:
    image: 'bitnami/mongodb:4.0'
    command: sleep infinity
    depends_on:
      - mongodb
volumes:
  mongodb_data:
    driver: local
```

You can connect to the 'client-container' and use it as a MongoDB client:

```console
$ docker-compose up -d
$ docker-compose exec client-container bash
$ mongo mongo-server/my-database
```
