### ISSUE TITLE
Can not create user in custom initialization script

### ISSUE THREAD

**Issue by maoyi8212** [bitnami/bitnami-docker-mongodb#176]
**Description**

I am trying the executing custom scripts from /docker-entrypoint-initdb.d and I found that if I tried to create the user in the customized script, it does not work.

**Steps to reproduce the issue:**

1. create a customized script
```
#!/bin/bash
sleep 2m
mongo <<EOF
    use admin;
    db.auth('root', 'password123');
    db.createUser({user: 'test-user', pwd: 'test-passwd', roles: [{role: 'readWrite', db: 'test'}]});
EOF
```
2. Start the mongodb cluster by docker-compose file
```
version: '2'
services:
  mongodb-primary:
    image: 'bitnami/mongodb:4.0'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - './data:/bitnami'
      - './init:/docker-entrypoint-initdb.d'
      - './conf:/opt/bitnami/mongodb/conf'

  mongodb-secondary:
    image: 'bitnami/mongodb:4.0'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: 'bitnami/mongodb:4.0'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
```
3. After the cluster is deployed, when I log into the master node and try to do the db.auth('test-user','test-password'), it is failed

But if I create a user and database by MONGODB_USERNAME, MONGODB_PASSWORD and MONGODB_DATABASE environment variables, then do some other initialization such as createCollection, it seems works fine.  
**Steps to reproduce the issue:**

1. create a customized script
```
#!/bin/bash
sleep 2m
mongo <<EOF
    use test;
    db.auth('test-user','test-password');
    db.createCollection('product');
EOF
```
2. Start the mongodb cluster by docker-compose file
```
version: '2'
services:
  mongodb-primary:
    image: 'bitnami/mongodb:4.0'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_USERNAME=test-user
      - MONGODB_PASSWORD=test-password
      - MONGODB_DATABASE=test
    volumes:
      - './data:/bitnami'
      - './init:/docker-entrypoint-initdb.d'
      - './conf:/opt/bitnami/mongodb/conf'

  mongodb-secondary:
    image: 'bitnami/mongodb:4.0'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: 'bitnami/mongodb:4.0'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
```
3. After the cluster is deployed, when I log into the master node and try to show the collections, the "product" collection can be shown.

So my questions is whether it is possible to create table or user in the customized initialization script.  Anything wrong when I executing custom initialization script? Many thanks!
