### ISSUE TITLE
cannot create directory '/bitnami/mongodb': Permission denied

### ISSUE THREAD

**Issue by pankaj-dahiya** [bitnami/bitnami-docker-mongodb#177]
Unable to launch container , Error is "cannot create directory '/bitnami/mongodb': Permission denied"

I am using a fresh EC2 AWS t2.large machine (Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-04763b3055de4860b (64-bit x86)) . 

running container as : sudo docker-compose up

docker-compose.yml : 

version: '2.4'
services:
  mongodb:
    container_name: mongodb
    image: bitnami/mongodb
    environment:
      MONGODB_USERNAME: user1
      MONGODB_PASSWORD: pass1
    ports:
      - "27017:27017"
    volumes:
      - '/tmp/mongo:/bitnami'
    restart: "no"

Logs : 

mongodb    |  07:44:32.44 
mongodb    |  07:44:32.44 Welcome to the Bitnami mongodb container
mongodb    |  07:44:32.44 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb    |  07:44:32.44 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb    |  07:44:32.44 Send us your feedback at containers@bitnami.com
mongodb    |  07:44:32.44 
mongodb    |  07:44:32.45 INFO  ==> ** Starting MongoDB setup **
mongodb    |  07:44:32.46 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb    |  07:44:32.46 INFO  ==> Initializing MongoDB...
mongodb    |  07:44:32.46 INFO  ==> Deploying MongoDB from scratch...
mongodb    | mkdir: cannot create directory '/bitnami/mongodb': Permission denied
mongodb exited with code 1

**Comment by jotamartos** [comment]
Hi @pankaj-dahiya,

Thank you for using our containers. You are getting that error message because the container can't mount the /tmp/mongo directory you specified in the docker-compose.yml file.

As you can see in [our changelog](https://github.com/bitnami/bitnami-docker-mongodb#366-r16-and-411-r9), the container was migrated to the non-root user approach, that means that the user `1001` needs read/write permissions in the /tmp/mongo folder so it can be mounted and used. Can you modify the permissions in your local folder and try to launch the container again?

```
sudo chown -R 1001 /tmp/mongo
```

Thanks

**Comment by pankaj-dahiya** [comment]
Yeh that's working after changing the permission. 

My take - It should be the first and most important line of readme doc because every single person on earth using your containers will face this issue. Hence **mark this permission thing in Bold in readme** to save some time of engineers like me, who are new to this.

**Comment by pankaj-dahiya** [comment]
I expect the owners of this container to mention this permission thing in readme in bold, so that everyone will get aware about this thing.

**Comment by jotamartos** [comment]
Hi @pankaj-dahiya,

Thanks for the suggestion. We will create a task on our side to improve the information in the repository.

**Comment by margach** [comment]
This Permission Issue should be the first thing you say in the ReadMe file because it invalidates all the other instructions for running the containers.

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback on the documentation. I will forward it to the team for evaluation. Please note that mounting host path volumes is not the usual way to work with these containers. If using docker-compose, it would be using docker volumes (which already handle the permission issue), the same would apply with Kubernetes and the MongoDB helm chart, which would use the `securityContext` section to ensure the proper permissions.

**Comment by javsalgar** [comment]
Hi,

Thanks for the input! Note that you could set the `user:` section in the docker-compose file. Would that work for your use case?

**Comment by nodejsdeveloperskh** [comment]
> As you can see in [our changelog](https://github.com/bitnami/bitnami-docker-mongodb#366-r16-and-411-r9), the container was migrated to the non-root user approach, that means that the user `1001` needs read/write permissions in the /tmp/mongo folder so it can be mounted and used. 
> ```
> sudo chown -R 1001 /tmp/mongo
> ```

Why not **1000**?

I bind the MongoDB to a local diretory owned by 1000:1000. I think uid 1000 is more popular and useful.

**Comment by nodejsdeveloperskh** [comment]
> Thanks for the input! Note that you could set the `user:` section in the docker-compose file. Would that work for your use case?

`user` cause problem: 

`docker-compose.yml` file content: 

```yml
version: "3.7"

services:
  mongo:
    image: bitnami/mongodb:4.4-debian-10
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=pass
    container_name: test-mongodb
    hostname: test-mongodb
    ports:
      - 27027:27017
    volumes:
      - type: bind
        source: volume/data
        target: /bitnami/mongodb
        volume:
          nocopy: true
```

the error message: 
```cmd
WARN[0000] Found orphan containers ([mongorestore-db]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
WARN[0000] mount of type `bind` should not define `volume` option 
[+] Running 1/0
 ⠿ Container test-mongodb  Recreated                                                                                                                                                    0.1s
Attaching to test-mongodb
test-mongodb  | mongodb 06:28:28.05 
test-mongodb  | mongodb 06:28:28.05 Welcome to the Bitnami mongodb container
test-mongodb  | mongodb 06:28:28.05 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
test-mongodb  | mongodb 06:28:28.05 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
test-mongodb  | mongodb 06:28:28.05 
test-mongodb  | mongodb 06:28:28.06 INFO  ==> ** Starting MongoDB setup **
test-mongodb  | mongodb 06:28:28.07 INFO  ==> Validating settings in MONGODB_* env vars...
test-mongodb  | mongodb 06:28:28.09 INFO  ==> Initializing MongoDB...
test-mongodb  | mongodb 06:28:28.09 INFO  ==> Deploying MongoDB with persisted data...
test-mongodb  | 
test-mongodb  | mongodb 06:28:28.10 INFO  ==> ** MongoDB setup finished! **
test-mongodb  | mongodb 06:28:28.12 INFO  ==> ** Starting MongoDB **
test-mongodb  | Error opening config file: Permission denied
test-mongodb  | try '/opt/bitnami/mongodb/bin/mongod --help' for more information
test-mongodb exited with code 2
```

**Comment by alemorcuq** [comment]
I can't reproduce the issue. With your `docker-compose.yml` file I get a docker-compose error:

```yaml
version: "3.7"

services:
  mongo:
    image: bitnami/mongodb:4.4-debian-10
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=pass
    container_name: test-mongodb
    hostname: test-mongodb
    ports:
      - 27027:27017
    volumes:
      - type: bind
        source: volume/data
        target: /bitnami/mongodb
        volume:
          nocopy: true
```

```
ERROR: for test-mongodb  Cannot create container for service mongo: invalid mount config for type "bind": invalid mount path: 'volume/data' mount path must be absolute
```

Changing the path to an absolute one fixes this error and the container starts properly:

```yaml
version: "3.7"

services:
  mongo:
    image: bitnami/mongodb:4.4-debian-10
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=pass
    container_name: test-mongodb
    hostname: test-mongodb
    ports:
      - 27027:27017
    volumes:
      - type: bind
        source: ./volume/data
        target: /bitnami/mongodb
        volume:
          nocopy: true
```

```
test-mongodb | mongodb 07:42:35.30
test-mongodb | mongodb 07:42:35.30 Welcome to the Bitnami mongodb container
test-mongodb | mongodb 07:42:35.31 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
test-mongodb | mongodb 07:42:35.31 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
test-mongodb | mongodb 07:42:35.31
test-mongodb | mongodb 07:42:35.31 INFO  ==> ** Starting MongoDB setup **
test-mongodb | mongodb 07:42:35.33 INFO  ==> Validating settings in MONGODB_* env vars...
test-mongodb | mongodb 07:42:35.34 INFO  ==> Initializing MongoDB...
test-mongodb | mongodb 07:42:35.36 INFO  ==> Deploying MongoDB from scratch...
test-mongodb | mongodb 07:42:36.15 INFO  ==> Creating users...
test-mongodb | mongodb 07:42:36.15 INFO  ==> Creating root user...
test-mongodb | MongoDB shell version v4.4.11
test-mongodb | connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
test-mongodb | Implicit session: session { "id" : UUID("27b944ac-6e3c-47dc-a46f-d81092557325") }
test-mongodb | MongoDB server version: 4.4.11
test-mongodb | Successfully added user: {
test-mongodb | 	"user" : "root",
test-mongodb | 	"roles" : [
test-mongodb | 		{
test-mongodb | 			"role" : "root",
test-mongodb | 			"db" : "admin"
test-mongodb | 		}
test-mongodb | 	]
test-mongodb | }
test-mongodb | bye
test-mongodb | mongodb 07:42:36.28 INFO  ==> Users created
test-mongodb | mongodb 07:42:36.29 INFO  ==> Stopping MongoDB...
test-mongodb | mongodb 07:42:37.30 INFO  ==> Enabling authentication...
test-mongodb | mongodb 07:42:37.32 INFO  ==> ** MongoDB setup finished! **
test-mongodb |
test-mongodb | mongodb 07:42:37.34 INFO  ==> ** Starting MongoDB **
test-mongodb |
test-mongodb | {"t":{"$date":"2022-01-11T07:42:37.361+00:00"},"s":"I",  "c":"CONTROL",  "id":20698,   "ctx":"main","msg":"***** SERVER RESTARTED *****"}
...
```

The owner of `./volume/data` is user `1001`:

```
> ls -la ./volume/data
total 12K
drwxrwxr-x 3 1001 bitnami 4.0K 2022-01-11 07:42 ./
drwxrwxr-x 3 1001 bitnami 4.0K 2022-01-11 07:41 ../
drwxr-xr-x 3 1001 root    4.0K 2022-01-11 07:42 data/
```
