### ISSUE TITLE
Error: couldn't add user: command createUser requires authentication

### ISSUE THREAD

**Issue by pankaj-dahiya** [bitnami/bitnami-docker-mongodb#183]
Steps to replicate :
```bash
git clone https://github.com/bitnami/bitnami-docker-mongodb.git
cd bitnami-docker-mongodb/4.0/debian-9/
```
change user to root in Dockerfile.
```bash
docker build -t mongonew .
```
docker-compose.yml:
```yaml
version: '2.4'

services:
  mongodb:
    container_name: mongodb
    image: mongonew
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ROOT_PASSWORD: pmmp123
      MONGODB_REPLICA_SET_KEY: replicasetkey123
    ports:
      - "27017:27017"
    volumes:
      - '/opt/mongo:/bitnami'
      - './mongo:/docker-entrypoint-initdb.d'
    restart: "no"
    mem_limit: 1024m
    mem_reservation: 256m
    cpu_shares: 100
```
In Mongo folder, there is seed.sh file :
```bash
set -x

mongo --port 27017 <<Eof
use admin
db.createUser({user: "admin", pwd : "Hello@123", roles : [{role : "root", db : "admin"}]})
db.auth("admin", "Hello@123")
```
docker-compose up : 
```
Creating network "ubuntu_default" with the default driver
Creating mongodb ... done
Attaching to mongodb
mongodb    |  06:45:03.25 
mongodb    |  06:45:03.25 Welcome to the Bitnami mongodb container
mongodb    |  06:45:03.25 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb    |  06:45:03.25 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb    |  06:45:03.25 Send us your feedback at containers@bitnami.com
mongodb    |  06:45:03.25 
mongodb    |  06:45:03.25 INFO  ==> ** Starting MongoDB setup **
mongodb    |  06:45:03.26 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb    |  06:45:03.43 INFO  ==> Initializing MongoDB...
mongodb    |  06:45:03.44 WARN  ==> /bitnami/mongodb/data do not exist.
mongodb    |  06:45:03.44 INFO  ==> Deploying MongoDB from scratch...
mongodb    |  06:45:03.44 INFO  ==> No injected configuration files found. Creating default config files...
mongodb    |  06:45:04.43 INFO  ==> Creating users...
mongodb    |  06:45:04.43 INFO  ==> Creating root user...
mongodb    |  06:45:04.55 INFO  ==> Enabling authentication...
mongodb    |  06:45:04.56 INFO  ==> Users created
mongodb    |  06:45:04.56 INFO  ==> Writing keyfile for replica set authentication: replicasetkey123 /opt/bitnami/mongodb/conf/keyfile
mongodb    |  06:45:04.57 INFO  ==> Configuring MongoDB replica set...
mongodb    |  06:45:04.58 INFO  ==> Stopping MongoDB...
mongodb    |  06:45:06.96 INFO  ==> Configuring MongoDB primary node...: mongodb
mongodb    |  06:45:07.22 INFO  ==> Stopping MongoDB...
mongodb    |  06:45:22.24 INFO  ==> 
mongodb    |  06:45:22.24 INFO  ==> ########################################################################
mongodb    |  06:45:22.24 INFO  ==>  Installation parameters for MongoDB:
mongodb    |  06:45:22.24 INFO  ==>   Root Password: **********
mongodb    |  06:45:22.25 INFO  ==>   Replication Mode: primary
mongodb    |  06:45:22.25 INFO  ==> (Passwords are not shown for security reasons)
mongodb    |  06:45:22.25 INFO  ==> ########################################################################
mongodb    |  06:45:22.25 INFO  ==> 
mongodb    |  06:45:22.25 INFO  ==> Loading custom scripts...
mongodb    |  06:45:22.25 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
mongodb    | ++ mongo --port 27017
mongodb    | MongoDB shell version v4.0.13
mongodb    | connecting to: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb
mongodb    | Implicit session: session { "id" : UUID("4f0668ce-c561-42d0-bd5a-9c97f4ae3e15") }
mongodb    | MongoDB server version: 4.0.13
mongodb    | switched to db admin
mongodb    | 2019-11-04T06:45:23.424+0000 E QUERY    [js] Error: couldn't add user: command createUser requires authentication :
mongodb    | _getErrorWithCode@src/mongo/shell/utils.js:25:13
mongodb    | DB.prototype.createUser@src/mongo/shell/db.js:1491:15
mongodb    | @(shell):1:1
mongodb    | Error: Authentication failed.
mongodb    | 0
```
