### ISSUE TITLE
Root user not created 

### ISSUE THREAD

**Issue by pilvikala** [bitnami/bitnami-docker-mongodb#184]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------
**Description**

When starting a new container with MONGODB_ROOT_PASSWORD environment variable specified, the root user is not created, unless the MONGODB_REPLICA_SET_MODE variable is set as well. This is not mentioned in the documentation.

**Steps to reproduce the issue:**

1. Start a new container supplying the MONGODB_ROOT_PASSWORD, MONGODB_PASSWORD, MONGODB_USER, and MONGODB_DATABASE variables.
2. Check the container logs

**Describe the results you received:**

The user specified in the MONGODB_USER variable is created.
The root user is not created.

**Describe the results you expected:**

Both the root and the MONGODB_USER are created and announced in the logs.

**Additional information you deem important (e.g. issue happens only occasionally):**
The issue seems to be in the evaluation of this condition:
https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.2/debian-9/rootfs/libmongodb.sh#L506

Workaround:
Set the MONGODB_REPLICA_SET_MODE=primary when starting the container.

**Version**
4.2
- Output of `docker version`:

```
Docker version 19.03.2, build 6a30dfca03
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-18-generic
 Operating System: Ubuntu 19.10
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.844GiB
 Name: localhost
 ID: VG42:3SYA:AHJP:JG7Y:KE7X:RMU2:NLVO:F5GY:QLPP:7JTW:EIIS:N2QQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

```

**Comment by rafariossaa** [comment]
Hi @pilvikala ,
  Thanks for reporting this.
  We will try to fix it as soon as possible.

  We will reach you as soon as it is fixed.

**Comment by rafariossaa** [comment]
Hi @pilvikala ,
  If spotted the problem, the environment variable for the user name is MONGODB_USERNAME, and you are using MONGODB_USER.
  Could you give it a try ?

**Comment by cfchad** [comment]
I am experiencing the same issue. all environment variables 
- MONGODB_USERNAME=
- MONGODB_ROOT_PASSWORD=
- MONGODB_PASSWORD=
- MONGODB_DATABASE=

Not sure if these logs help...

``` 14:55:09.88 INFO  ==> ** Starting MongoDB setup **
 14:55:09.91 INFO  ==> Validating settings in MONGODB_* env vars...
 14:55:09.91 INFO  ==> Initializing MongoDB...
 14:55:09.92 INFO  ==> No injected configuration files found. Creating default config files...
 14:55:09.90 INFO  ==> Enabling authentication...
 14:55:09.90 INFO  ==> Deploying MongoDB with persisted data...
 14:55:09.91 INFO  ==>
 14:55:09.91 INFO  ==> ########################################################################
 14:55:09.91 INFO  ==>  Installation parameters for MongoDB:
 14:55:09.92 INFO  ==>    Persisted data and properties have been restored.
 14:55:09.92 INFO  ==>    Any input specified will not take effect.
 14:55:09.92 INFO  ==> (Passwords are not shown for security reasons)
 14:55:09.92 INFO  ==> ########################################################################
 14:55:09.92 INFO  ==>
 14:55:09.93 INFO  ==> Loading custom scripts...
find: '/docker-entrypoint-initdb.d/': No such file or directory

**Comment by rafariossaa** [comment]
Hi,
  Could you give a try to the following `docker-compose.yml` file ?

```
version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:4.0'
    environment:
      - BITNAMI_DEBUG=true
      - MONGODB_USERNAME=my_user 
      - MONGODB_PASSWORD=password123
      - MONGODB_ROOT_PASSWORD=password456
      - MONGODB_DATABASE=my_database
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'

volumes:
  mongodb_data:
    driver: local
```
Just in case, please delete old volumes and mongo images.

**Comment by pilvikala** [comment]
> Hi @pilvikala ,
> If spotted the problem, the environment variable for the user name is MONGODB_USERNAME, and you are using MONGODB_USER.
> Could you give it a try ?

That was just a "typo" in my first report. I actually used the MONGODB_USERNAME (just checked my docker-compose).

**Comment by rafariossaa** [comment]
Hi, @pilvikala 
  Could you share your docker-compose ?
  I am unable to reproduce the issue you are suffering.

**Comment by pilvikala** [comment]
> Hi, @pilvikala
> Could you share your docker-compose ?
> I am unable to reproduce the issue you are suffering.

I am trying again and I can't reproduce that anymore either.

**Comment by xgdgsc** [comment]
I' m using 4.0 and found I cannot login with root with MONGODB_ROOT_PASSWORD set, I can with my MONGODB_USERNAME though. But how I can do administritive task with my user? Is there a way I can add permissions without recreating?

```
version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:4.0'
    ports:
      - "27018:27017"
    volumes:
      - '/home/gsc/mongo:/bitnami'
    environment:
      - MONGODB_ROOT_PASSWORD=PASSWORD
      - MONGODB_USERNAME=my_name
      - MONGODB_PASSWORD=PASSWORD
      - MONGODB_DATABASE=db_name
    restart: always

volumes:
  mongodb_data:
    driver: local

```
