### ISSUE TITLE
Change default port, does it work?

### ISSUE THREAD

**Issue by rodrigorodriguescosta** [bitnami/bitnami-docker-mongodb#202]
I'm using the default docker-compose and it works, I'd like to change only the port exposed by container to another port, the **docker-compose** below is the same in the documentation changing only the exposed port

I'dl like to change the port due I'm using Cloud Run and it doesn't provide VPC connection, so I have to expose to internet with authentication, changing the default port would be extra security measure 

When I change default port, the connection error shows on console, can't we change the default port?

![image](https://user-images.githubusercontent.com/3034127/76715510-76950400-670b-11ea-8ae0-70c546b797bf.png)

Also, I received the alert email about that deploy from Digital Ocean

![image](https://user-images.githubusercontent.com/3034127/76715638-fde27780-670b-11ea-8380-ba57698a8ba5.png)

```
version: '2'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

    volumes:
      - 'mongodb_master_data:/bitnami'
    ports:
      - 30001:27017

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=30001
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=30001
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  mongodb_master_data:
    driver: local
```
