### ISSUE TITLE
Mongo replica set is not reachable in docker swarm cluster

### ISSUE THREAD

**Issue by riibeirogabriel** [bitnami/bitnami-docker-mongodb#210]
I has deployed a mongo replica set in my swarm cluster, with a mongo-primary, mongo-sencudary and mongo-abritrary services, in bellow my .yml file:

`
version: '3'

services:
    database_api:
        build: ./database_api_service
        image: 127.0.0.1:5050/database_api:database_api
        ports:
            - "5000:5000"
        depends_on:
            - mongodb-primary
            - images
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - "node.role==worker"
        networks:
            - database
        environment:
            - DATABASE_URL=mongodb://root:password123@mongodb-primary
            - DATABASE_PORT=27017 

    mongodb-primary:
        image: 'bitnami/mongodb:latest'
        environment:
            - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
            - MONGODB_REPLICA_SET_MODE=primary
            - MONGODB_ROOT_PASSWORD=password123
            - MONGODB_REPLICA_SET_KEY=replicasetkey123
    
        volumes:
            - 'mongodb_master_data:/bitnami'
        networks:
            - database
            
    mongodb-secondary:
        image: 'bitnami/mongodb:latest'
        depends_on:
            - mongodb-primary
        environment:
            - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
            - MONGODB_REPLICA_SET_MODE=secondary
            - MONGODB_PRIMARY_HOST=mongodb-primary
            - MONGODB_PRIMARY_PORT_NUMBER=27017
            - MONGODB_PRIMARY_ROOT_PASSWORD=password123
            - MONGODB_REPLICA_SET_KEY=replicasetkey123
        networks:
            - database
    mongodb-arbiter:
        image: 'bitnami/mongodb:latest'
        depends_on:
         - mongodb-primary
        environment:
            - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
            - MONGODB_REPLICA_SET_MODE=arbiter
            - MONGODB_PRIMARY_HOST=mongodb-primary
            - MONGODB_PRIMARY_PORT_NUMBER=27017
            - MONGODB_PRIMARY_ROOT_PASSWORD=password123
            - MONGODB_REPLICA_SET_KEY=replicasetkey123
        networks:
            - database
    images:
        image: registry:2
        ports:
            - "5050:5000"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - "node.role==manager"

        networks:
            - database
        volumes:
            - images:/var/lib/registry

    visualizer:
        image: dockersamples/visualizer
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
        - "8080:8080"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                  - "node.role==manager"

networks:
    database:

volumes:
    images:
    mongodb_master_data:
`

but, when my database_api service or mongo local try connecting in mongodb-primary, the error is showed:
`
mongo -u root -p password123 --host mongodb-primary
MongoDB shell version v4.2.6
connecting to: mongodb://mongodb-primary:27017/?compressors=disabled&gssapiServiceName=mongodb
2020-05-01T11:56:54.920+0000 E  QUERY    [js] Error: couldn't connect to server mongodb-primary:27017, connection attempt failed: HostNotFound: Could not find address for
 mongodb-primary:27017: SocketException: Host not found (authoritative) :
connect@src/mongo/shell/mongo.js:341:17
`
Someone might help me? thanks

**Comment by harmnot** [comment]
I have same error when  run ` mongo -u root -p 'password123' --host 'mongodb-primary' `, how do solve this ? @riibeirogabriel

**Comment by juan131** [comment]
Hi @harmnot 

Where are you running that command? Are you running it inside the Docker network? Please note that `mongodb-primary` hostname won't resolve outside Docker.

Can you also try using the command below instead?

```
mongo admin --username root --password 'password123' --host 'mongodb-primary'
```

**Comment by harmnot** [comment]
I am running outside in Docker , so is it not possible to run them outside from Docker ? how can I connect to mongodb compass ?? @juan131

**Comment by juan131** [comment]
Yes, you can access PostgreSQL outside Docker @harmnot . But in that case you cannot use `mongodb-primary` hostname since that's internal to Docker.

Could you share the command or the Docker Compose you're using to deploy MongoDB? I'll provide you the instructions to access MongoDB from the outside.

**Comment by harmnot** [comment]
I follow this issue [#219](https://github.com/bitnami/bitnami-docker-mongodb/issues/219#issue-627764649) and change the hostname and then I can run 
```
mongo --username root --password 'password123' --host 'localhost'       
```

so I dont need to use `/?replicaset=rs0` anymore when I run bitnami mongodb , right ?

**Comment by harmnot** [comment]
try run in my Go app with this URI: `mongodb://root:password123@localhost:27017`
always got `context deadline exceeded`

**Comment by juan131** [comment]
Hi @harmnot 

If you're running your Golang app in the same machine you're running the Mongo client, then it should be able to access your MongoDB Database. 

Doublecheck you're using a MongoDB driver that's compatible with the version 4.2 of MongoDB (the one you're using in the MongoDB container).  You can also try adding a forward slash at the end:

```
mongodb://root:password123@localhost:2701/
```

**Comment by harmnot** [comment]
here is my docker-compose.yml 
```
version: "3.7"

services:
  mongodb01:
    image: "bitnami/mongodb:4.2"
    hostname: mongodb01.dev.com
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb01.dev.com
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
    volumes:
      - "mongodb01_data:/bitnami/mongodb"
    networks:
      mongodb:
        aliases:
          - mongodb01.dev.com

  mongodb02:
    image: "bitnami/mongodb:4.2"
    hostname: mongodb02.dev.com
    ports:
      - 27018:27018
    restart: always
    depends_on:
      - mongodb01
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb02.dev.com
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_PRIMARY_HOST=mongodb01.dev.com
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_PORT_NUMBER=27018
    volumes:
      - "mongodb02_data:/bitnami/mongodb"
    networks:
      mongodb:
        aliases:
          - mongodb02.dev.com

  mongodb03:
    image: "bitnami/mongodb:4.2"
    hostname: mongodb03.dev.com
    ports:
      - 27019:27019
    restart: always
    depends_on:
      - mongodb02
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb03.dev.com
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_PRIMARY_HOST=mongodb01.dev.com
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_PORT_NUMBER-27019
    volumes:
      - "mongodb03_data:/bitnami/mongodb"
    networks:
      mongodb:
        aliases:
          - mongodb03.dev.com

volumes:
  mongodb01_data:
  mongodb02_data:
  mongodb03_data:

networks:
  mongodb:
```
I can connect to MongoDB compass  with:
`mongodb://root:password123@localhost:2701/`
but I cant run it in MongoDB driver in Golang , got 
```
context deadline exceeded
```
