### ISSUE TITLE
Mongodb not creating root user after redeploying in kubernetes

### ISSUE THREAD

**Issue by sasmellors** [bitnami/bitnami-docker-mongodb#214]
**Description**

I am trying to deploy mongodb to a kubernetes cluster, here are some key details:

- image: mongodb:4.2.6-debian-10-r23 used first 
- image: mongodb:4.2.6-debian-10-r34 used as a test to see if it would fix the issue
- persistent volume is created for deployment and mounted to /bitnami/mongodb
- Kubernetes master version: 1.15.11-gke.3

The issue is when deploying this mongodb instance, it does not register a "from scratch" deployment. In the setup.sh file, line 28 calls the `mongodb_initialize` function, however since mongo doesn't think the deployment is from scratch the if statement on line 991 of libmongodb.sh is not executed. The effect of this is when I try to deploy mongodb with a root password, the root user is never made and I can not log in

From what I have gathered, when the scripts are running, mongo seems to think `"$MONGODB_DATA_DIR/db"` is not empty, even though it's a fresh install. 

**Steps to reproduce the issue:**

1. I applied the following manifests in kubernetes

**secret.yaml**
```
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: default
  labels:
    app: mongodb
    release: mongodb
type: Opaque
data:
  mongodb-root-password: xxxxxx
```
**svc.yaml**
```
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: default
  labels:
    app: mongodb
    release: mongodb
spec:
  type: NodePort
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
      nodePort: 30222
  selector:
    app: mongodb
    release: mongodb
```
**statefulset.yml**

```
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongodb
    release: mongodb
  name: mongodb
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: mongodb
      release: mongodb
  serviceName: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        release: mongodb
    spec:
      containers:
      - env:
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb-root-password
              name: mongodb
        - name: MONGODB_SYSTEM_LOG_VERBOSITY
          value: "0"
        - name: MONGODB_DISABLE_SYSTEM_LOG
          value: "no"
        - name: MONGODB_ENABLE_IPV6
          value: "no"
        - name: MONGODB_ENABLE_DIRECTORY_PER_DB
          value: "no"
        image: docker.io/bitnami/mongodb:4.2.6-debian-10-r23
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - db.adminCommand('ping')
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: mongodb
        ports:
        - containerPort: 27017
          name: mongodb
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - db.adminCommand('ping')
          failureThreshold: 6
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        volumeMounts:
        - mountPath: /bitnami/mongodb
          name: data
      securityContext:
        fsGroup: 1001
      volumes:
      - emptyDir: {}
        name: data
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
```
2. I deleted the resources in k8s using `kubectl delete`
Then, I found out if I delete the persistent volume it would get stuck saying "terminating"
In order to fix this I would run `kubectl edit pv <pv_name>` to then delete 2 lines from under the metadata block

```
  finalizers:
  - kubernetes.io/pv-protection
```
After removing these lines I would save the resource and the PV would be deleted
I then deleted the PVC 

3. Once all mongo resources in k8s have been deleted I would repeat the 1st step by redeploying the manifests again. This then puts me in the situation where Mongo doesn't think it's installing from scratch and therefore doesn't create a root user.

**Describe the results you received:**

 After redeploying, in the start up logs I get the following:

```
mongodb 14:09:15.01 INFO  ==> ** Starting MongoDB setup **
mongodb 14:09:15.03 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 14:09:15.05 INFO  ==> Initializing MongoDB...
mongodb 14:09:15.08 INFO  ==> Enabling authentication...
mongodb 14:09:15.09 INFO  ==> Deploying MongoDB with persisted data...
mongodb 14:09:15.10 INFO  ==> Loading custom scripts...
mongodb 14:09:15.11 INFO  ==> ** MongoDB setup finished! **
```
and then when trying to log in as root I get the following in the network logs:

```
2020-05-13T15:14:16.740+0000 I  NETWORK  [conn777] received client metadata from 172.30.232.25:37374 conn777: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.2.6" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 9 (stretch)"", architecture: "x86_64", version: "Kernel 4.9.0-9-amd64" } }
2020-05-13T15:14:16.741+0000 I  SHARDING [conn777] Marking collection admin.system.users as collection version: <unsharded>
2020-05-13T15:14:16.741+0000 I  ACCESS   [conn777] Supported SASL mechanisms requested for unknown user 'root@admin'
2020-05-13T15:14:16.741+0000 I  ACCESS   [conn777] SASL SCRAM-SHA-1 authentication failed for root on admin from client 172.30.232.25:37374 ; UserNotFound: Could not find user "root" for db "admin"
```

**Describe the results you expected:**

After redeploying I expect to see the following:

```
mongodb 10:42:30.63 INFO  ==> ** Starting MongoDB setup **
mongodb 10:42:30.65 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 10:42:30.67 INFO  ==> Initializing MongoDB...
mongodb 10:42:30.69 INFO  ==> Deploying MongoDB from scratch...
mongodb 10:42:31.45 INFO  ==> Creating users...
mongodb 10:42:31.45 INFO  ==> Creating root user...
mongodb 10:42:31.61 INFO  ==> Users created
mongodb 10:42:31.62 INFO  ==> Stopping MongoDB...
mongodb 10:42:32.65 INFO  ==> Enabling authentication...
mongodb 10:42:32.66 INFO  ==> Loading custom scripts...

mongodb 10:42:32.66 INFO  ==> ** MongoDB setup finished! **

```
and then I expect root@admin to be found and be able to log in with my password

**Additional information you deem important (e.g. issue happens only occasionally):**
This happens every single time now so I can't deploy mongodb at all. I have also tried updating the image to use `docker.io/bitnami/mongodb:4.2.6-debian-10-r34` and the issue still happens.

**Version**

- Output of `docker version`:
Kubernetes master version: 1.15.11-gke.3
This version supports the following docker versions:
1.13.1, 17.03, 17.06, 17.09, 18.06, 18.09

more info can be found here 
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.15.md#changelog-since-v11510

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Using GKE cluster
