### ISSUE TITLE
Replicaset setup with wrong Port

### ISSUE THREAD

**Issue by ricaragao** [bitnami/bitnami-docker-mongodb#219]
**Description**

I'm creating a replicaset of Mongo 4.2 in a Swarm cluster. The problem is that configuration of PORT on compose file not is been respected and replica is up with default port 27017. This happen when I have 3 replicas.

**Steps to reproduce the issue:**

1. [First Step]

```
version: '3.4'

services:
  mongodb01:
    image: 'bitnami/mongodb:4.2'
    hostname: mongodb01.brasiliahost.com
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb01.brasiliahost.com
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_ROOT_PASSWORD=xxxxxx
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
    volumes:
      - 'mongodb01_data:/bitnami/mongodb'
    networks:
      mongodb:
        aliases:
          - mongodb01.brasiliahost.com
    deploy:
      placement:
        constraints:
          - "node.hostname==docker-node-1.novalocal"

  mongodb02:
    image: 'bitnami/mongodb:4.2'
    hostname: mongodb02.brasiliahost.com
    ports:
      - 27018:27018
    restart: always
    depends_on:
      - mongodb01
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb02.brasiliahost.com
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_PRIMARY_HOST=mongodb01.brasiliahost.com
      - MONGODB_PRIMARY_ROOT_PASSWORD=xxxxxx
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_PORT_NUMBER=27018
    volumes:
      - 'mongodb02_data:/bitnami/mongodb'
    networks:
      mongodb:
        aliases:
          - mongodb02.brasiliahost.com
    deploy:
      placement:
        constraints:
          - "node.hostname==docker-node-2.novalocal"

  mongodb03:
    image: 'bitnami/mongodb:4.2'
    hostname: mongodb03.brasiliahost.com
    ports:
      - 27019:27019
    restart: always
    depends_on:
      - mongodb02
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb03.brasiliahost.com
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_PRIMARY_HOST=mongodb01.brasiliahost.com
      - MONGODB_PRIMARY_ROOT_PASSWORD=xxxxxx
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_PORT_NUMBER:27019
    volumes:
      - 'mongodb03_data:/bitnami/mongodb'
    networks:
      mongodb:
        aliases:
          - mongodb03.brasiliahost.com
    deploy:
      placement:
        constraints:
          - "node.hostname==docker-node-3.novalocal"

volumes:
  mongodb01_data:
  mongodb02_data:
  mongodb03_data:

networks:
  mongodb:
``` 

**Describe the results you received:**

rs.status()

```
{
	"set" : "rs0",
	"date" : ISODate("2020-05-30T16:00:05.008Z"),
	"myState" : 1,
	"term" : 4,
	"syncingTo" : "",
	"syncSourceHost" : "",
	"syncSourceId" : -1,
	"heartbeatIntervalMillis" : 2000,
	"majorityVoteCount" : 2,
	"writeMajorityCount" : 2,
	"optimes" : {
		"lastCommittedOpTime" : {
			"ts" : Timestamp(1590854398, 1),
			"t" : 4
		},
		"lastCommittedWallTime" : ISODate("2020-05-30T15:59:58.920Z"),
		"readConcernMajorityOpTime" : {
			"ts" : Timestamp(1590854398, 1),
			"t" : 4
		},
		"readConcernMajorityWallTime" : ISODate("2020-05-30T15:59:58.920Z"),
		"appliedOpTime" : {
			"ts" : Timestamp(1590854398, 1),
			"t" : 4
		},
		"durableOpTime" : {
			"ts" : Timestamp(1590854398, 1),
			"t" : 4
		},
		"lastAppliedWallTime" : ISODate("2020-05-30T15:59:58.920Z"),
		"lastDurableWallTime" : ISODate("2020-05-30T15:59:58.920Z")
	},
	"lastStableRecoveryTimestamp" : Timestamp(1590854378, 1),
	"lastStableCheckpointTimestamp" : Timestamp(1590854378, 1),
	"electionCandidateMetrics" : {
		"lastElectionReason" : "priorityTakeover",
		"lastElectionDate" : ISODate("2020-05-30T15:26:48.513Z"),
		"electionTerm" : 4,
		"lastCommittedOpTimeAtElection" : {
			"ts" : Timestamp(1590852407, 1),
			"t" : 3
		},
		"lastSeenOpTimeAtElection" : {
			"ts" : Timestamp(1590852407, 1),
			"t" : 3
		},
		"numVotesNeeded" : 2,
		"priorityAtElection" : 5,
		"electionTimeoutMillis" : 10000,
		"priorPrimaryMemberId" : 2,
		"numCatchUpOps" : 0,
		"newTermStartDate" : ISODate("2020-05-30T15:26:48.817Z"),
		"wMajorityWriteAvailabilityDate" : ISODate("2020-05-30T15:26:50.900Z")
	},
	"members" : [
		{
			"_id" : 0,
			"name" : "mongodb01.brasiliahost.com:27017",
			"health" : 1,
			"state" : 1,
			"stateStr" : "PRIMARY",
			"uptime" : 2009,
			"optime" : {
				"ts" : Timestamp(1590854398, 1),
				"t" : 4
			},
			"optimeDate" : ISODate("2020-05-30T15:59:58.000Z"),
			"syncingTo" : "",
			"syncSourceHost" : "",
			"syncSourceId" : -1,
			"infoMessage" : "",
			"electionTime" : Timestamp(1590852408, 1),
			"electionDate" : ISODate("2020-05-30T15:26:48.000Z"),
			"configVersion" : 3,
			"self" : true,
			"lastHeartbeatMessage" : ""
		},
		{
			"_id" : 1,
			"name" : "mongodb03.brasiliahost.com:27017",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 2006,
			"optime" : {
				"ts" : Timestamp(1590854398, 1),
				"t" : 4
			},
			"optimeDurable" : {
				"ts" : Timestamp(1590854398, 1),
				"t" : 4
			},
			"optimeDate" : ISODate("2020-05-30T15:59:58.000Z"),
			"optimeDurableDate" : ISODate("2020-05-30T15:59:58.000Z"),
			"lastHeartbeat" : ISODate("2020-05-30T16:00:04.552Z"),
			"lastHeartbeatRecv" : ISODate("2020-05-30T16:00:04.536Z"),
			"pingMs" : 0,
			"lastHeartbeatMessage" : "",
			"syncingTo" : "mongodb01.brasiliahost.com:27017",
			"syncSourceHost" : "mongodb01.brasiliahost.com:27017",
			"syncSourceId" : 0,
			"infoMessage" : "",
			"configVersion" : 3
		},
		{
			"_id" : 2,
			"name" : "mongodb02.brasiliahost.com:27018",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 456,
			"optime" : {
				"ts" : Timestamp(1590854398, 1),
				"t" : 4
			},
			"optimeDurable" : {
				"ts" : Timestamp(1590854398, 1),
				"t" : 4
			},
			"optimeDate" : ISODate("2020-05-30T15:59:58.000Z"),
			"optimeDurableDate" : ISODate("2020-05-30T15:59:58.000Z"),
			"lastHeartbeat" : ISODate("2020-05-30T16:00:04.574Z"),
			"lastHeartbeatRecv" : ISODate("2020-05-30T16:00:04.725Z"),
			"pingMs" : 0,
			"lastHeartbeatMessage" : "",
			"syncingTo" : "mongodb01.brasiliahost.com:27017",
			"syncSourceHost" : "mongodb01.brasiliahost.com:27017",
			"syncSourceId" : 0,
			"infoMessage" : "",
			"configVersion" : 3
		}
	],
	"ok" : 1,
	"$clusterTime" : {
		"clusterTime" : Timestamp(1590854398, 1),
		"signature" : {
			"hash" : BinData(0,"C2v4+RsF9Ts3uKLZwDgLxs2dtKM="),
			"keyId" : 6832255235117809668
		}
	},
	"operationTime" : Timestamp(1590854398, 1)
}
``` 

**Describe the results you expected:**

Port of replica 3 = 27019

```
                         "_id" : 1,
			"name" : "mongodb03.brasiliahost.com:27019",
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 3
  Paused: 0
  Stopped: 1
 Images: 12
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: sudjmeh9wwoomaq3eo0m7m0u8
  Is Manager: true
  ClusterID: 3u3ne0n0ofyki1k71iwnsmww5
  Managers: 3
  Nodes: 3
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.0.0.13
  Manager Addresses:
   10.0.0.13:2377
   10.0.0.14:2377
   10.0.0.6:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.8.2.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 991MiB
 Name: docker-node-1.novalocal
 ID: DEQ6:YZGT:2ZKA:MTPF:IXYE:HGKX:66ID:A532:EDMY:4NAS:ZBO3:D7E6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Host OS: CentOS Linux release 7.8.2003 (Core)

**Comment by joancafom** [comment]
Hi  @ricaragao ,

Thanks for posting your `docker-compose.yml` file, it helps a lot reproducing the issue. I think it is all due to this line in your third mongo instance:

```yaml
mongodb03:
  ...
    environment:
      ...
      - MONGODB_PORT_NUMBER:27019
      ...
```

This line is using a colon (`:`) instead of an equal sign (`=`) and thus the container is not setting the env var properly. I have changed it and checked that `rs.status()` returns the correct port now.

Hope it helps and thanks for reaching us out!

**Comment by ricaragao** [comment]
@joancafom , thank you so much. I reviewed my yml many times and I can't to see this simple syntax error. 

Thank you for your fast support.

**Comment by harmnot** [comment]
what is the URI foe connect to mongodb compass ? @ricaragao @joancafom

**Comment by joancafom** [comment]
Hi @harmnot ,

Could you provide me with a little bit of context please? Is your MongoDB docker instance running local? Where are you running mongodb compass?

Thanks!

**Comment by harmnot** [comment]
I run mongodb docker in local , and here is the docker-compose.yml:
```
version: "3.7"

services:
  mongodb01:
    image: "bitnami/mongodb:4.2"
    hostname: mongodb01.dev.com
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb01.dev.com
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
    volumes:
      - "mongodb01_data:/bitnami/mongodb"
    networks:
      mongodb:
        aliases:
          - mongodb01.dev.com

  mongodb02:
    image: "bitnami/mongodb:4.2"
    hostname: mongodb02.dev.com
    ports:
      - 27018:27018
    restart: always
    depends_on:
      - mongodb01
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb02.dev.com
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_PRIMARY_HOST=mongodb01.dev.com
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_PORT_NUMBER=27018
    volumes:
      - "mongodb02_data:/bitnami/mongodb"
    networks:
      mongodb:
        aliases:
          - mongodb02.dev.com

  mongodb03:
    image: "bitnami/mongodb:4.2"
    hostname: mongodb03.dev.com
    ports:
      - 27019:27019
    restart: always
    depends_on:
      - mongodb02
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb03.dev.com
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_PRIMARY_HOST=mongodb01.dev.com
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_PORT_NUMBER-27019
    volumes:
      - "mongodb03_data:/bitnami/mongodb"
    networks:
      mongodb:
        aliases:
          - mongodb03.dev.com

volumes:
  mongodb01_data:
  mongodb02_data:
  mongodb03_data:

networks:
  mongodb:
```

I can run into mongodb compoass local but can't run with my Go app

always got timepout and can't connected I think
