### ISSUE TITLE
cannot upgrade  due to MONGODB_ROOT_PASSWORD

### ISSUE THREAD

**Issue by joshribakoff** [bitnami/bitnami-docker-mongodb#238]
**Description**

No matter what I put for auth.enabled or architecture, after installing I can never upgrade, but MONGODB_ROOT_PASSWORD is set.

```
apiVersion: v2
name: chart
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: sha-0f72070

dependencies:
  - name: mongodb
    version: 9.3.1
    repository: https://charts.bitnami.com/bitnami


mongodb:
  # architecture: replicaset
  auth.enabled: false
```

```
➜  mergetrain git:(main) ✗ helm install bot backend-chart --set auth.rootPassword=$MONGODB_ROOT_PASSWORD
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/joshribakoff/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/joshribakoff/.kube/config
NAME: bot
LAST DEPLOYED: Sat Nov 14 09:23:24 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=chart,app.kubernetes.io/instance=bot" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT
➜  mergetrain git:(main) ✗ helm upgrade bot backend-chart --set auth.rootPassword=$MONGODB_ROOT_PASSWORD
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/joshribakoff/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/joshribakoff/.kube/config
Error: UPGRADE FAILED: template: chart/charts/mongodb/templates/NOTES.txt:192:4: executing "chart/charts/mongodb/templates/NOTES.txt" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" (list $requiredPasswordValidationErrors) "context" $)>: error calling include: template: chart/charts/mongodb/charts/common/templates/_errors.tpl:18:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail: 
PASSWORDS ERROR: you must provide your current passwords when upgrade the release
    'auth.rootPassword' must not be empty, please add '--set auth.rootPassword=$MONGODB_ROOT_PASSWORD' to the command. To get the current value:

        export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default bot-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)

➜  mergetrain git:(main) ✗ echo $MONGODB_ROOT_PASSWORD
r0JTlPnry8
➜  mergetrain git:(main) ✗ 
```

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
 Kubernetes:
  Version:          v1.19.2
  StackAPI:         Unknown
```

- Output of `docker info`:

```
Containers: 10
 Running: 3
 Paused: 0
 Stopped: 7
Images: 37
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.786GiB
Name: linuxkit-025000000001
ID: CZ6R:FNE7:MBK7:HWDF:7W7F:K6MC:6XQR:T3XD:3ACR:SS43:YIHF:US3M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 49
 Goroutines: 72
 System Time: 2020-11-14T17:28:40.0777384Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

n/a

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

using minikube on mac to test

**Comment by andresbono** [comment]
Hi @joshribakoff, it is possible that the problem comes from the fact that mongodb is being used as a subchart in your case.

You may need to pass the value like `--set mongodb.auth.rootPassword=$MONGODB_ROOT_PASSWORD`

Can you try that?

Also, I'm not really sure that the following block applies into the `Chart.yaml` file:

```yaml
mongodb:
  # architecture: replicaset
  auth.enabled: false
```

You may want to add that in the `values.yaml` instead, and with the proper structure:

```yaml
mongodb:
  # architecture: replicaset
  auth:
    enabled: false
```

Let us know if you solves the issue.
