### ISSUE TITLE
Connecting to mongodb via node.js mongoose gives ReplicaSetNoPrimary

### ISSUE THREAD

**Issue by kaykhancheckpoint** [bitnami/bitnami-docker-mongodb#240]
**Description**

Im trying to connect to mongo via node.js using mongoose package. I'm unsure if this is a mongo configuration issue or a node.js mongoose application issue.

**Steps to reproduce the issue:**

1. `docker-compose up`
2. `ts-node mongo.service.ts`

**Describe the results you received:**
```
MongooseServerSelectionError: getaddrinfo EAI_AGAIN mongodb-primary
    at NativeConnection.Connection.openUri (/home/kay/checkpoint/stream-hatchet/node_modules/mongoose/lib/connection.js:800:32)
    at /home/kay/checkpoint/stream-hatchet/node_modules/mongoose/lib/index.js:341:10
    at /home/kay/checkpoint/stream-hatchet/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/kay/checkpoint/stream-hatchet/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Mongoose.connect (/home/kay/checkpoint/stream-hatchet/node_modules/mongoose/lib/index.js:340:10)
    at Object.MongoDBService [as default] (/home/kay/checkpoint/stream-hatchet/src/services/mongodb.service.ts:22:24)
    at Streaming (/home/kay/checkpoint/stream-hatchet/src/main.ts:16:29)
    at Object.<anonymous> (/home/kay/checkpoint/stream-hatchet/src/main.ts:38:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module.m._compile (/home/kay/checkpoint/stream-hatchet/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/home/kay/checkpoint/stream-hatchet/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    setName: 'replicaset',
    maxSetVersion: 61323,
    maxElectionId: 7fffffff0000000000000002,
    servers: Map {
      'mongodb-primary:27017' => [ServerDescription],
      'mongodb-arbiter:27017' => [ServerDescription]
    },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: 9
  }
}

```

**Describe the results you expected:**

Successfully connect

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 19.03.13, build 4484c46d9d
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
Client:
 Debug Mode: false

Server:
 Containers: 15
  Running: 2
  Paused: 0
  Stopped: 13
 Images: 134
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-53-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.5GiB
 Name: khan
 ID: U4DA:KICR:7CIF:TE6K:E3QU:ZCQW:BRGR:2L5V:3ZEA:DJPX:T23H:VB6V
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

**docker-compose.yml**

```
version: '2'

services:
  mongodb-primary:
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    ports:
      - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'

  mongodb-arbiter:
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  mongodb_master_data:
    driver: local
```

**mongo.service.ts**

```
    import mongoose from "mongoose";
    
    const MongoDBService = async () => {
    
        try {
    
            const connectionString = "mongodb://root:password123@localhost:27017/streamhatchet?authSource=admin&replicaSet=replicaset&retryWrites=true"

            const options = {
              useNewUrlParser: true,
              useUnifiedTopology: true,
              useCreateIndex: true,
              useFindAndModify: false,
              autoIndex: true,
              poolSize: 10,
              serverSelectionTimeoutMS: 30000,
              socketTimeoutMS: 75000,
              family: 4,
              keepAlive: true, 
              keepAliveInitialDelay: 300000,
            };

            await mongoose.connect(connectionString, options);
    
        } catch (error) {
            console.log(error);
        }
    
        mongoose.connection.on("error", (err) => {
           console.log(error);
        });
    };
    
    
    export default MongoDBService;

```

**Comment by kaykhancheckpoint** [comment]
**Update**:
This maybe more to do with a mongodb configuration issue as oppose to a node.js/mongoose connection issue. The reason is because im able to connect using the same code to my live production replicaset. By just changing the parts in the connection string `mongodb://<username>:<password>@<host>:27017?replicaSet=<replicasetname>`

**Comment by juan131** [comment]
Hi @kaykhancheckpoint 

It seems you're not exposing the ports in the Docker Compose, so you cannot connect from the host. 

(already answered on this issue: https://github.com/bitnami/bitnami-docker-mongodb/issues/239)

**Comment by kaykhancheckpoint** [comment]
@juan131 if you see my docker-compose file you can see im exposing the port

**Comment by juan131** [comment]
The MongoDB node is using "mongodb-primary" as "advertised hostname":

```console
MongooseServerSelectionError: getaddrinfo EAI_AGAIN mongodb-primary
```

But that's an internal hostname (I mean, internal to Docker network), so your host doesn't know how to solve it. Try setting the `MONGODB_ADVERTISED_HOSTNAME` env var to `localhost` (since your client is accessing MongoDB through localhost). MOre info at:

- https://github.com/bitnami/bitnami-docker-mongodb#setting-up-replication

**Comment by kaykhancheckpoint** [comment]
@juan131 

So my temporary fix (removing replicaset=replicaset) stopped working when i updated mongoose to version  5.11.x from 5.10.x

Adding `MONGODB_ADVERTISED_HOSTNAME=localhost` to my docker file had no effect and i get the same error message.

docker-compose.yml
```
version: '2'

services:
  mongodb-primary:
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    ports:
      - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'

  mongodb-arbiter:
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ADVERTISED_HOSTNAME=localhost

volumes:
  mongodb_master_data:
    driver: local
```

**Comment by kaykhancheckpoint** [comment]
@juan131 
So my temporary fix (removing replicaset=replicaset) stopped working when i updated mongoose to version  5.11.x from 5.10.x
Adding `MONGODB_ADVERTISED_HOSTNAME=localhost` to my docker file had no effect and i get the same error message.
docker-compose.yml
```
version: '2'

services:
  mongodb-primary:
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    ports:
      - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'

  mongodb-arbiter:
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=localhost
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  mongodb_master_data:
    driver: local
``` 

```
{"message":{"error":{"message":"getaddrinfo EAI_AGAIN mongodb-primary","reason":{"type":"ReplicaSetNoPrimary","setName":"replicaset","maxSetVersion":288476,"maxElectionId":"7fffffff000000000000002a","servers":{},"stale":false,"compatible":true,"compatibilityError":null,"logicalSessionTimeoutMinutes":null,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"commonWireVersion":9}},"error_stack":"MongooseServerSelectionError: getaddrinfo EAI_AGAIN mongodb-primary\n    at NativeConnection.Connection.openUri (/home/kay/checkpoint/stream-hatchet/node_modules/mongoose/lib/connection.js:832:32)\n    at /home/kay/checkpoint/stream-hatchet/node_modules/mongoose/lib/index.js:345:10\n    at /home/kay/checkpoint/stream-hatchet/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (/home/kay/checkpoint/stream-hatchet/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)\n    at Mongoose._promiseOrCallback (/home/kay/checkpoint/stream-hatchet/node_modules/mongoose/lib/index.js:1135:10)\n    at Mongoose.connect (/home/kay/checkpoint/stream-hatchet/node_modules/mongoose/lib/index.js:344:20)\n    at Object.MongoDBService [as default] (/home/kay/checkpoint/stream-hatchet/src/services/mongodb.service.ts:18:24)\n    at Streaming (/home/kay/checkpoint/stream-hatchet/src/main.ts:15:29)\n    at Object.<anonymous> (/home/kay/checkpoint/stream-hatchet/src/main.ts:37:1)\n    at Module._compile (internal/modules/cjs/loader.js:1137:30)\n    at Module.m._compile (/home/kay/checkpoint/stream-hatchet/node_modules/ts-node/src/index.ts:858:23)\n    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)\n    at Object.require.extensions.<computed> [as .ts] (/home/kay/checkpoint/stream-hatchet/node_modules/ts-node/src/index.ts:861:12)\n    at Module.load (internal/modules/cjs/loader.js:985:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:878:14)"},"level":"error","timestamp":"2020-12-11T13:33:36.194Z"}
```
