### ISSUE TITLE
Error when connect to replica set

### ISSUE THREAD

**Issue by gancarzradoslaw** [bitnami/bitnami-docker-mongodb#248]
Hi,

I have the following docker-compose.yaml:

```yaml
version: '2'

services:
  mongodb-primary:
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'
    ports:
      - 30001:27017

  mongodb-secondary:
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - 30002:27017

  mongodb-arbiter:
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - 30003:27017

volumes:
  mongodb_master_data:
    driver: local
```

When I try to connect to primary or secondary node I am able to do that, but when I try connect to replica set by using this connection string:
`mongodb://root:password123@localhost:30001,localhost:30002/?replicaSet=replicaset&readPreference=secondary` widh disabled tls, my Robo 3T cannot connect.

What can be wrong with the configuration?

Thanks
