### ISSUE TITLE
Readiness probe fails when activating externalAccess

### ISSUE THREAD

**Issue by lusu007** [bitnami/bitnami-docker-mongodb#250]
**Description**

Readiness probe fails when activating externalAccess. Only the first instance of the replicaset tries to start. It is probably a configuration error on my site because I'm getting the newly added error message (#244).

**Steps to reproduce the issue:**

1. Deploy the following values.yaml via Helm in your cluster.
```
namespace: &mongodbNamespace stage-mongodb
mongodb:
  global:
    namespaceOverride: *mongodbNamespace
    imagePullSecrets:
      - dockerhub
    storageClass: csi-cinder-high-speed
  architecture: replicaset
  auth:
    database: admin
    username: legend
    existingSecret: mongodb-secret
  replicaSetName: mongodb
  replicaCount: 3
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: global-prometheus-stack
  externalAccess:
    enabled: true
    service:
      type: NodePort
      nodePorts:
        - 31000
        - 31001
        - 31002
```

**Describe the results you received:**

MongoDB readiness probe fails and no further replicaset members started.

**Describe the results you expected:**

I expect that all my replicaset members are coming up and external access is activated.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:32 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020   
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 92
  Running: 68
  Paused: 0
  Stopped: 24
 Images: 51
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-135-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 28.75GiB
 Name: general-node-c7e76c
 ID: JDJF:XDXO:I3LG:W2MY:NGU4:PLOI:HZOX:SZLO:SWRG:4X4R:LGCI:GHAU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
OVH Managed Kubernetes (Kubernetes Version 1.19.5-1)
