### ISSUE TITLE
Infinity loop restarting without error on swarm

### ISSUE THREAD

**Issue by GrishaDev** [bitnami/bitnami-docker-mongodb#255]
**Edit**
I fixed it by changing version of docker swarm file from 3 to 3.3
Very weird but seems to work now, keeping it open for now if the issue might happen again, or maybe you know why its happening exactly.

**Description**

I am trying to run mongodb container in swarm mode, from stack deploy yml file.
the container starts but restarts infinity times with no errors on swarm mode.

**Steps to reproduce the issue:**

1. create stack deploy yml with mongodb things, aka:
```
mongo:
        image: bitnami/mongodb:latest
        restart: unless-stopped
        # env_file: swarm.env
        user: root
        # environment:
        #     # - MONGO_INITDB_ROOT_USERNAME=admin
        #     # - MONGO_INITDB_ROOT_PASSWORD=password
        #     # - MONGO_INITDB_DATABASE = g
        #     - MONGODB_ROOT_PASSWORD=password1
        #     - MONGODB_USERNAME=guser
        #     - MONGODB_PASSWORD=password2
        #     - MONGODB_DATABASE=g
        ports:
            - "27017:27017"
        # volumes:
        #     - /volume:/bitnami/mongodb/data
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.labels.manager == 1
```

2. docker stack deploy -c docker-swarm.yml something
3. wait abit
4. and it goes into infinity restart

 **What actually happens**

![image](https://user-images.githubusercontent.com/6249988/113857740-8d414980-97ab-11eb-9d85-b9684bd599f8.png)

if image doesnt load then:

```
migration_mongo.1.uins2lgecs2o@e7d323572f7d    | mongodb 11:14:27.82 Welcome to the Bitnami mongodb container
migration_mongo.1.uins2lgecs2o@e7d323572f7d    | mongodb 11:14:27.82 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
migration_mongo.1.uins2lgecs2o@e7d323572f7d    | mongodb 11:14:27.83 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
migration_mongo.1.uins2lgecs2o@e7d323572f7d    | mongodb 11:14:27.83 
migration_mongo.1.uins2lgecs2o@e7d323572f7d    | mongodb 11:14:27.83 INFO  ==> ** Starting MongoDB setup **
migration_mongo.1.uins2lgecs2o@e7d323572f7d    | mongodb 11:14:27.84 INFO  ==> Validating settings in MONGODB_* env vars...
migration_mongo.1.uins2lgecs2o@e7d323572f7d    | mongodb 11:14:27.98 INFO  ==> Initializing MongoDB...
migration_mongo.1.uins2lgecs2o@e7d323572f7d    | mongodb 11:14:27.99 INFO  ==> Deploying MongoDB from scratch...
migration_mongo.1.wz5c2ach1wyu@e7d323572f7d    | mongodb 11:14:35.39 
migration_mongo.1.wz5c2ach1wyu@e7d323572f7d    | mongodb 11:14:35.39 Welcome to the Bitnami mongodb container
migration_mongo.1.wz5c2ach1wyu@e7d323572f7d    | mongodb 11:14:35.40 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
migration_mongo.1.wz5c2ach1wyu@e7d323572f7d    | mongodb 11:14:35.40 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
migration_mongo.1.wz5c2ach1wyu@e7d323572f7d    | mongodb 11:14:35.40 
migration_mongo.1.wz5c2ach1wyu@e7d323572f7d    | mongodb 11:14:35.40 INFO  ==> ** Starting MongoDB setup **
migration_mongo.1.wz5c2ach1wyu@e7d323572f7d    | mongodb 11:14:35.41 INFO  ==> Validating settings in MONGODB_* env vars...
migration_mongo.1.wz5c2ach1wyu@e7d323572f7d    | mongodb 11:14:35.54 INFO  ==> Initializing MongoDB...
migration_mongo.1.wz5c2ach1wyu@e7d323572f7d    | mongodb 11:14:35.56 INFO  ==> Deploying MongoDB from scratch...
```

 **What you expect to happen**

for the container to run succesfuly

**Any additional information, configuration or data that might be necessary to reproduce the issue.**

I tried pruning, restarting, different image version, and inspecting the container that everything is correct, it seems it is correct.

**Version**

Docker version 19.03.12, build 48a66213fe
