### ISSUE TITLE
Allow the journal to be disabled.

### ISSUE THREAD

**Issue by guanzo** [bitnami/bitnami-docker-mongodb#256]
Related: https://github.com/bitnami/bitnami-docker-mongodb/issues/132#issuecomment-815645760

There should be some config that lets users disable the journal.

**Comment by alvneiayu** [comment]
hi @guanzo 

Thanks to report the issue. I created an internal task and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news.

Thanks

Álvaro

**Comment by carrodher** [comment]
Hi, in each branch's latest tags, it should be possible to enable/disable journaling by using an environment variable.
You can find more information in this README section: https://github.com/bitnami/bitnami-docker-mongodb#enablingdisabling-journaling

-----------------------------------

- Without setting any extra env. variable, the default value should be `true`:
```
I have no name!@9bc282cd38e1:/$ cat /opt/bitnami/mongodb/conf/mongodb.conf
# mongod.conf
# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# where and how to store data.
storage:
  dbPath: /bitnami/mongodb/data/db
  journal:
    enabled: true
  directoryPerDB: false
```

- Setting `MONGODB_ENABLE_JOURNAL=true` in the docker-compose:
```
I have no name!@a866524c998b:/$ cat /opt/bitnami/mongodb/conf/mongodb.conf
# mongod.conf
# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# where and how to store data.
storage:
  dbPath: /bitnami/mongodb/data/db
  journal:
    enabled: true
  directoryPerDB: false
```

- Setting `MONGODB_ENABLE_JOURNAL=false` in the docker-compose:
```
I have no name!@a866524c998b:/$ cat /opt/bitnami/mongodb/conf/mongodb.conf
# mongod.conf
# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# where and how to store data.
storage:
  dbPath: /bitnami/mongodb/data/db
  journal:
    enabled: false
  directoryPerDB: false
```
-----------------------------------

Please, feel free to reopen the issue if something is not working as expected.
