### ISSUE TITLE
Initialize Databases and User on Master

### ISSUE THREAD

**Issue by busyboy77** [bitnami/bitnami-docker-mongodb#260]
**Description**

Database and Users Initialization Script is not loading as expected.

**Steps to reproduce the issue:**

1. My Docker Compose on Master
```yaml
version: '2'

services:
  node1:
    image: 'bitnami/mongodb:latest'
    ports:
      - 27017:27017
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_ADVERTISED_HOSTNAME=node1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=replicaset
      - BITNAMI_DEBUG=true

    extra_hosts:
      - "node1:192.168.2.230"
      - "node2:192.168.2.233"
      - "node3:192.168.2.234"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
      - './mongo/initdb/init.js:/docker-entrypoint-initdb.d/init.js'
volumes:
  mongodb_data:
    driver: local
```

my Secondary docker-compose.yml

```yaml
version: '2'

services:
  node2:
    image: 'bitnami/mongodb:latest'
    ports:
      - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=node2
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=node1
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=replicaset
      - BITNAMI_DEBUG=true
    extra_hosts:
      - "node1:192.168.2.230"
      - "node2:192.168.2.233"
      - "node3:192.168.2.234"
    volumes:
      - 'mongodb_data:/bitnami'

volumes:
  mongodb_data:
    driver: local
```
and finally the Arbiter Node docker-compose.yml

```yaml
version: '2'
services:
  node3:
    image: 'bitnami/mongodb:latest'
    ports:
      - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=node3
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=node1
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=replicaset
      - BITNAMI_DEBUG=true
    extra_hosts:
      - "node1:192.168.2.230"
      - "node2:192.168.2.233"
      - "node3:192.168.2.234"
```

my init.js

```javascript
db = db.getSiblingDB('dbuser');
db.createUser(
        {
            user: "dbuserUser",
            pwd: "sixty61",
            roles: [
                {
                    role: "readWrite",
                    db: "dbuser"
                }
            ]
        }
);
db = db.getSiblingDB('solutiondb');
db.createUser(
        {
            user: "connector",
            pwd: "sixty64",
            roles: [
                {
                    role: "readWrite",
                    db: "solutiondb"
                }
            ]
        }
);
```

2. now when I start the Master, I  can see that it has executed the init.js script, like this

```console
$ docker-compose -f mongo-dc.yml up
Creating volume "root_mongodb_data" with local driver
Creating root_node1_1 ... done
Attaching to root_node1_1
node1_1  | mongodb 10:22:40.07
node1_1  | mongodb 10:22:40.08 Welcome to the Bitnami mongodb container
node1_1  | mongodb 10:22:40.08 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
node1_1  | mongodb 10:22:40.09 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
node1_1  | mongodb 10:22:40.09
node1_1  | mongodb 10:22:40.09 INFO  ==> ** Starting MongoDB setup **
node1_1  | mongodb 10:22:40.13 INFO  ==> Validating settings in MONGODB_* env vars...
node1_1  | mongodb 10:22:40.17 INFO  ==> Initializing MongoDB...
node1_1  | mongodb 10:22:40.21 INFO  ==> Deploying MongoDB from scratch...
node1_1  | mongodb 10:22:40.22 DEBUG ==> Starting MongoDB in background...
node1_1  | about to fork child process, waiting until server is ready for connections.
node1_1  | forked process: 40
node1_1  | child process started successfully, parent exiting
node1_1  | mongodb 10:22:42.03 INFO  ==> Creating users...
node1_1  | mongodb 10:22:42.03 INFO  ==> Creating root user...
node1_1  | mongodb 10:22:42.43 INFO  ==> Users created
node1_1  | mongodb 10:22:42.44 INFO  ==> Writing keyfile for replica set authentication...
node1_1  | mongodb 10:22:42.50 INFO  ==> Configuring MongoDB replica set...
node1_1  | mongodb 10:22:42.52 INFO  ==> Stopping MongoDB...
node1_1  | mongodb 10:22:43.54 DEBUG ==> Starting MongoDB in background...
node1_1  | about to fork child process, waiting until server is ready for connections.
node1_1  | forked process: 128
node1_1  | child process started successfully, parent exiting
node1_1  | mongodb 10:22:46.98 INFO  ==> Configuring MongoDB primary node
node1_1  | mongodb 10:22:47.88 INFO  ==> Stopping MongoDB...
node1_1  | mongodb 10:22:49.92 INFO  ==> Enabling authentication...
node1_1  | mongodb 10:22:49.96 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
node1_1  | mongodb 10:22:49.96 DEBUG ==> Starting MongoDB in background...
node1_1  | about to fork child process, waiting until server is ready for connections.
node1_1  | forked process: 265
node1_1  | child process started successfully, parent exiting
node1_1  | mongodb 10:22:52.60 DEBUG ==> Executing /docker-entrypoint-initdb.d/init.js
node1_1  | MongoDB shell version v4.4.5
node1_1  | connecting to: mongodb://node1:27017/?compressors=disabled&gssapiServiceName=mongodb
node1_1  | Implicit session: session { "id" : UUID("aa14bfa2-676a-4347-a3bd-eb292a9200d3") }
node1_1  | MongoDB server version: 4.4.5
node1_1  | Error: Authentication failed.
node1_1  | 0
node1_1  | dbuser
node1_1  | Successfully added user: {
node1_1  |      "user" : "dbuserUser",
node1_1  |      "roles" : [
node1_1  |              {
node1_1  |                      "role" : "readWrite",
node1_1  |                      "db" : "dbuser"
node1_1  |              }
node1_1  |      ]
node1_1  | }
node1_1  | solutiondb
node1_1  | Successfully added user: {
node1_1  |      "user" : "connector",
node1_1  |      "roles" : [
node1_1  |              {
node1_1  |                      "role" : "readWrite",
node1_1  |                      "db" : "solutiondb"
node1_1  |              }
node1_1  |      ]
node1_1  | }
node1_1  | bye
node1_1  | mongodb 10:22:53.02 INFO  ==> Stopping MongoDB...
node1_1  |
node1_1  | mongodb 10:22:54.05 INFO  ==> ** MongoDB setup finished! **
node1_1  | mongodb 10:22:54.08 INFO  ==> ** Starting MongoDB **
node1_1  |
node1_1  | {"t":{"$date":"2021-04-22T10:22:54.148+00:00"},"s":"I",  "c":"CONTROL",  "id":20698,   "ctx":"main","msg":"***** SERVER RESTARTED *****"}
```

3. after starting up the Secondary and Arbiter,  when I log into the master, I can see that there is nothing created neither Databases  nor users

```console
$ docker exec -it -u 0 root_node1_1 bash
root@5ddb6139301a:/# mongo -u root -p
MongoDB shell version v4.4.5
Enter password:
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("f8d50050-7a81-4eab-aa41-bf9626bfb158") }
MongoDB server version: 4.4.5
---
replicaset:PRIMARY> show dbs
admin   0.000GB
config  0.000GB
local   0.000GB
replicaset:PRIMARY> show users
replicaset:PRIMARY> use admin
switched to db admin
replicaset:PRIMARY> exit
bye
root@5ddb6139301a:/#
```

**Describe the results you received:**

The Database and User initialization scripts are executed but never worked. 

**Describe the results you expected:**

The initialization script should have been executed to run and complete its operation of creating users and databases.
**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```console
$ docker version
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:33:55 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:32:17 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```console
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 26
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.21.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 9.606GiB
 Name: devbox
 ID: P4MX:F6EQ:MIYX:XZO5:YBXJ:GNIJ:2FEY:PPNU:LW5K:MT7P:IAQI:Y5WR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```console
$ docker-compose version
docker-compose version 1.28.6, build unknown
docker-py version: 4.4.4
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Its a KVM based VM running CentOS-7

```console
$ uname -a
Linux  devbox 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 18:28:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
and /etc/os-release
```console
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

Can someone suggest what is wrong here. the normal Mongo image works perfectly fine when running in replication, but bitnami image is having above issue.
