### ISSUE TITLE
Cannot setup keyfile authentication

### ISSUE THREAD

**Issue by namlt3820** [bitnami/bitnami-docker-mongodb#262]
**Steps to reproduce the issue:**

1. Create a keyfile `openssl rand -base64 756 > /data/shard.key`
2. My docker-compose file 
```
version: '2'
services:
  shard-config:
    container_name: shard-config
    image: docker.io/bitnami/mongodb:4.4
    ports:
      - '27017:27017'
    volumes:
      - 'shard-config:/bitnami/mongodb'
      - '/data/shard.key:/data/shard.key'
    environment:
      - MONGODB_EXTRA_FLAGS=--configsvr --replSet=shard-config --keyFile=/data/shard.key
volumes:
  shard-config:
    driver: local
```
3. docker-compose up --build

**Describe the results you received:**
The container exited with code 1

**Describe the results you expected:**
The mongodb container start successfully with keyfile authentication

**Additional information**
From mongo docs, it seems that I only need to add --keyFile option to enable authentication
```
mongod --keyFile <path-to-keyfile> --replSet <replicaSetName> --bind_ip localhost,<hostname(s)|ip address(es)>
```
Adding that option to MONGODB_EXTRA_FLAGS caused the crash. Removed it and the container run fine. So I dont know what's wrong here. Can someone please point out? Thanks
