### ISSUE TITLE
Enable RBAC after configuring the sharded cluster to use SSL/TLS connection?

### ISSUE THREAD

**Issue by namlt3820** [bitnami/bitnami-docker-mongodb#265]
I understand this is a more mongodb related question but yesterday when I set up a keyfile authentication method, after that, the RBAC was added automatically, I can create user admin, cluster admin, db users etc and can only connect to the cluster with those accounts. Today I removed the keyfile, created some free Letsencrypt certificates and attempted to set up tls connection between sharded members. The cluster is up and running, but without RBAC. I create some administrative users via mongos, but I can still connect to mongos without an account. Something is missing here, maybe it's related to x509 certificates? Can someone give me a few keywords about what I have to do next? Thank you.

**Comment by namlt3820** [comment]
**Steps to reproduce the issue:**

1. Acquire LetsEncrypt certificates via certbot, store them at /etc/letsencrypt/live/example.com/ for three servers
2. Generate mongodb and CA pem files according to this [tutorial](https://serverfault.com/questions/805971/how-to-correctly-configure-mongodb-to-use-letsencrypt-ssl-on-ubuntu), store them at /etc/ssl/mongo for each server
3. Run docker-compose.yml for each server
```
version: '2'

services:
  shard-config:
    container_name: shard-config
    image: docker.io/bitnami/mongodb:4.4
    ports:
      - "27017:27017"
    volumes:
      - 'shard-config:/bitnami/mongodb'
      - '/etc/ssl/mongo:/certificates/'
    environment:
      - MONGODB_EXTRA_FLAGS=--configsvr --replSet=shard-config --tlsMode=preferTLS --tlsCertificateKeyFile=/certificates/mongo.pem --tlsClusterFile=/certificates/mongo.pem --tlsCAFile=/certificates/ca.pem --clusterAuthMode=x509 --auth
    restart: on-failure
  shard-mongos:
    container_name: shard-mongos
    image: docker.io/bitnami/mongodb:4.4
    ports:
      - "27021:27017"
    volumes:
      - '/etc/ssl/mongo:/certificates/'
    command: [ "mongos", "-tlsMode", "preferTLS", "-tlsCertificateKeyFile", "/certificates/mongo.pem", "-tlsClusterFile", "/certificates/mongo.pem", "-tlsCAFile", "/certificates/ca.pem", "-clusterAuthMode", "x509", "-auth","-configdb", "${SHARD_CONFIG_RS}", "-bind_ip", "0.0.0.0" ]
  shard-member-1:
    container_name: shard-member-1
    image: docker.io/bitnami/mongodb:4.4
    ports:
      - "27018:27017"
    volumes:
      - 'shard-member-1:/bitnami/mongodb'
      - '/etc/ssl/mongo:/certificates/'
    environment:
      - MONGODB_EXTRA_FLAGS=--shardsvr --replSet=shard-member-1 --tlsMode=preferTLS --tlsCertificateKeyFile=/certificates/mongo.pem --tlsClusterFile=/certificates/mongo.pem --tlsCAFile=/certificates/ca.pem --clusterAuthMode=x509 --auth
    restart: on-failure
  shard-member-2:
    container_name: shard-member-2
    image: docker.io/bitnami/mongodb:4.4
    ports:
      - "27019:27017"
    volumes:
      - 'shard-member-2:/bitnami/mongodb'
      - '/etc/ssl/mongo:/certificates/'
    environment:
      - MONGODB_EXTRA_FLAGS=--shardsvr --replSet=shard-member-2 --tlsMode=preferTLS --tlsCertificateKeyFile=/certificates/mongo.pem --tlsClusterFile=/certificates/mongo.pem --tlsCAFile=/certificates/ca.pem --clusterAuthMode=x509 --auth
    restart: on-failure
  shard-member-3:
    container_name: shard-member-3
    image: docker.io/bitnami/mongodb:4.4
    ports:
      - "27020:27017"
    volumes:
      - 'shard-member-3:/bitnami/mongodb'
      - '/etc/ssl/mongo:/certificates/'
    environment:
      - MONGODB_EXTRA_FLAGS=--shardsvr --replSet=shard-member-3 --tlsMode=preferTLS --tlsCertificateKeyFile=/certificates/mongo.pem --tlsClusterFile=/certificates/mongo.pem --tlsCAFile=/certificates/ca.pem --clusterAuthMode=x509 --auth
    restart: on-failure
volumes:
  shard-config:
    driver: local
  shard-member-1:
    driver: local
  shard-member-2:
    driver: local
  shard-member-3:
    driver: local
```
4. Access one of the config server, run 
```
rs.initiate(
  {
    _id: "shard-config",
    configsvr: true,
    members: [
      { _id : 0, host : "host1:27017" },
      { _id : 1, host : "host2:27017" },
      { _id : 2, host : "host3:27017" }
    ]
  }
)
```

**Describe the results you received:**
Error: command replSetInitiate requires authentication

**Describe the results you expected:**
Config server replica set configured successfully

**Additional information**
The .pem files don't seem to be working. I can decode them with command `openssl x509 -in mongo.pem -text -noout` but here is the docker container logs from config server, with "No TransportLayer configured during NetworkInterface startup"
```
mongodb 23:30:58.81
mongodb 23:30:58.81 Welcome to the Bitnami mongodb container
mongodb 23:30:58.82 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 23:30:58.82 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 23:30:58.82
mongodb 23:30:58.82 INFO  ==> ** Starting MongoDB setup **
mongodb 23:30:58.83 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 23:30:58.84 INFO  ==> Initializing MongoDB...
mongodb 23:30:58.86 INFO  ==> Deploying MongoDB with persisted data...
mongodb 23:30:58.86 INFO  ==> ** MongoDB setup finished! **

mongodb 23:30:58.88 INFO  ==> ** Starting MongoDB **

{"t":{"$date":"2021-05-25T23:30:58.899+00:00"},"s":"I",  "c":"CONTROL",  "id":20698,   "ctx":"main","msg":"***** SERVER RESTARTED *****"}
{"t":{"$date":"2021-05-25T23:30:58.899+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
{"t":{"$date":"2021-05-25T23:30:58.904+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
{"t":{"$date":"2021-05-25T23:30:58.904+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
{"t":{"$date":"2021-05-25T23:30:58.905+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/bitnami/mongodb/data/db","architecture":"64-bit","host":"7f95d0803946"}}
{"t":{"$date":"2021-05-25T23:30:58.905+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.6","gitVersion":"72e66213c2c3eab37d9358d5e78ad7f5c1d0d0d7","openSSLVersion":"OpenSSL 1.1.1d  10 Sep 2019","modules":[],"allocator":"tcmalloc","environment":{"distmod":"debian10","distarch":"x86_64","target_arch":"x86_64"}}}}
{"t":{"$date":"2021-05-25T23:30:58.905+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"PRETTY_NAME=\"Debian GNU/Linux 10 (buster)\"","version":"Kernel 5.4.0-72-generic"}}}
{"t":{"$date":"2021-05-25T23:30:58.905+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"config":"/opt/bitnami/mongodb/conf/mongodb.conf","net":{"bindIp":"*","ipv6":false,"port":27017,"tls":{"CAFile":"/certificates/ca.pem","certificateKeyFile":"/certificates/mongo.pem","clusterFile":"/certificates/mongo.pem","mode":"preferTLS"},"unixDomainSocket":{"enabled":true,"pathPrefix":"/opt/bitnami/mongodb/tmp"}},"processManagement":{"fork":false,"pidFilePath":"/opt/bitnami/mongodb/tmp/mongodb.pid"},"replication":{"replSet":"shard-member-1"},"security":{"authorization":"enabled","clusterAuthMode":"x509"},"setParameter":{"enableLocalhostAuthBypass":"true"},"sharding":{"clusterRole":"shardsvr"},"storage":{"dbPath":"/bitnami/mongodb/data/db","directoryPerDB":false,"journal":{"enabled":true}},"systemLog":{"destination":"file","logAppend":true,"logRotate":"reopen","path":"/opt/bitnami/mongodb/logs/mongodb.log","quiet":false,"verbosity":0}}}}
{"t":{"$date":"2021-05-25T23:30:58.906+00:00"},"s":"I",  "c":"CONNPOOL", "id":22576,   "ctx":"CurlConnPool-0","msg":"Connecting","attr":{"hostAndPort":"r3.o.lencr.org:80"}}
{"t":{"$date":"2021-05-25T23:30:58.907+00:00"},"s":"I",  "c":"STORAGE",  "id":22270,   "ctx":"initandlisten","msg":"Storage engine to use detected by data files","attr":{"dbpath":"/bitnami/mongodb/data/db","storageEngine":"wiredTiger"}}
{"t":{"$date":"2021-05-25T23:30:58.907+00:00"},"s":"I",  "c":"STORAGE",  "id":22297,   "ctx":"initandlisten","msg":"Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem","tags":["startupWarnings"]}
{"t":{"$date":"2021-05-25T23:30:58.907+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=15458M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}}
{"t":{"$date":"2021-05-25T23:30:59.327+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1621985459:327780][1:0x7f3d342d7140], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 2 through 3"}}
{"t":{"$date":"2021-05-25T23:30:59.362+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1621985459:362140][1:0x7f3d342d7140], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 3 through 3"}}
{"t":{"$date":"2021-05-25T23:30:59.419+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1621985459:419361][1:0x7f3d342d7140], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Main recovery loop: starting at 2/13696 to 3/256"}}
{"t":{"$date":"2021-05-25T23:30:59.481+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1621985459:481143][1:0x7f3d342d7140], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 2 through 3"}}
{"t":{"$date":"2021-05-25T23:30:59.517+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1621985459:517519][1:0x7f3d342d7140], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 3 through 3"}}
{"t":{"$date":"2021-05-25T23:30:59.546+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1621985459:546820][1:0x7f3d342d7140], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Set global recovery timestamp: (0, 0)"}}
{"t":{"$date":"2021-05-25T23:30:59.546+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1621985459:546855][1:0x7f3d342d7140], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Set global oldest timestamp: (0, 0)"}}
{"t":{"$date":"2021-05-25T23:30:59.547+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1621985459:547474][1:0x7f3d342d7140], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 1, snapshot max: 1 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0)"}}
{"t":{"$date":"2021-05-25T23:30:59.549+00:00"},"s":"I",  "c":"STORAGE",  "id":4795906, "ctx":"initandlisten","msg":"WiredTiger opened","attr":{"durationMillis":642}}
{"t":{"$date":"2021-05-25T23:30:59.549+00:00"},"s":"I",  "c":"RECOVERY", "id":23987,   "ctx":"initandlisten","msg":"WiredTiger recoveryTimestamp","attr":{"recoveryTimestamp":{"$timestamp":{"t":0,"i":0}}}}
{"t":{"$date":"2021-05-25T23:30:59.550+00:00"},"s":"I",  "c":"STORAGE",  "id":4366408, "ctx":"initandlisten","msg":"No table logging settings modifications are required for existing WiredTiger tables","attr":{"loggingEnabled":false}}
{"t":{"$date":"2021-05-25T23:30:59.551+00:00"},"s":"I",  "c":"STORAGE",  "id":22262,   "ctx":"initandlisten","msg":"Timestamp monitor starting"}
{"t":{"$date":"2021-05-25T23:30:59.554+00:00"},"s":"I",  "c":"STORAGE",  "id":20536,   "ctx":"initandlisten","msg":"Flow Control is enabled on this deployment"}
{"t":{"$date":"2021-05-25T23:30:59.554+00:00"},"s":"W",  "c":"SHARDING", "id":22074,   "ctx":"initandlisten","msg":"Started with --shardsvr, but no shardIdentity document was found on disk. This most likely means this server has not yet been added to a sharded cluster","attr":{"namespace":"admin.system.version"}}
{"t":{"$date":"2021-05-25T23:30:59.556+00:00"},"s":"I",  "c":"FTDC",     "id":20625,   "ctx":"initandlisten","msg":"Initializing full-time diagnostic data capture","attr":{"dataDirectory":"/bitnami/mongodb/data/db/diagnostic.data"}}
{"t":{"$date":"2021-05-25T23:30:59.559+00:00"},"s":"I",  "c":"REPL",     "id":21311,   "ctx":"initandlisten","msg":"Did not find local initialized voted for document at startup"}
{"t":{"$date":"2021-05-25T23:30:59.560+00:00"},"s":"I",  "c":"REPL",     "id":21529,   "ctx":"initandlisten","msg":"Initializing rollback ID","attr":{"rbid":1}}
{"t":{"$date":"2021-05-25T23:30:59.560+00:00"},"s":"I",  "c":"REPL",     "id":21313,   "ctx":"initandlisten","msg":"Did not find local replica set configuration document at startup","attr":{"error":{"code":47,"codeName":"NoMatchingDocument","errmsg":"Did not find replica set configuration document in local.system.replset"}}}
{"t":{"$date":"2021-05-25T23:30:59.561+00:00"},"s":"I",  "c":"CONTROL",  "id":20714,   "ctx":"LogicalSessionCacheRefresh","msg":"Failed to refresh session cache, will try again at the next refresh interval","attr":{"error":"ShardingStateNotInitialized: sharding state is not yet initialized"}}
{"t":{"$date":"2021-05-25T23:30:59.561+00:00"},"s":"I",  "c":"CONTROL",  "id":20712,   "ctx":"LogicalSessionCacheReap","msg":"Sessions collection is not set up; waiting until next sessions reap interval","attr":{"error":"ShardingStateNotInitialized: sharding state is not yet initialized"}}
{"t":{"$date":"2021-05-25T23:30:59.561+00:00"},"s":"I",  "c":"REPL",     "id":40440,   "ctx":"initandlisten","msg":"Starting the TopologyVersionObserver"}
{"t":{"$date":"2021-05-25T23:30:59.561+00:00"},"s":"I",  "c":"REPL",     "id":40445,   "ctx":"TopologyVersionObserver","msg":"Started TopologyVersionObserver"}
{"t":{"$date":"2021-05-25T23:30:59.562+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"/opt/bitnami/mongodb/tmp/mongodb-27017.sock"}}
{"t":{"$date":"2021-05-25T23:30:59.562+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"0.0.0.0"}}
{"t":{"$date":"2021-05-25T23:30:59.562+00:00"},"s":"I",  "c":"NETWORK",  "id":23016,   "ctx":"listener","msg":"Waiting for connections","attr":{"port":27017,"ssl":"on"}}
{"t":{"$date":"2021-05-25T23:31:59.553+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1621985519:553334][1:0x7f3d2baa4700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 3, snapshot max: 3 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0)"}}
{"t":{"$date":"2021-05-25T23:32:58.911+00:00"},"s":"I",  "c":"CONNPOOL", "id":22572,   "ctx":"CurlConnPool-3","msg":"Dropping all pooled connections","attr":{"hostAndPort":"r3.o.lencr.org:80","error":"ShutdownInProgress: Pool for r3.o.lencr.org:80 has expired."}}
```
