### ISSUE TITLE
Replication problem in separated servers!

### ISSUE THREAD

**Issue by emonorg** [bitnami/bitnami-docker-mongodb#267]
**Description**

I have tried to up the dokcer-compose as below on a server and everything worked fine:
```YML
version: '2'

services:
  mongodb-primary:
    container_name: mongo_primary
    image: docker.io/bitnami/mongodb:4.4
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - './data_pri:/bitnami/mongodb'

  mongodb-secondary:
    container_name: mongo_secondary
    image: docker.io/bitnami/mongodb:4.4
    restart: always
    ports:
      - "27018:27017"
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - "./data_sec:/bitnami/mongodb"

  mongodb-arbiter:
    container_name: mongo_arbitary
    image: docker.io/bitnami/mongodb:4.4
    restart: always
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - "./data_arb:/bitnami/mongodb"
```
Then, I decided to separate the nodes in different servers, in a way that the primary node runs on `server1`, secondary and arbiter on `server 2`. So the composes are:

**Sever 1**
```YML
version: '2'

services:
  mongodb-primary:
    container_name: mongo_primary
    image: docker.io/bitnami/mongodb:4.4
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - './data_pri:/bitnami/mongodb'
```

**Server 2**
```YML
version: '2'

services:
  mongodb-secondary:
    container_name: mongo_secondary
    image: docker.io/bitnami/mongodb:4.4
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=<Server 1's IPv4>
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - "./data_sec:/bitnami/mongodb"

  mongodb-arbiter:
    container_name: mongo_arbitary
    image: docker.io/bitnami/mongodb:4.4
    restart: always
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=<Server 1's IPv4>
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - "./data_arb:/bitnami/mongodb"
```
**Describe the results you received:**

Secondary log:
```
mongodb 09:14:26.32 INFO  ==> ** Starting MongoDB setup **
mongodb 09:14:26.35 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 09:14:26.38 INFO  ==> Initializing MongoDB...
mongodb 09:14:26.41 INFO  ==> Deploying MongoDB from scratch...
mongodb 09:14:28.93 INFO  ==> Creating users...
mongodb 09:14:28.94 INFO  ==> Users created
mongodb 09:14:28.94 INFO  ==> Writing keyfile for replica set authentication...
mongodb 09:14:28.98 INFO  ==> Configuring MongoDB replica set...
mongodb 09:14:28.99 INFO  ==> Stopping MongoDB...
mongodb 09:14:31.96 INFO  ==> Trying to connect to MongoDB server 5.253.24.151...
mongodb 09:14:32.05 INFO  ==> Found MongoDB server listening at 5.253.24.151:27017 !
mongodb 09:14:32.30 INFO  ==> MongoDB server listening and working at 5.253.24.151:27017 !
mongodb 09:14:32.58 INFO  ==> Primary node ready.
mongodb 09:14:32.78 INFO  ==> Adding node to the cluster
mongodb 09:17:50.36 ERROR ==> Secondary node did not get ready
mongodb 09:17:50.37 INFO  ==> Stopping MongoDB...
mongodb 09:17:52.97
mongodb 09:17:52.97 Welcome to the Bitnami mongodb container
mongodb 09:17:52.97 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 09:17:52.97 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 09:17:52.98
mongodb 09:17:52.98 INFO  ==> ** Starting MongoDB setup **
mongodb 09:17:53.01 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 09:17:53.04 INFO  ==> Initializing MongoDB...
mongodb 09:17:53.11 INFO  ==> Deploying MongoDB with persisted data...
mongodb 09:17:53.11 INFO  ==> Writing keyfile for replica set authentication...

mongodb 09:17:53.17 INFO  ==> ** MongoDB setup finished! **
mongodb 09:17:53.21 INFO  ==> ** Starting MongoDB **
```
and arbiter:

```
mongodb 09:14:25.92 INFO  ==> ** Starting MongoDB setup **
mongodb 09:14:25.96 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 09:14:26.01 INFO  ==> Initializing MongoDB...
mongodb 09:14:26.12 INFO  ==> Deploying MongoDB from scratch...
mongodb 09:14:28.93 INFO  ==> Creating users...
mongodb 09:14:28.94 INFO  ==> Users created
mongodb 09:14:28.94 INFO  ==> Writing keyfile for replica set authentication...
mongodb 09:14:29.00 INFO  ==> Configuring MongoDB replica set...
mongodb 09:14:29.01 INFO  ==> Stopping MongoDB...
mongodb 09:14:32.02 INFO  ==> Trying to connect to MongoDB server 5.253.24.151...
mongodb 09:14:32.05 INFO  ==> Found MongoDB server listening at 5.253.24.151:27017 !
mongodb 09:14:32.31 INFO  ==> MongoDB server listening and working at 5.253.24.151:27017 !
mongodb 09:14:32.54 INFO  ==> Primary node ready.
mongodb 09:14:32.75 INFO  ==> Configuring MongoDB arbiter node
mongodb 09:17:57.24 ERROR ==> Arbiter node did not get ready
mongodb 09:17:57.25 INFO  ==> Stopping MongoDB...
mongodb 09:17:59.65
mongodb 09:17:59.65 Welcome to the Bitnami mongodb container
mongodb 09:17:59.65 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 09:17:59.66 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 09:17:59.66
mongodb 09:17:59.66 INFO  ==> ** Starting MongoDB setup **
mongodb 09:17:59.68 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 09:17:59.71 INFO  ==> Initializing MongoDB...
mongodb 09:17:59.74 INFO  ==> Deploying MongoDB with persisted data...
mongodb 09:17:59.75 INFO  ==> Writing keyfile for replica set authentication...
mongodb 09:17:59.79 INFO  ==> ** MongoDB setup finished! **

mongodb 09:17:59.82 INFO  ==> ** Starting MongoDB **
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:28 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-73-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.844GiB
 Name: mongo-secondary
 ID: 5JDP:PK36:JRFL:3ZWD:KIRB:TUIJ:PZJQ:GQY5:3YM2:FJA2:NM57:UKMM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
UBUNTU 20

Can anyone help me with this?
Regards
