### ISSUE TITLE
Collection not found after docker-compose down - up

### ISSUE THREAD

**Issue by AstaDK** [bitnami/bitnami-docker-mongodb#269]
```yml
version: "3.7"

services:
  node:
    container_name: demo-server
    build:
      context: .
      dockerfile: ./dockers/Dockerfile
    ports:
      - 3200:3000
    volumes:
      - .:/app
    command: yarn start
    networks:
      - common
    env_file:
      - .env
    links:
      - mongo

  mongo:
    container_name: demo-mongo
    image: bitnami/mongodb:4.4
    restart: always
    env_file:
      - .env
    environment:
      - MONGODB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_USERNAME=${MONGODB_ROOT_PASSWORD}
      - MONGODB_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/bitnami/mongodb
    networks:
      - common

  mongo-express:
    container_name: demo-mongo-express
    image: mongo-express
    restart: always
    env_file:
      - .env
    environment:
      - ME_CONFIG_MONGODB_SERVER=video-hosting-mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=${MONGODB_DATABASE}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGODB_PASSWORD}
    depends_on:
      - mongo
    ports:
      - 8081:8081
    networks:
      - common

networks:
  common:
  
volumes:
  mongo:
    name: demo
```

This is my config about mongo-express vs Bitnami MongoDB.
I facing the issue after I act with DB in order to create a user, video ... it means I have records in my DB but **after I down and up again I can not find collect that according to the document will mount**
The image below after I down and up docker-compose and click user collection:
![Screen Shot 2021-06-27 at 10 21 41](https://user-images.githubusercontent.com/80238484/123531776-9bab5b80-d731-11eb-9b4a-468a62931648.png)
