### ISSUE TITLE
Issue: Please add retryWrites=false to your connection string.

### ISSUE THREAD

**Issue by AstaDK** [bitnami/bitnami-docker-mongodb#272]
I'm facing with an error below when starting with docker-compose:

> "MongoError: This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string."

My configuration docker-compose:
```yml
mongo:
    container_name: video-hosting-mongo
    image: docker.io/bitnami/mongodb:4.2
    restart: always
    env_file:
      - .env
    environment:
      - MONGODB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_USERNAME=${MONGODB_ROOT_PASSWORD}
      - MONGODB_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-persistence:/bitnami/mongodb
    networks:
      - common
```
My connecting db:
```js 
// TODO: Should change to environment instead of process.env
const connectionString = `mongodb://${process.env.MONGODB_ROOT_USERNAME}:${process.env.MONGODB_ROOT_PASSWORD}@mongo:27017/name-db?retryWrites=false`;

const startDB = async () => {
    try {
        await mongoose.connect(connectionString, {
            useUnifiedTopology: true,
            useNewUrlParser: true,
            connectTimeoutMS: 1000,
            retryWrites: false,
        });

        logger.info("MongoDB Connected...");
    } catch (error) {
        logger.error("MongoDB Connection error", error);
        throw errorCode.MONGO_CONNECTION_ERROR;
    }
};
```

**Comment by AstaDK** [comment]
I research and aware that I'm using standalone server and I try to add **replSet**
> command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "27017"]

But Having the issue: 
```
/opt/bitnami/scripts/mongodb/entrypoint.sh: line 26: exec: --: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
```

_**So how can I set replSet?**_

**Comment by miguelaeh** [comment]
Hi @AstaDK ,
Check the env vars where to configure it with replicaset: https://github.com/bitnami/bitnami-docker-mongodb#setting-up-replication

**Comment by AstaDK** [comment]
Hi @miguelaeh Following document and config with docker my docker compose 
```yml
  mongo:
    container_name: video-hosting-mongo
    image: docker.io/bitnami/mongodb:4.2
    restart: always
    env_file:
      - .env
    environment:
      - MONGODB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_USERNAME=${MONGODB_ROOT_PASSWORD}
      - MONGODB_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-persistence:/bitnami/mongodb
    networks:
      - common

  mongodb-secondary:
    image: docker.io/bitnami/mongodb:4.2
    depends_on:
      - mongo
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
    
  mongodb-arbiter:
    image: docker.io/bitnami/mongodb:4.2
    depends_on:
      - mongo
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
```
Then I can use mongo with Replica?
I facing the error :

```json
{    
      "ok": 0,
        "code": 13435,
        "codeName": "NotPrimaryNoSecondaryOk",
        "name": "MongoError"
}
```
