### ISSUE TITLE
Not connect with compass

### ISSUE THREAD

**Issue by rupamking1** [bitnami/bitnami-docker-mongodb#274]
why not ablt to connect with mongodb compass 
mongodb://user1:pass1@192.168.31.254:27017/db1

**Comment by Mauraza** [comment]
Hi @rupamking1,

Could you add more information about this error?. How you are deploy MongoDB?

**Comment by rupamking1** [comment]
when I put this URL in robomongo it was but in compass show not authorised, 
I already set up username password according to tu your documentation

**Comment by Mauraza** [comment]
Hi @rupamking1,

Did you are running the docker-compose in local? and the robot3T is in local too?
Are you using this docker-compose https://github.com/bitnami/bitnami-docker-mongodb/blob/master/docker-compose.yml?

**Comment by rupamking1** [comment]
Yes, You are right, yml file with username and password, so why it makes problem please tell me?

**Comment by Mauraza** [comment]
Hi @rupamking1,

Did you add the database?
```yaml
version: '2'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=db1
volumes:
  mongodb_data:
```
