### ISSUE TITLE
Cannot connect to replicaset

### ISSUE THREAD

**Issue by cata0309** [bitnami/bitnami-docker-mongodb#282]
**Description**

**Steps to reproduce the issue:**

1. Paste the following code in a docker-compose.yaml file:
```yaml
version: '3.9'
services:
  mongodb_primary:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb_primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=123456789
      - MONGODB_ROOT_USERNAME=root
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=user
      - MONGODB_DATABASE=testing
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb_primary
    ports:
      - 27001:27017
    volumes:
      - 'mongodb_master_data:/bitnami'
  mongodb_secondary:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb_primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb_secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_KEY=123456789
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb_primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_USERNAME=root
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=root
    ports:
      - 27002:27017
  mongodb_arbiter:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb_primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb_arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_REPLICA_SET_KEY=123456789
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb_primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_USERNAME=root
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=root
    ports:
      - 27003:27017
volumes:
  mongodb_master_data:
    driver: local
```
2. Run `docker-compose up --build`
3. Use Mongo Compass to connect to the db and try the following uris: 
- `mongodb://user:user@localhost:27001/testing?replicaSet=replicaset&authSource=admin`
- `mongodb://user:user@localhost:27001/testing?replicaSet=replicaset&authSource=testing`
- `mongodb://root:root@localhost:27001/testing?replicaSet=replicaset&authSource=testing`
- `mongodb://user:user@localhost:27001,localhost:27002,localhost:27003/testing?replicaSet=replicaset&authSource=testing`

**Describe the results you received:**
Cannot connect to the db.
![image](https://user-images.githubusercontent.com/35623921/129541605-2118c69e-a5d4-438b-adfc-c61286303adc.png)

Secondary and arbiter fail
![image](https://user-images.githubusercontent.com/35623921/129541656-e42ebdc6-e43b-45ef-9222-0c736d5b712d.png)

![image](https://user-images.githubusercontent.com/35623921/129541686-c57d671c-e2cb-4949-bda3-6492f059e1d8.png)

**Describe the results you expected:**
Being able to connect to the replicaset and the nodes to not fail

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**
latest as of now(4.4.8)
- Output of `docker version`:
```
Client: Docker Engine - Community
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:47 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)
WARNING: Plugin "/usr/libexec/docker/cli-plugins/docker-app" is not valid: failed to fetch metadata: fork/exec /usr/libexec/docker/cli-plugins/docker-app: no such file or directory

Server:
 Containers: 8
  Running: 2
  Paused: 0
  Stopped: 6
 Images: 23
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 12.18GiB
 Name: docker-desktop
 ID: 2BXZ:32JN:VQ5Y:AOIJ:DFRN:PBRW:M7LF:Y45H:GMG5:T4YA:TPRD:RUFY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
None

**Comment by rafariossaa** [comment]
Hi,
  Not very sure of the issue here. On one hand you seem to have connections issue and in the other you got the primary stopped.
  I used the compose you provided, and started and I got all the containers up and running.
```
 IMAGE                    COMMAND                  CREATED              STATUS              PORTS                      NAMES
1eb712b453c0        bitnami/mongodb:latest   "/opt/bitnami/script…"   About a minute ago   Up About a minute   0.0.0.0:27002->27017/tcp   bitnami-docker-mongodb_mongodb_secondary_1
625c902c16f0        bitnami/mongodb:latest   "/opt/bitnami/script…"   About a minute ago   Up About a minute   0.0.0.0:27003->27017/tcp   bitnami-docker-mongodb_mongodb_arbiter_1
13c02aec0ef1        bitnami/mongodb:latest   "/opt/bitnami/script…"   About a minute ago   Up About a minute   0.0.0.0:27001->27017/tcp   bitnami-docker-mongodb_mongodb_primary_1

```

and the log were normal:
```
...
mongodb_primary_1    | {"t":{"$date":"2021-08-17T07:12:23.275+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1629184343:275733][1:0x7f169e8d7700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 31, snapshot max: 31 snapshot count: 0, oldest timestamp: (1629184328, 1) , meta checkpoint timestamp: (1629184333, 1) base write gen: 24"}}
mongodb_arbiter_1    | {"t":{"$date":"2021-08-17T07:12:31.452+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1629184351:452513][1:0x7f1be7b9e700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 22, snapshot max: 22 snapshot count: 0, oldest timestamp: (1629184338, 1) , meta checkpoint timestamp: (1629184343, 1) base write gen: 14"}}
mongodb_secondary_1  | {"t":{"$date":"2021-08-17T07:12:31.683+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1629184351:683953][1:0x7f80212c4700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 40, snapshot max: 40 snapshot count: 0, oldest timestamp: (1629184338, 1) , meta checkpoint timestamp: (1629184343, 1) base write gen: 25"}}
^Tmongodb_primary_1    | {"t":{"$date":"2021-08-17T07:13:23.296+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1629184403:296940][1:0x7f169e8d7700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 45, snapshot max: 45 snapshot count: 0, oldest timestamp: (1629184388, 1) , meta checkpoint timestamp: (1629184393, 1) base write gen: 24"}}
mongodb_arbiter_1    | {"t":{"$date":"2021-08-17T07:13:31.465+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1629184411:465908][1:0x7f1be7b9e700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 24, snapshot max: 24 snapshot count: 0, oldest timestamp: (1629184398, 1) , meta checkpoint timestamp: (1629184403, 1) base write gen: 14"}}
mongodb_secondary_1  | {"t":{"$date":"2021-08-17T07:13:31.709+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1629184411:709104][1:0x7f80212c4700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 72, snapshot max: 72 snapshot count: 0, oldest timestamp: (1629184398, 1) , meta checkpoint timestamp: (1629184403, 1) base write gen: 25"}}
mongodb_primary_1    | {"t":{"$date":"2021-08-17T07:14:23.312+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1629184463:312131][1:0x7f169e8d7700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 59, snapshot max: 59 snapshot count: 0, oldest timestamp: (1629184448, 1) , meta checkpoint timestamp: (1629184453, 1) base write gen: 24"}}
mongodb_arbiter_1    | {"t":{"$date":"2021-08-17T07:14:31.475+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1629184471:475625][1:0x7f1be7b9e700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 25, snapshot max: 25 snapshot count: 0, oldest timestamp: (1629184458, 1) , meta checkpoint timestamp: (1629184463, 1) base write gen: 14"}}
mongodb_secondary_1  | {"t":{"$date":"2021-08-17T07:14:31.727+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1629184471:727770][1:0x7f80212c4700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 104, snapshot max: 104 snapshot count: 0, oldest timestamp: (1629184458, 1) , meta checkpoint timestamp: (1629184463, 1) base write gen: 25"}}
```

**Comment by cata0309** [comment]
Did you manage to connect to the replicaset?

**Comment by cata0309** [comment]
They are up and running in my case too but when trying to connect arbiter and secondary fail

**Comment by cata0309** [comment]
Do you happen to have a docker-compose with an authenticated replicaset?

**Comment by rafariossaa** [comment]
I could not connect using the urls you provided, however I can connect with:
```bash
$ docker run -it --network temp_default bitnami/mongodb -- bash

I have no name!@d46bd30129ae:/$ mongo -u root -p root --host temp_mongodb_primary_1 --port 27017 
MongoDB shell version v4.4.8
connecting to: mongodb://temp_mongodb_primary_1:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("b7be132f-ae7f-4256-b64b-a361da61701b") }
MongoDB server version: 4.4.8

...

---
replicaset:PRIMARY> 
```

the `temp_default` network is the one that the docker-compose file you provided created when started.

**Comment by diavrank** [comment]
I have the same problem. I am using Mongo Booster and I can connect only to a single node at a time, but when I try to connect to the 3 nodes at the same time I got this error:

<img width="637" alt="Screen Shot 2021-08-18 at 23 42 15" src="https://user-images.githubusercontent.com/39581375/130009116-f4c2dae8-67cc-4140-a2f5-611902993cd1.png">


I added my nodes as follows:

<img width="578" alt="Screen Shot 2021-08-18 at 23 45 05" src="https://user-images.githubusercontent.com/39581375/130009498-c19457f9-c9be-4a84-9177-dd64efb4c241.png">

I also tried to click on "Discovery Members" button, but I got this:

![image](https://user-images.githubusercontent.com/39581375/130009627-caeb53e0-730a-439e-a4d7-59f1fb9e13c9.png)

They are the names defined in my **docker-compose.yml**. It seems they are names from **MONGODB_ADVERTISED_HOSTNAME** environment variable of each service. I tried to rename the values for that env variable to mydomain.com but it didn't work. 

On the other hand, I can access to them but only one at a time:

Primary node:

<img width="385" alt="Screen Shot 2021-08-18 at 23 54 25" src="https://user-images.githubusercontent.com/39581375/130010797-5b185744-861e-4d04-965a-7f22272338fd.png">

Secondary node:

<img width="537" alt="Screen Shot 2021-08-18 at 23 58 57" src="https://user-images.githubusercontent.com/39581375/130010824-4ab2a3e7-f0b2-4667-a453-2d779a27a41e.png">

Arbiter node:

<img width="389" alt="Screen Shot 2021-08-19 at 0 03 20" src="https://user-images.githubusercontent.com/39581375/130010844-87b3bda3-d153-44ba-bdc7-6fa86694ee0b.png">

It is worth mentioning that when I tried to connect from my nodejs app (which is another container in the same docker network), it works as follows:

```
mongodb://user:pwd@mongo-primary:27017,mongo-secondary:27017,mongo-arbiter:27017/db?authSource=db&replicaSet=rs0
```

So, I don't know why it isn't possible from a Mongo Client like Mongo Booster, Robo 3T or Mongo Compass.

**Comment by rafariossaa** [comment]
Hi,
  I used [this](https://github.com/bitnami/bitnami-docker-mongodb/blob/master/docker-compose-replicaset.yml) compose, and then started a client container by running:
```
$ docker run -it --network bitnami-docker-mongodb_default bitnami/mongodb -- bash
```
I could connect to the replica set with:
```
I have no name!@35d06ec3b3d6:/$ mongo "mongodb://root:password123@mongodb-primary:27017,mongo-secondary:27017,mongo-arbiter:27017/?replicaSet=replicaset"      
MongoDB shell version v4.4.8
connecting to: mongodb://mongodb-primary:27017,mongo-secondary:27017,mongo-arbiter:27017/?compressors=disabled&gssapiServiceName=mongodb&replicaSet=replicaset
Implicit session: session { "id" : UUID("1b31d524-a2e6-49d0-9fb2-d7c933b63d8d") }
MongoDB server version: 4.4.8
---
The server generated these startup warnings when booting: 
        2021-08-19T07:48:09.308+00:00: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem
        2021-08-19T07:48:11.169+00:00: 
        2021-08-19T07:48:11.169+00:00: ** WARNING: This replica set has a Primary-Secondary-Arbiter architecture, but readConcern:majority is enabled 
        2021-08-19T07:48:11.169+00:00: **          for this node. This is not a recommended configuration. Please see 
        2021-08-19T07:48:11.169+00:00: **          https://dochub.mongodb.org/core/psa-disable-rc-majority
        2021-08-19T07:48:11.169+00:00: 
---
---
        Enable MongoDB's free cloud-based monitoring service, which will then receive and display
        metrics about your deployment (disk utilization, CPU, operation statistics, etc).

        The monitoring data will be available on a MongoDB website with a unique URL accessible to you
        and anyone you share the URL with. MongoDB may use this information to make product
        improvements and to suggest MongoDB products and deployment options to you.

        To enable free monitoring, run the following command: db.enableFreeMonitoring()
        To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
---
replicaset:PRIMARY> 
```

**Comment by diavrank** [comment]
@rafariossaa the problem is to connect to the replica set from a **mongo client with GUI** (like Mongo Compass, Mongo Booster, Robo 3t).

**Comment by rafariossaa** [comment]
Hi,
  I tried with Mongo Booster and the following docker-compose, and got this error: `getaddrinfo ENOTFOUND mongodb-arbiter`.
```
$ cat docker-compose-replicaset.yml 
version: '2'

services:
  mongodb-primary:
    image: docker.io/bitnami/mongodb:4.4
    ports:
      - '27017:27017' 
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'

  mongodb-secondary:
    image: docker.io/bitnami/mongodb:4.4
    ports:
      - '27018:27017' 
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: docker.io/bitnami/mongodb:4.4
    ports:
      - '27019:27017' 
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  mongodb_master_data:
    driver: local
```

  The issue here is that where the client is launched it is not able to resolve the containers names. So I added this to my `/etc/host`file:
```
127.0.0.1  mongodb-primary mongodb-secondary mongodb-arbiter
```
  Now I am able to connect :
![image](https://user-images.githubusercontent.com/11049367/130435237-f34968a3-aa54-48c6-90dd-c50984409b15.png)

  This is the connection defintion:
![image](https://user-images.githubusercontent.com/11049367/130435345-a6b470e9-d527-41e4-a10b-7f684fde8651.png)
  Also, I set the user and password in the authentication tab.

  Could you try that ?

**Comment by diavrank** [comment]
> I tried with Mongo Booster and the following docker-compose, and got this error: `getaddrinfo ENOTFOUND mongodb-arbiter`

I get that error too. 

I have just modified my **hosts** file as follow:

```
<my_public_ip_address_of_VM>	mongodb-primary mongodb-secondary mongodb-arbiter
```
But I got this error:

![image](https://user-images.githubusercontent.com/39581375/130704381-7df256ca-dfc3-4105-958b-4dc126e27e8f.png)

I don't know why **mongodb-arbiter** is listening on **27017**, since I configured in `docker-compose.yml` the **29017** port.

This is my docker-compose file:

```yaml
version: '3'

services:
  mongo-primary:
    container_name: mongo-primary
    image: bitnami/mongodb:4.4.7
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_ROOT_PASSWORD=anypassword
      - MONGODB_REPLICA_SET_KEY=anyreplicasetkey
      - MONGODB_USERNAME=custom
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=dbexample
    volumes:
      - $PWD/data:/bitnami
      - $PWD/database:/opt/database
    networks:
      - rematch-net
  mongo-secondary:
    container_name: mongo-secondary
    image: bitnami/mongodb:4.4.7
    restart: always
    ports:
      - 28017:27017
    depends_on:
      - mongo-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_INITIAL_PRIMARY_HOST=mongo-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=anypassword
      - MONGODB_REPLICA_SET_KEY=anyreplicasetkey
    networks:
      - rematch-net
  mongo-arbiter:
      container_name: mongo-arbiter
      image: bitnami/mongodb:4.4.7
      restart: always
      ports:
        - 29017:27017
      depends_on:
        - mongo-primary
      environment:
        - MONGODB_ADVERTISED_HOSTNAME=mongo-arbiter
        - MONGODB_REPLICA_SET_MODE=arbiter
        - MONGODB_REPLICA_SET_NAME=rs0
        - MONGODB_INITIAL_PRIMARY_HOST=mongo-primary
        - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
        - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=anypassword
        - MONGODB_REPLICA_SET_KEY=anyreplicasetkey
      networks:
        - rematch-net
networks:
  rematch-net:

```

_in this compose file, I skipped other services which are not related to this issue of database connection (app, SSL proxy, etc)_

docker ps command show this:

```shell
CONTAINER ID   IMAGE                      COMMAND                  CREATED        STATUS        PORTS                                           NAMES
e8d4d7b9babb   justsml/ssl-proxy:latest   "/bin/sh -c /www/ent…"   45 hours ago   Up 45 hours   80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   ssl-proxy
c4b9b9923623   crontab                    "cron -f"                45 hours ago   Up 45 hours                                                   crontab
167a5b0d17ea   rematch-api-player         "/docker/entrypoint.…"   45 hours ago   Up 45 hours   0.0.0.0:80->3000/tcp, :::80->3000/tcp           app
bb58f44989e8   bitnami/mongodb:4.4.7      "/opt/bitnami/script…"   45 hours ago   Up 45 hours   0.0.0.0:28017->27017/tcp, :::28017->27017/tcp   mongo-secondary
0f099c20d9b2   bitnami/mongodb:4.4.7      "/opt/bitnami/script…"   45 hours ago   Up 45 hours   0.0.0.0:29017->27017/tcp, :::29017->27017/tcp   mongo-arbiter
4d4b5302f71a   bitnami/mongodb:4.4.7      "/opt/bitnami/script…"   45 hours ago   Up 45 hours   0.0.0.0:27017->27017/tcp, :::27017->27017/tcp   mongo-primary
```

Any configuration is missing?
