### ISSUE TITLE
User creation fails in EKS with persistent volumes

### ISSUE THREAD

**Issue by xifnathan** [bitnami/bitnami-docker-mongodb#288]
**Description**

We are having an issue running the container in EKS with a persistent volume. We are using the credential creation via env vars:
```
MONGODB_USERNAME
MONGODB_PASSWORD
MONGODB_DATABASE
```
and we keep getting an error when it tries to create the user: 

```
{"t":{"$date":"2021-09-02T16:20:38.855+00:00"},"s":"D2", "c":"COMMAND",  "id":21965,   "ctx":"conn2","msg":"About to run the command","attr":{"db":"test","commandArgs":{"createUser":"cobbMongo","pwd":"xxx","roles":[{"role":"readWrite","db":"test"}],"digestPassword":true,"writeConcern":{"w":"majority","wtimeout":600000.0},"lsid":{"id":{"$uuid":"2b468b18-7a03-461d-ab45-59492c0519a1"}},"$db":"test"}}}
{"t":{"$date":"2021-09-02T16:20:38.855+00:00"},"s":"D1", "c":"-",        "id":23074,   "ctx":"conn2","msg":"User assertion","attr":{"error":"Unauthorized: command createUser requires authentication","file":"src/mongo/db/commands.cpp","line":110}}
```

So far we've tried:

1. `chown`ing the mounted volume for UID 1001 in case it was a file permission issue
2.  setting the `MONGODB_ROOT_PASSWORD`  in case it was a root password issue
3.  We've also cleaned the volume several times in case something was amiss 

If we run without the persistent volume and everything works great, but as soon as we try the persistence it fails

Snipped from yaml:

```
      - name: mongo
        image: bitnami/mongodb:latest
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: true
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-config
          mountPath: /opt/bitnami/mongodb/conf/mongodb.conf
          subPath: mongodb.conf
        - name: mongo-data
          mountPath: /bitnami/mongodb/data/db
        - name: mongo-logs
          mountPath: /opt/bitnami/mongodb/logs
        env:
        - name: MONGODB_USERNAME
          value: "xxxxxxx"
        - name: MONGODB_PASSWORD
          value: "xxxxxxx"
        - name: MONGODB_DATABASE
          value: "test"
```
