### ISSUE TITLE
localhost and Replica Sets not able to connect

### ISSUE THREAD

**Issue by jml5qh** [bitnami/bitnami-docker-mongodb#292]
**Description**

I have a Replica Set that I'd like to access via localhost so I don't need to manually set my /etc/hosts file. However, I'm unable to get a permutation of my Docker-Compose file that will work. Ideally, I'd connect to the DB like:

mongo "mongodb://root:password123@localhost:27017,localhost:28017,localhost:29017/?replicaSet=replicaset"

However, I'd take any solution where I don't need to manually set my /etc/hosts file.

**Steps to reproduce the issue:**

Use the following Docker-compose file.

```
version: '3'
      
  mongodb-primary:
    image: docker.io/bitnami/mongodb:4.4
    ports:
      - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'

  mongodb-secondary:
    image: docker.io/bitnami/mongodb:4.4
    depends_on:
      - mongodb-primary
    ports:
      - 28017:28017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_PORT_NUMBER=28017
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: docker.io/bitnami/mongodb:4.4
    depends_on:
      - mongodb-primary
    ports:
      - 29017:29017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_PORT_NUMBER=29017
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      
volumes:
  mongodb_master_data:
    driver: local
```

**Describe the results you received:**

The secondary set is unable to start up and I can't connect to the replicaset

mongodb-secondary_1                | mongodb 07:02:47.45 ERROR ==> Initial data sync did not finish after 35 seconds
mongodb-secondary_1                | mongodb 07:02:47.46 INFO  ==> Stopping MongoDB...

**Describe the results you expected:**

I'd be able to connect to the replicaset with: "mongo "mongodb://root:password123@localhost:27017,localhost:28017,localhost:29017/?replicaSet=replicaset"

**Version**

- Output of `docker version`:

Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

- Output of `docker info`:

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 85
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.941GiB
 Name: docker-desktop
 ID: H5HK:EBHN:N5U7:RLQ5:Z63T:CYHB:SKKO:WWB6:RSLB:OGI7:IX4B:HIZA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

- Output of `docker-compose version` (if applicable):

docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Docker for Mac
