### ISSUE TITLE
Read-only file system Issue on K8S cluster

### ISSUE THREAD

**Issue by digantamukherjee** [bitnami/bitnami-docker-mongodb#293]
**Description**

I am trying to deploy the mongodb image on my kubernetes cluster to run the chaos test litmus tool. However I am getting this error which I am unable to resolve. Any pointers to resolve this would be much appreciated. I could not find this exact scenario by searching across the issues.

**Steps to reproduce the issue:**

1. Build the mongodb image(version 4.2)
2. Deploy on K8S cluster. I am using below script
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: litmus
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      component: database
  serviceName: mongo
  replicas: 1
  template:
    metadata:
      labels:
        component: database
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: mongo
          securityContext:
            runAsUser: 1001
            runAsGroup: 3000
          image: mongo_bt:42
          ports:
            - containerPort: 27017
          imagePullPolicy: Always
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-admin-config
                  key: DB_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-admin-config
                  key: DB_PASSWORD
      imagePullSecrets:
      - name: local-creds
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: mongo-sc
```
3. Wait for mongo-0 sts container to bootup

**Describe the results you received:**

Below is the error I get:
mongodb 19:45:22.05
mongodb 19:45:22.05 Welcome to the Bitnami mongodb container
mongodb 19:45:22.05 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 19:45:22.06 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 19:45:22.06
mongodb 19:45:22.06 INFO  ==> ** Starting MongoDB setup **
mongodb 19:45:22.09 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 19:45:22.12 INFO  ==> Initializing MongoDB...
mongodb 19:45:22.13 INFO  ==> Deploying MongoDB from scratch...
mkdir: cannot create directory '/opt/bitnami/mongodb/bitnami/mongodb/data/db': Read-only file system

**Describe the results you expected:**

The image should bootup and provide a usable instance of mongodb

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens every time

**Version**

- Output of `docker version`:

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 34
  Running: 0
  Paused: 0
  Stopped: 34
 Images: 49
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 5.805GiB
 Name: docker-desktop
 ID: 5G73:XFUI:SW4L:RAJ4:7CPQ:ZQAR:QB3A:NQPW:OTLR:CD6E:7FWZ:U72B
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Using Docker for MAC
