### ISSUE TITLE
Unable to override config as instructed by the README

### ISSUE THREAD

**Issue by mhyousefi** [bitnami/bitnami-docker-mongodb#304]
Hi there,

First of all, thank you for building and maintaining useful docker images and helm charts.

I have been experimenting with the `bitnami/mongodb` image, wondering how I can override the default configuration. Now with `bitnami/mysql`, for instance, the main configuration file `include`s, at its last line, another config file from some directory, allowing the user to present its custom config to override the default one. 

This is not the case with `bitnami/mongodb`, but the docs [here](https://github.com/bitnami/bitnami-docker-mongodb#configuration-file) provide steps to achieve the same purpose. I was unable, however, to successfully follow these steps and appreciate if you could assist me on this.

I have the following `docker-compose.yml`:
```yaml
version: '2'

services:
  mongodb:
    image: bitnami/mongodb:5.0
    environment:
      - MONGODB_ROOT_PASSWORD=secret
      - MONGODB_SYSTEM_LOG_VERBOSITY=3
    ports:
      - "27017:27017"
    volumes:
      - "/path/to/local/dir:/bitnami/mongodb"

volumes:
  mongodb_data:
    driver: local
```

Before running `docker-compose up -d`, I make sure there is a file at `/path/to/local/dir/conf/mongodb.conf` containing the following. I have taken the bellow config from the default one the image ends up creating, and have only added the line `connPoolMaxConnsPerHost: 246` to ultimately tell if the it is overriding MongoDB config.
```yaml
storage:
  dbPath: /bitnami/mongodb/data/db
  journal:
    enabled: true
  directoryPerDB: false
systemLog:
  destination: file
  quiet: false
  logAppend: true
  logRotate: reopen
  path: /opt/bitnami/mongodb/logs/mongodb.log
  verbosity: 5
net:
  port: 27017
  unixDomainSocket:
    enabled: true
    pathPrefix: /opt/bitnami/mongodb/tmp
  ipv6: false
  bindIpAll: true
processManagement:
   fork: false
   pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
setParameter:
   enableLocalhostAuthBypass: false
   connPoolMaxConnsPerHost: 246
security:
  authorization: enabled
  keyFile: /opt/bitnami/mongodb/conf/keyfile
```

The database seems to startup just fine. Not only does the file `/opt/bitnami/mongodb/conf/mongodb.conf` remain the same as before, but also the targeted parameter is not changed to `246`.
```bash
> db.adminCommand( { getParameter : 1, "connPoolMaxConnsPerHost" : 1 } )
{ "connPoolMaxConnsPerHost" : 200, "ok" : 1 }
```

I then tried to mount my file at `/opt/bitnami/mongodb/conf/mongodb.conf`, which results in the container crashing immediately after startup silently (even with `MONGODB_SYSTEM_LOG_VERBOSITY=5`). I assume that's because I'm tinkering with the bitnami internal process, which is not what I want in the first place.

**Comment by mhyousefi** [comment]
My main purpose is to be able to customize mongodb config in a reliable way. Any tips on making the above method work or suggestions on other methods would be appreciated.

**Comment by migruiz4** [comment]
Hi @mhyousefi,

It appears to be an issue, either with the documentation or the value for "MONGODB_MOUNTED_CONF_DIR" being set to `/bitnami/conf` and not `/bitnami/mongodb/conf` as the README suggests.

As a workaround, you could try the following:
```
version: '2'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    environment:
      - MONGODB_ROOT_PASSWORD=secret
      - MONGODB_SYSTEM_LOG_VERBOSITY=3
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb/data'
      - /path/to/mongodb-configuration-persistence:/bitnami/conf
volumes:
  mongodb_data:
    driver: local
```
I tried it myself and should work:
```
> db.adminCommand( { getParameter : 1, "connPoolMaxConnsPerHost" : 1 } )

{ "connPoolMaxConnsPerHost" : 246, "ok" : 1 }
```

But please be aware that we may change the current paths with a non-backward compatible image to match what the README says and be in line with other images in our catalog.

When the change is performed, we will add a note in the section **Notable changes** of the README.
