### ISSUE TITLE
PVC ignored, always use Pod internal storage

### ISSUE THREAD

**Issue by ognif** [bitnami/bitnami-docker-mongodb#305]
**PVC ignored, always use volume on pod**

The deployemnt of bitnami mongodb has teh instruction to use a PVC in our longhorn storage class.
The deployment works without error. The log file show wrong data path. 

**Steps to reproduce the issue:**

install the Chart with:
````
mongodb:
  enabled: true
  global:
    storageClass: longhorn
  auth:
    enabled: false
  architecture: replicaset
  useStatefulSet: true
  arbiter:
    enabled: false
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: longhorn
    mountPath: /opt/mongodb/data
    size: 512Mi
  service:
    port: 27017
````

**Describe the results you received:**

The mongo DB is created with an internal data inside the Pod, not with the aquried PVC in longhorn. 

**Describe the results you expected:**

Persitent volume usaeg. StoreClass "longhorn" not "whitetiger".

**Additional information you deem important (e.g. issue happens only occasionally):**
Chart:
````
mongodb:
  enabled: true
  global:
    storageClass: longhorn
  auth:
    enabled: false
  architecture: replicaset
  useStatefulSet: true
  arbiter:
    enabled: false
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: longhorn
    mountPath: /opt/mongodb/data
    size: 512Mi
  service:
    port: 27017
````
Log file:
mongodb 11:21:03.00 INFO  ==> ** Starting MongoDB **

{"t":{"$date":"2021-11-30T11:21:03.027+00:00"},"s":"I",  "c":"CONTROL",  "id":20698,   "ctx":"main","msg":"***** SERVER RESTARTED *****"}
{"t":{"$date":"2021-11-30T11:21:03.029+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
{"t":{"$date":"2021-11-30T11:21:03.031+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
{"t":{"$date":"2021-11-30T11:21:03.031+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
{"t":{"$date":"2021-11-30T11:21:03.031+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
{"t":{"$date":"2021-11-30T11:21:03.032+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/bitnami/mongodb/data/db","architecture":"64-bit","host":"adt-development-mongodb-0"}}
{"t":{"$date":"2021-11-30T11:21:03.032+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.9","gitVersion":"b4048e19814bfebac717cf5a880076aa69aba481","openSSLVersion":"OpenSSL 1.1.1d  10 Sep 2019","modules":[],"allocator":"tcmalloc","environment":{"distmod":"debian10","distarch":"x86_64","target_arch":"x86_64"}}}}
{"t":{"$date":"2021-11-30T11:21:03.032+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"PRETTY_NAME=\"Debian GNU/Linux 10 (buster)\"","version":"Kernel 4.19.0-10-amd64"}}}
{"t":{"$date":"2021-11-30T11:21:03.032+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"config":"/opt/bitnami/mongodb/conf/mongodb.conf","net":{"bindIp":"*","ipv6":false,"port":27017,"unixDomainSocket":{"enabled":true,"pathPrefix":"/opt/bitnami/mongodb/tmp"}},"processManagement":{"fork":false,"pidFilePath":"/opt/bitnami/mongodb/tmp/mongodb.pid"},"replication":{"enableMajorityReadConcern":true,"replSetName":"rs0"},"security":{"authorization":"disabled"},"setParameter":{"enableLocalhostAuthBypass":"true"},"storage":{"dbPath":"/bitnami/mongodb/data/db","directoryPerDB":false,"journal":{"enabled":true}},"systemLog":{"destination":"file","logAppend":true,"logRotate":"reopen","path":"/opt/bitnami/mongodb/logs/mongodb.log","quiet":false,"verbosity":0}}}}
{"t":{"$date":"2021-11-30T11:21:03.033+00:00"},"s":"I",  "c":"STORAGE",  "id":22270,   "ctx":"initandlisten","msg":"Storage engine to use detected by data files","attr":{"dbpath":"/bitnami/mongodb/data/db","storageEngine":"wiredTiger"}}
````
