### ISSUE TITLE
Unable to create/open the lock file: /bitnami/mongodb/data/db/mongod.lock (Operation not permitted)

### ISSUE THREAD

**Issue by amirjani** [bitnami/bitnami-docker-mongodb#306]
I'm trying to run replicaset on my local machine, but I received this error when I'm logging it 
my docker-compose file looks like this: 
```yaml
version: "3.3"

services:
  mongo-first:
    hostname: mongo-first
    container_name: mongo-first
    image: docker.io/bitnami/mongodb:4.4
    expose:
      - ${MONGO_EXPOSE_PORT}
    ports:
      - ${MONGO_FIRST_LOCAL_PORT}:${MONGO_CONTAINER_PORT}
    restart: always
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_FIRST_ADVERTISED_HOSTNAME}
      - MONGODB_REPLICA_SET_MODE=${MONGODB_FIRST_REPLICA_SET_MODE}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
    volumes:
      - ../data/mongo:/bitnami/mongodb
    networks:
      - rms_network

  mongo-second:
    hostname: mongo-second
    container_name: mongo-second
    image: docker.io/bitnami/mongodb:4.4
    depends_on:
      - mongo-first
    expose:
      - ${MONGO_EXPOSE_PORT}
    ports:
      - ${MONGO_SECOND_LOCAL_PORT}:${MONGO_CONTAINER_PORT}
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_SECOND_ADVERTISED_HOSTNAME}
      - MONGODB_REPLICA_SET_MODE=${MONGODB_SECOND_REPLICA_SET_MODE}
      - MONGODB_INITIAL_PRIMARY_HOST=${MONGODB_INITIAL_PRIMARY_HOST}
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
    networks:
      - rms_network

  mongo-third:
    hostname: mongo-third
    container_name: mongo-third
    image: docker.io/bitnami/mongodb:4.4
    depends_on:
      - mongo-first
    expose:
      - ${MONGO_EXPOSE_PORT}
    ports:
      - ${MONGO_THIRD_LOCAL_PORT}:${MONGO_CONTAINER_PORT}
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_THIRD_REPLICA_SET_MODE}
      - MONGODB_REPLICA_SET_MODE=${MONGODB_THIRD_REPLICA_SET_MODE}
      - MONGODB_INITIAL_PRIMARY_HOST=${MONGODB_INITIAL_PRIMARY_HOST}
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
    networks:
      - rms_network

```
this error is: 
```
{"t":{"$date":"2021-12-02T08:56:32.185+00:00"},"s":"E",  "c":"STORAGE",  "id":20557,   "ctx":"initandlisten","msg":"DBException in initAndListen, terminating","attr":{"error":"DBPathInUse: Unable to create/open the lock file: /bitnami/mongodb/data/db/mongod.lock (Operation not permitted). Ensure the user executing mongod is the owner of the lock file and has the appropriate permissions. Also make sure that another mongod instance is not already running on the /bitnami/mongodb/data/db directory"}}
{"t":{"$date":"2021-12-02T08:56:32.187+00:00"},"s":"I",  "c":"REPL",     "id":4784900, "ctx":"initandlisten","msg":"Stepping down the ReplicationCoordinator for shutdown","attr":{"waitTimeMillis":10000}}
```
but I chown my data file with ```sudo chown -R 1001 ./data/mongo```

**Steps to reproduce the issue:**

1. run docker-compose 

- Output of `docker version`:

```
Client:
 Cloud integration: v1.0.20
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:43:15 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:10 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.1.1)
  scan: Docker Scan (Docker Inc., 0.9.0)

Server:
 Containers: 7
  Running: 6
  Paused: 0
  Stopped: 1
 Images: 10
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 1.942GiB
 Name: docker-desktop
 ID: U3XO:KZDV:WZUD:VSEO:G2H6:GKD4:KGUN:B3L7:DIS6:ZDTB:3XUO:D3C2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
Docker Compose version v2.1.1
```
