### ISSUE TITLE
How to use environment variables create a user with read & write access to the `local` database?

### ISSUE THREAD

**Issue by alvancamp** [bitnami/bitnami-docker-mongodb#315]
Hello,

I'm somewhat new to Mongo, so please forgive this beginner's question.

I am trying to set up a easy-to-use `docker-compose.yaml` file for use in demo deployments of a [Meteor](https://www.meteor.com/) application. A performance-sensitive requirement of Meteor deployments is configuration of the [`MONGO_OPLOG_URL`](https://docs.meteor.com/environment-variables.html#MONGO-OPLOG-URL) environment variable. After playing around with the Bitnami MongoDB image for a couple hours yesterday, I was unable to figure out how to use the `MONGODB_EXTRA_USERNAMES`, `MONGODB_EXTRA_PASSWORDS`, and `MONGODB_EXTRA_DATABASES` environment variables to create a user with access to the `local` database.

Is it possible to use environment variables to create a user with access to the `local` database, or must that be done through a shell?

Thanks,
Alex

**Comment by juan131** [comment]
Hi @alvancamp 

Could you please provide the Docker Compose (or equivalent commands) you're using to launch your MongoDB container? Please include all the environment variables you're customizing.

> Is it possible to use environment variables to create a user with access to the local database, or must that be done through a shell?

Do you you require local access, I mean accessing to MongoDB locally, or access to a database which name is "local"?

**Comment by alvancamp** [comment]
Hi @juan131,

Here's an excerpt of the relevant portion of the Docker Compose file I am using. This is one of several failed permutations I tried:

```yaml
  db:
    hostname: mongo
    image: bitnami/mongodb:4.2.18
    restart: always
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_EXTRA_USERNAMES=meteor;local
      - MONGODB_EXTRA_PASSWORDS=password123;password123
      - MONGODB_EXTRA_DATABASES=meteor;local
    volumes:
      - db-data:/data/db
```

>Do you you require local access, I mean accessing to MongoDB locally, or access to a database which name is "local"?

I require access to the MongoDB default database named `local`, for use with Meteor's `MONGO_OPLOG_URL` environment variable.  Given the above configuration of the bitnami mongodb image, my `MONGO_OPLOG_URL` would look something like this:

```yaml
MONGO_OPLOG_URL: "mongodb://local:password123@db:27017/local"
```
