### ISSUE TITLE
How to connect to the replica network that I raised in docker-compose local?

### ISSUE THREAD

**Issue by IzyI** [bitnami/bitnami-docker-mongodb#321]
I have docer-compose.yml

``` yaml
version: '3.9'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

    # volumes:
    #   - 'mongodb_master_data:/bitnami'

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    ports:
      - "27018:27017"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
```

I can't figure out how to connect to the replica

roboto3t:   
![изображение](https://user-images.githubusercontent.com/16782308/151848899-53a022be-9c1f-42b2-a798-609d16fdca1f.png)

console:  

``` bash
└─■  mongo --host replicaset/127.0.0.1:27018,127.0.0.1:27017 --username root --password=password123 
MongoDB shell version v4.4.11
connecting to: mongodb://127.0.0.1:27018,127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb&replicaSet=replicaset
{"t":{"$date":"2022-01-31T17:25:13.757Z"},"s":"I",  "c":"NETWORK",  "id":4333208, "ctx":"ReplicaSetMonitor-TaskExecutor","msg":"RSM host selection timeout","attr":{"replicaSet":"replicaset","error":"FailedToSatisfyReadPreference: Could not find host matching read preference { mode: \"nearest\" } for set replicaset"}}
Error: connect failed to replica set replicaset/127.0.0.1:27018,127.0.0.1:27017 :
connect@src/mongo/shell/mongo.js:374:17
@(connect):2:6
exception: connect failed
exiting with code 1
``` 

netstat
``` bash
└─■  netstat -antp | grep LISTEN
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:5355            0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:1080          0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:6341          0.0.0.0:*               LISTEN      2374/megasync       
tcp        0      0 127.0.0.1:6342          0.0.0.0:*               LISTEN      2374/megasync       
tcp        0      0 192.168.122.1:53        0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:27018           0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:27017           0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::5355                 :::*                    LISTEN      -                   
tcp6       0      0 ::1:631                 :::*                    LISTEN      -                   
tcp6       0      0 127.0.0.1:6942          :::*                    LISTEN      4865/java           
tcp6       0      0 :::27018                :::*                    LISTEN      -                   
tcp6       0      0 :::27017                :::*                    LISTEN      -                   
tcp6       0      0 127.0.0.1:63342         :::*                    LISTEN      4865/java          
```

But I can connect to each node separately

``` bash
└─■ mongo --host 127.0.0.1:27017 --username root --password=password123 
MongoDB shell version v4.4.11
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("9828e7af-2306-4086-8a85-1abb2a637d5d") }
MongoDB server version: 4.4.12
---
        Enable MongoDB's free cloud-based monitoring service, which will then receive and display
        metrics about your deployment (disk utilization, CPU, operation statistics, etc).

        The monitoring data will be available on a MongoDB website with a unique URL accessible to you
        and anyone you share the URL with. MongoDB may use this information to make product
        improvements and to suggest MongoDB products and deployment options to you.

        To enable free monitoring, run the following command: db.enableFreeMonitoring()
        To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
---
replicaset:PRIMARY> rs.status()
{
	"set" : "replicaset",
	"date" : ISODate("2022-01-31T17:28:39.608Z"),
	"myState" : 1,
	"term" : NumberLong(2),
	"syncSourceHost" : "",
	"syncSourceId" : -1,
	"heartbeatIntervalMillis" : NumberLong(2000),
	"majorityVoteCount" : 2,
	"writeMajorityCount" : 2,
	"votingMembersCount" : 2,
	"writableVotingMembersCount" : 2,
	"optimes" : {
		"lastCommittedOpTime" : {
			"ts" : Timestamp(1643650114, 1),
			"t" : NumberLong(2)
		},
		"lastCommittedWallTime" : ISODate("2022-01-31T17:28:34.293Z"),
		"readConcernMajorityOpTime" : {
			"ts" : Timestamp(1643650114, 1),
			"t" : NumberLong(2)
		},
		"readConcernMajorityWallTime" : ISODate("2022-01-31T17:28:34.293Z"),
		"appliedOpTime" : {
			"ts" : Timestamp(1643650114, 1),
			"t" : NumberLong(2)
		},
		"durableOpTime" : {
			"ts" : Timestamp(1643650114, 1),
			"t" : NumberLong(2)
		},
		"lastAppliedWallTime" : ISODate("2022-01-31T17:28:34.293Z"),
		"lastDurableWallTime" : ISODate("2022-01-31T17:28:34.293Z")
	},
	"lastStableRecoveryTimestamp" : Timestamp(1643650074, 1),
	"electionCandidateMetrics" : {
		"lastElectionReason" : "electionTimeout",
		"lastElectionDate" : ISODate("2022-01-31T17:16:54.279Z"),
		"electionTerm" : NumberLong(2),
		"lastCommittedOpTimeAtElection" : {
			"ts" : Timestamp(0, 0),
			"t" : NumberLong(-1)
		},
		"lastSeenOpTimeAtElection" : {
			"ts" : Timestamp(1643649411, 9),
			"t" : NumberLong(1)
		},
		"numVotesNeeded" : 1,
		"priorityAtElection" : 5,
		"electionTimeoutMillis" : NumberLong(10000),
		"newTermStartDate" : ISODate("2022-01-31T17:16:54.281Z"),
		"wMajorityWriteAvailabilityDate" : ISODate("2022-01-31T17:16:54.384Z")
	},
	"members" : [
		{
			"_id" : 0,
			"name" : "mongodb-primary:27017",
			"health" : 1,
			"state" : 1,
			"stateStr" : "PRIMARY",
			"uptime" : 706,
			"optime" : {
				"ts" : Timestamp(1643650114, 1),
				"t" : NumberLong(2)
			},
			"optimeDate" : ISODate("2022-01-31T17:28:34Z"),
			"lastAppliedWallTime" : ISODate("2022-01-31T17:28:34.293Z"),
			"lastDurableWallTime" : ISODate("2022-01-31T17:28:34.293Z"),
			"syncSourceHost" : "",
			"syncSourceId" : -1,
			"infoMessage" : "",
			"electionTime" : Timestamp(1643649414, 1),
			"electionDate" : ISODate("2022-01-31T17:16:54Z"),
			"configVersion" : 4,
			"configTerm" : 2,
			"self" : true,
			"lastHeartbeatMessage" : ""
		},
		{
			"_id" : 1,
			"name" : "mongodb-secondary:27017",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 701,
			"optime" : {
				"ts" : Timestamp(1643650114, 1),
				"t" : NumberLong(2)
			},
			"optimeDurable" : {
				"ts" : Timestamp(1643650114, 1),
				"t" : NumberLong(2)
			},
			"optimeDate" : ISODate("2022-01-31T17:28:34Z"),
			"optimeDurableDate" : ISODate("2022-01-31T17:28:34Z"),
			"lastAppliedWallTime" : ISODate("2022-01-31T17:28:34.293Z"),
			"lastDurableWallTime" : ISODate("2022-01-31T17:28:34.293Z"),
			"lastHeartbeat" : ISODate("2022-01-31T17:28:39.150Z"),
			"lastHeartbeatRecv" : ISODate("2022-01-31T17:28:39.588Z"),
			"pingMs" : NumberLong(0),
			"lastHeartbeatMessage" : "",
			"syncSourceHost" : "mongodb-primary:27017",
			"syncSourceId" : 0,
			"infoMessage" : "",
			"configVersion" : 4,
			"configTerm" : 2
		}
	],
	"ok" : 1,
	"$clusterTime" : {
		"clusterTime" : Timestamp(1643650114, 1),
		"signature" : {
			"hash" : BinData(0,"reoz/vX7rWncGaWVMCVeUBqY3UA="),
			"keyId" : NumberLong("7059420466334662661")
		}
	},
	"operationTime" : Timestamp(1643650114, 1)
}
```

**Comment by IzyI** [comment]
heeeeeelp))))!!!

**Comment by juan131** [comment]
This is a topic that has been discussed several times, see:

- https://github.com/bitnami/bitnami-docker-mongodb/issues/282
- https://github.com/bitnami/bitnami-docker-mongodb/issues/239
- https://github.com/bitnami/bitnami-docker-mongodb/issues/248

Please check the solutions that were provided in these issues.

**Comment by IzyI** [comment]
Hello. 

I tried writing to /etc/hosts
127.0.0.1 mongo_secondary_test mongo_primary_test mongo_arbiter_test

But it did not give any results. 

**Connected like this :**
_mango --hot replicaset/mongo_primary_test:27037,mongo_secondary_test:27038,mongo_arbiter_test:27039 --username root --password=password123_

**and that's how**
_mango --host replicaset works/127.0.0.1:27037,127.0.0.1:27038,127.0.0.1:27039 -- username root --password=password123_

This did not give results. I even tried to put in /etc/hosts the ip that my router gave me 192.168.50.124

My docker-compose.yml

```yml
version: '3.9'

services:
  mongodb-primary:
    container_name: mongo_primary_test
    image: 'bitnami/mongodb:latest'
    ports:
      - "27037:27017"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    networks:
      - rematch-net
    # volumes:
    #   - 'mongodb_master_data:/bitnami'

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    container_name: mongo_secondary_test
    depends_on:
      - mongodb-primary
    ports:
      - "27038:27017"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    networks:
      - rematch-net
  mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    container_name: mongo_arbiter_test
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - "27039:27017"
    networks:
      - rematch-net
networks:
  rematch-net:

```


Result:
``` bash

┌─iz|fe  (~)
└─■ mongo --host replicaset/127.0.0.1:27037,127.0.0.1:27038,127.0.0.1:27039 --username root --password=password123
MongoDB shell version v4.4.11
connecting to: mongodb://127.0.0.1:27037,127.0.0.1:27038,127.0.0.1:27039/?compressors=disabled&gssapiServiceName=mongodb&replicaSet=replicaset
{"t":{"$date":"2022-02-02T22:52:19.795Z"},"s":"I",  "c":"NETWORK",  "id":4333208, "ctx":"ReplicaSetMonitor-TaskExecutor","msg":"RSM host selection timeout","attr":{"replicaSet":"replicaset","error":"FailedToSatisfyReadPreference: Could not find host matching read preference { mode: \"nearest\" } for set replicaset"}}
Error: connect failed to replica set replicaset/127.0.0.1:27037,127.0.0.1:27038,127.0.0.1:27039 :
connect@src/mongo/shell/mongo.js:374:17
@(connect):2:6
exception: connect failed
exiting with code 1
┌─iz|fe  (~)
└─■ 
┌─iz|fe  (~)
└─■ mongo --host replicaset/mongo_primary_test:27037,mongo_secondary_test:27038,mongo_arbiter_test:27039 --username root --password=password123
MongoDB shell version v4.4.11
connecting to: mongodb://mongo_primary_test:27037,mongo_secondary_test:27038,mongo_arbiter_test:27039/?compressors=disabled&gssapiServiceName=mongodb&replicaSet=replicaset
{"t":{"$date":"2022-02-02T23:07:58.543Z"},"s":"I",  "c":"NETWORK",  "id":4333208, "ctx":"ReplicaSetMonitor-TaskExecutor","msg":"RSM host selection timeout","attr":{"replicaSet":"replicaset","error":"FailedToSatisfyReadPreference: Could not find host matching read preference { mode: \"nearest\" } for set replicaset"}}
Error: connect failed to replica set replicaset/mongo_primary_test:27037,mongo_secondary_test:27038,mongo_arbiter_test:27039 :
connect@src/mongo/shell/mongo.js:374:17
@(connect):2:6
exception: connect failed
exiting with code 1

```

traceback docker-composer:
``` bash
mongo_primary_test   | {"t":{"$date":"2022-02-02T23:40:58.878+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.28.0.1:42806","connectionId":54,"connectionCount":10}}
mongo_primary_test   | {"t":{"$date":"2022-02-02T23:40:58.878+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn54","msg":"client metadata","attr":{"remote":"172.28.0.1:42806","client":"conn54","doc":{"application":{"name":"MongoDB Shell"},"driver":{"name":"MongoDB Internal Client","version":"4.2.6-18-g6cdb6ab"},"os":{"type":"Linux","name":"Fedora release 34 (Thirty Four)","architecture":"x86_64","version":"Kernel 5.15.15-200.rog.fc34.x86_64"}}}}
mongo_primary_test   | {"t":{"$date":"2022-02-02T23:40:58.880+00:00"},"s":"I",  "c":"ACCESS",   "id":20250,   "ctx":"conn54","msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-256","speculative":false,"principalName":"root","authenticationDatabase":"admin","remote":"172.28.0.1:42806","extraInfo":{}}}

```

![изображение](https://user-images.githubusercontent.com/16782308/152256485-7a6082c9-0cf8-4633-bfaf-38c3ff1d54f0.png)


``` bash

└─■ docker-compose ps
        Name                      Command               State                      Ports                    
------------------------------------------------------------------------------------------------------------
mongo_arbiter_test     /opt/bitnami/scripts/mongo ...   Up      0.0.0.0:27039->27017/tcp,:::27039->27017/tcp
mongo_primary_test     /opt/bitnami/scripts/mongo ...   Up      0.0.0.0:27037->27017/tcp,:::27037->27017/tcp
mongo_secondary_test   /opt/bitnami/scripts/mongo ...   Up      0.0.0.0:27038->27017/tcp,:::27038->27017/tcp

```
