### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by halindraprakoso** [bitnami/bitnami-docker-mongodb#322]
**Description**

Hello, I'm trying to set up replica set using the docker compose from the readme (only added ports), but I cannot connect to it using GUI  and keep getting **Authentication failed.** with either
`mongodb://root:password123@localhost:27017/?authSource=admin`
or
`mongodb://root:password123@localhost:27017,localhost:27018,localhost:27019/?authSource=admin&replicaSet=replicaset`. 

However `mongo admin -u root -p password123` works fine in the docker cli. 

**Steps to reproduce the issue:**

```
version: "2"

services:
  mongodb-primary:
    image: "bitnami/mongodb:latest"
    ports:
      - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

    volumes:
      - "mongodb_master_data:/bitnami"

  mongodb-secondary:
    image: "bitnami/mongodb:latest"
    depends_on:
      - mongodb-primary
    ports:
      - 27018:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: "bitnami/mongodb:latest"
    depends_on:
      - mongodb-primary
    ports:
      - 27019:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  mongodb_master_data:
    driver: local
```

run `docker-compose up --detach`

**Describe the results you expected:**

Connected to the database using compass or mongobooster

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**

I also tried it in a VM, same story.
