### ISSUE TITLE
Mongodb container exists with code 132 upon creation

### ISSUE THREAD

**Issue by anoduck** [bitnami/bitnami-docker-mongodb#325]
### Name and Version

bitnami/mongodb:latest

### Environment

Running bitnami/mongodb:latest on Alpine linux with docker-compose.

### Configuration

Configuration is pretty straight forward and typical of docker-compose.yml
```yaml
# Mongo DB ------------------------------------ 
  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongdb_container
    ports:
      - '27017:27017'
    volumes:
      - type: bind
        source: $PWD/db
        target: /bitnami/mongodb
    environment:
      - MONGODB_ROOT_PASSWORD=RootPassword
      - MONGODB_USER=User
      - MONGODB_PASSWORD=Password
      - MONGODB_DATABASE=Database
      - MONGODB_ENABLE_IPV6=no
      - MONGODB_SYSTEM_LOG_VERBOSITY=3
      - MONGODB_ENABLE_JOURNAL=true
```

### What action caused it to stop working?

This is where it gets weird, well for me anyway. I attempted to start another docker-compose stack, a cloud9 + cloudcmd stack with docker-compose. It was during the startup of the cloud9 stack, that mongodb exited and never returned to life. The docker-compose file for that stack is posted below.

```yml
version: "2.1"
services:
  cloud9:
    image: lscr.io/linuxserver/cloud9
    container_name: cloud9
    environment:
      - PUID=1000 # <--- Potential source
      - PGID=1000 # <--- Potential source
      - TZ=America/New_York
      - GITURL=https://github.com/linuxserver/docker-cloud9.git #optional
      - USERNAME= #optional
      - PASSWORD= #optional
    volumes:
      - $HOME/Folder:/code #optional
      - /var/run/docker.sock:/var/run/docker.sock #optional  # <--- Potential source
    ports:
      - 8000:8000
    restart: unless-stopped
  cloudcmd:
    image: coderaiser/cloudcmd
    container_name: cloudcmd
    ports:
      - 8888:8000
    volumes:
      - $HOME/Folder:/root # <--- Potential source
      - /:/mnt/fs # <--- Potential source
```

I assumed this was caused by limited resources, but once the cloud9 stack was removed, mongodb never returned. I also checked filesystem space, which checked out good as well. 

### Error Output

Only exists with code 132.

### What is the expected behavior?

The container never should have exited.

### What do you see instead?

Exited with code 132.

### Additional information

I am completely baffled by this one, and reasonably upset. Mongodb was the database for a live website I was hosting. Now, that site is down.
