### ISSUE TITLE
Initialize hangs with docker compose replica set configuration

### ISSUE THREAD

**Issue by gf3** [bitnami/bitnami-docker-mongodb#326]
### Name and Version

bitnami/mongodb:latest

### docker-compose.yml
```yaml
version: "3.8"

services:
  mongo-primary:
    container_name: mongo-primary
    image: bitnami/mongodb:latest
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      BITNAMI_DEBUG: true
      MONGODB_ADVERTISED_HOSTNAME: "mongo-primary"
      MONGODB_DATABASE: "freshline-backend-development"
      MONGODB_PASSWORD: "password"
      MONGODB_REPLICA_SET_KEY: "replicaset"
      MONGODB_REPLICA_SET_MODE: "primary"
      MONGODB_ROOT_PASSWORD: "password"
      MONGODB_SYSTEM_LOG_VERBOSITY: 5
      MONGODB_USERNAME: "development"
    ports:
      - 27017:27017
    volumes:
      - mongo-primary-data:/bitnami:rw

  mongo-secondary:
    container_name: mongo-secondary
    image: bitnami/mongodb:latest
    depends_on:
      - mongo-primary
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      BITNAMI_DEBUG: true
      MONGODB_ADVERTISED_HOSTNAME: "mongo-secondary"
      MONGODB_INITIAL_PRIMARY_HOST: "mongo-primary"
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: "password"
      MONGODB_REPLICA_SET_KEY: "replicaset"
      MONGODB_REPLICA_SET_MODE: "secondary"
      MONGODB_SYSTEM_LOG_VERBOSITY: 5
    ports:
      - 27018:27017
    volumes:
      - mongo-secondary-data:/bitnami:rw

volumes:
  mongo-primary-data:
  mongo-secondary-data:
```

### Command
```sh
docker compose up
```

### What is the expected behavior?

Successful initialization.

### What do you see instead?

```
Attaching to mongo-primary, mongo-secondary
mongo-primary    | mongodb 19:29:27.28
mongo-primary    | mongodb 19:29:27.31 Welcome to the Bitnami mongodb container
mongo-primary    | mongodb 19:29:27.33 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongo-primary    | mongodb 19:29:27.34 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongo-primary    | mongodb 19:29:27.36
mongo-primary    | mongodb 19:29:27.38 INFO  ==> ** Starting MongoDB setup **
mongo-primary    | mongodb 19:29:27.55 INFO  ==> Validating settings in MONGODB_* env vars...
mongo-primary    | mongodb 19:29:27.57 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=true. For safety reasons, do not use this flag in a production environment.
mongo-primary    | mongodb 19:29:27.72 INFO  ==> Initializing MongoDB...
mongo-primary    | mongodb 19:29:27.93 INFO  ==> Deploying MongoDB from scratch...
mongo-primary    | mongodb 19:29:27.98 DEBUG ==> Starting MongoDB in background...
mongo-secondary  | mongodb 19:29:28.48
mongo-secondary  | mongodb 19:29:28.50 Welcome to the Bitnami mongodb container
mongo-secondary  | mongodb 19:29:28.52 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongo-secondary  | mongodb 19:29:28.54 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongo-secondary  | mongodb 19:29:28.56
mongo-secondary  | mongodb 19:29:28.58 INFO  ==> ** Starting MongoDB setup **
mongo-secondary  | mongodb 19:29:28.75 INFO  ==> Validating settings in MONGODB_* env vars...
mongo-secondary  | mongodb 19:29:28.77 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=true. For safety reasons, do not use this flag in a production environment.
mongo-secondary  | mongodb 19:29:28.93 INFO  ==> Initializing MongoDB...
mongo-secondary  | mongodb 19:29:29.13 INFO  ==> Deploying MongoDB from scratch...
mongo-secondary  | mongodb 19:29:29.18 DEBUG ==> Starting MongoDB in background...
```

It hangs at `Starting MongoDB in background...` indefinitely.

### Docker
```
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:46:56 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.5.0 (74594)
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:07 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker Compose
```
Docker Compose version v2.2.3
```

### Hardware
```
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,4
      Chip: Apple M1 Max
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 64 GB
      System Firmware Version: 7429.81.3
      OS Loader Version: 7429.81.3
      Serial Number (system): XXXXXXXXXX
      Hardware UUID: AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE
      Provisioning UDID: XXXXXXXX-YYYYYYYYYYYYYYYY
      Activation Lock Status: Enabled
```

**Comment by gf3** [comment]
@javsalgar yes, i see the same issue with that docker compose file:

![screenshot](https://screenshot.pics/s/Cbitnami-mongodb-replicaset-test__2022-03-22_15-45-58.png)

seems to just hand indefinitely, each container is eating 100% of its available CPU:

![cpu](https://screenshot.pics/s/Container_instance_2022-03-22_15-47-27.png)

and the containers are running in amd64 emulation mode (not sure if related):

![emulation](https://screenshot.pics/s/Container_list_2022-03-22_15-48-16.png)

**Comment by javsalgar** [comment]
Could you also try entering in the containers that are hanged and execute `ps xufa` to see in which exact process it is hanging up?

**Comment by danieletorelli** [comment]
@javsalgar it happens also with only one primary node:

```
mongodb 06:57:07.50 
mongodb 06:57:07.52 Welcome to the Bitnami mongodb container
mongodb 06:57:07.54 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 06:57:07.56 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 06:57:07.58 
mongodb 06:57:07.61 INFO  ==> ** Starting MongoDB setup **
mongodb 06:57:07.79 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 06:57:07.95 INFO  ==> Initializing MongoDB...
mongodb 06:57:08.13 INFO  ==> Deploying MongoDB from scratch...
```

![Top](https://user-images.githubusercontent.com/2891141/160552140-d7e6d785-69f7-4ab6-a662-6015f3dc5b51.png)

**Comment by javsalgar** [comment]
Is there any trace in `/opt/bitnami/mongodb/logs`?

**Comment by danieletorelli** [comment]
> Is there any trace in `/opt/bitnami/mongodb/logs`?

There's only one file there, and points to stdout:
```
I have no name!@d7488b9730fa:/opt/bitnami/mongodb/logs$ ls -l
total 0
lrwxrwxrwx 1 root root 11 Mar 30 18:03 mongodb.log -> /dev/stdout
```

**Comment by danieletorelli** [comment]
Nope, the last message I see before it hangs is:
```
mongodb 06:57:08.13 INFO  ==> Deploying MongoDB from scratch...
```
as in https://github.com/bitnami/bitnami-docker-mongodb/issues/326#issuecomment-1081486108, that is the same behavior that @gf3 is showing with the screenshot in https://github.com/bitnami/bitnami-docker-mongodb/issues/326#issuecomment-1075568446.

**Comment by javsalgar** [comment]
Hi,

Please ensure that you are setting the BITNAMI_DEBUG variable to true, as it seems clear to me that the issue lies here

```
        info "Deploying MongoDB from scratch..."
        ensure_dir_exists "$MONGODB_DATA_DIR/db"
        am_i_root && chown -R "$MONGODB_DAEMON_USER" "$MONGODB_DATA_DIR/db"

        mongodb_start_bg "$MONGODB_CONF_FILE" <----- HERE

```

**Comment by danieletorelli** [comment]
> Hi,
> 
> Please ensure that you are setting the BITNAMI_DEBUG variable to true, as it seems clear to me that the issue lies here.

With the flag set to `true`:
```
mongodb 13:07:34.12 
mongodb 13:07:34.14 Welcome to the Bitnami mongodb container
mongodb 13:07:34.16 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 13:07:34.18 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 13:07:34.19 
mongodb 13:07:34.21 INFO  ==> ** Starting MongoDB setup **
mongodb 13:07:34.37 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 13:07:34.53 INFO  ==> Initializing MongoDB...
mongodb 13:07:34.69 INFO  ==> Deploying MongoDB from scratch...
mongodb 13:07:34.74 DEBUG ==> Starting MongoDB in background...
```
no trace of other logs than `mongodb.log` (pointing to `stdout`) in `/opt/bitnami/mongodb/logs` and CPU still stuck at 100% like in the previous screenshot in https://github.com/bitnami/bitnami-docker-mongodb/issues/326#issuecomment-1081486108.

**Comment by javsalgar** [comment]
Hi,


I have an idea to see what the potential error is.

Execute the following command (assuming you are using the same docker-compose.file as the OP)

```
docker-compose run mongo-primary bash
```

Then, inside the container

```
rm /opt/bitnami/mongodb/logs/mongodb.log
touch /opt/bitnami/mongodb/logs/mongodb.log

/opt/bitnami/scripts/mongodb/entrypoint.sh /opt/bitnami/scripts/mongodb/run.sh
```

That way we should be able to see what the logs show.

**Comment by raphael-papazikas** [comment]
This issue seems to happen only on `latest` because if i switch back to version `4.4.2` the issue no longer appears.

**Comment by raphael-papazikas** [comment]
Running on apple silicon macbook pro, version `12.1`

docker engine: `v20.10.11`

In docker dashboard i see the following label: 
<img width="250" alt="image" src="https://user-images.githubusercontent.com/33499602/162494827-ed042d7a-983f-4285-85ff-8e5a45399474.png">


compose file
```
version: '3'
services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_REPLICA_SET_KEY=key
      - BITNAMI_DEBUG=true
    ports:
      - "27017:27017"

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_REPLICA_SET_KEY=key
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=root
      - BITNAMI_DEBUG=true
```
