### ISSUE TITLE
Using docker swarm secrets via _FILE doesn't work with different UIDs

### ISSUE THREAD

**Issue by alexrudd2** [bitnami/bitnami-docker-mongodb#329]
### Name and Version

mongodb:5.0.6-debian-10-r45

### What steps will reproduce the bug?

```
<Dockerfile>
FROM bitnami/mongodb:5.0
USER 0
RUN install_packages cron
RUN echo "America/Chicago" > /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata
USER 1002
```
Deploy the following docker-compose stack (via Portainer).  Note I've omitted irrelevant details like our local registry; each service is using `mongo` as built above and the docker Swarm secrets are setup correctly.
```
  mongo-a:
    volumes:
      - /media/glusterdata/mongo:/bitnami/mongodb
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=mongo_mongo-a
      - MONGODB_ROOT_PASSWORD_FILE=/run/secrets/MONGO_ROOT_PASSWORD
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD_FILE=/run/secrets/MONGO_PASSWORD
      - MONGODB_DATABASE=logs
    secrets:
      - MONGO_PASSWORD
      - MONGO_ROOT_PASSWORD

  mongo-b:
    volumes:
      - mongo-b_data:/bitnami/mongodb
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_ADVERTISED_HOSTNAME=mongo_mongo-b
      - MONGODB_INITIAL_PRIMARY_HOST=mongo_mongo-a
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD_FILE=/run/secrets/MONGO_ROOT_PASSWORD
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_USERNAME=user
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_DATABASE=logs
    secrets:
      - MONGO_ROOT_PASSWORD
  mongo-c:
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_ADVERTISED_HOSTNAME=mongo_mongo-c
      - MONGODB_INITIAL_PRIMARY_HOST=mongo_mongo-a
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD_FILE=/run/secrets/MONGO_ROOT_PASSWORD
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    secrets:
      - MONGO_ROOT_PASSWORD
```

Docker swarm secrets from a shell on `mongo-a` are working correctly.
```
I have no name!@c83858f1b37a:/$ cd /run/secrets
I have no name!@c83858f1b37a:/run/secrets$ ls
MONGO_PASSWORD  MONGO_ROOT_PASSWORD
```

### What is the expected behavior?

A working replicaSet, with all three services starting up correctly.  This all works if I use e.g. `MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD` instead of `MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD_FILE`.  It appears to me that `_FILE` should be copied to the base envvar by the following bitnami script:
https://github.com/bitnami/bitnami-docker-mongodb/blob/49aed5686c69033c7262a90194aff7c2e3b24071/5.0/debian-10/rootfs/opt/bitnami/scripts/mongodb-env.sh#L65-L72

### What do you see instead?

The base environment variables are not being set correctly.
```
I have no name!@c83858f1b37a:/run/secrets$ printenv
PWD=/run/secrets
MONGODB_ROOT_PASSWORD_FILE=/run/secrets/MONGO_ROOT_PASSWORD
BITNAMI_IMAGE_VERSION=5.0.6-debian-10-r45
MONGODB_ADVERTISED_HOSTNAME=mongo_mongo-a
MONGODB_DATABASE=logs
MONGODB_REPLICA_SET_MODE=primary
MONGODB_REPLICA_SET_KEY=replicasetkey123
MONGODB_USERNAME=user
MONGODB_PASSWORD_FILE=/run/secrets/MONGO_PASSWORD
PATH=/opt/bitnami/common/bin:/opt/bitnami/mongodb/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
OLDPWD=/
```

`mongo-a` service fails to create the `root` user.
```
{"t":{"$date":"2022-03-31T11:22:26.773-05:00"},"s":"I",  "c":"ACCESS",   "id":20251,   "ctx":"conn255","msg":"Supported SASL mechanisms requested for unknown user","attr":{"user":{"user":"root","db":"admin"}}}
{"t":{"$date":"2022-03-31T11:22:26.774-05:00"},"s":"I",  "c":"ACCESS",   "id":20249,   "ctx":"conn255","msg":"Authentication failed","attr":{"mechanism":"SCRAM-SHA-256","speculative":true,"principalName":"root","authenticationDatabase":"admin","remote":"10.0.5.18:49492","extraInfo":{},"error":"UserNotFound: Could not find user \"root\" for db \"admin\""}}
```

`mongo-b` service fails to create the `user` user:
```
mongodb 11:03:30.00 INFO  ==> ** Starting MongoDB setup **
mongodb 11:03:30.02 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 11:03:30.02 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mongodb 11:03:30.02 WARN  ==> User user will not be created as its password is empty or not set. MongoDB cannot create users with blank passwords.
mongodb 11:03:30.03 INFO  ==> Initializing MongoDB...
mongodb 11:03:30.05 INFO  ==> Deploying MongoDB from scratch...
mongodb 11:03:30.80 INFO  ==> Creating users...
mongodb 11:03:30.80 WARN  ==> Cannot create user 'user', no password provided
mongodb 11:03:30.80 INFO  ==> Users created
```

### Additional information

I've intentionally set `ALLOW_EMPTY_PASSWORD=yes` _on the secondary_ because I believe there's another scripting bug where the secondary fails to start without it.
