### ISSUE TITLE
Again, can't connect from Compass

### ISSUE THREAD

**Issue by koiosoft** [bitnami/bitnami-docker-mongodb#332]
### Name and Version

bitnami/bitnami-docker-mongodb

### What steps will reproduce the bug?

I'm using:
```yaml
version: "2"

services:
  mongodb-primary:
    image: "bitnami/mongodb:latest"
    ports:
      - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

    volumes:
      - "mongodb_master_data:/bitnami"

  mongodb-secondary:
    image: "bitnami/mongodb:latest"
    depends_on:
      - mongodb-primary
    ports:
      - 27018:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: "bitnami/mongodb:latest"
    depends_on:
      - mongodb-primary
    ports:
      - 27019:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  mongodb_master_data:
    driver: local
```
But I can't connect to MongoDb instances, neither with Compass, nor with Mongo Client (Shell).

I have seen this raised many times. But the solutions have not been clear at all. If there really is a transparent solution, such as a Certified Image like the one Bitnami offers, then maybe there wouldn't be so many questions about the same thing, over and over again.

But I have already followed N amount of comments on the issues, but nothing has worked. It's all a mystery.

I seriously request help on this matter.

I have a Mac OS X (Apple Silicon)

### What is the expected behavior?

I should be able to connect from Compass or from the Shell

### What do you see instead?

I can not connect
