### ISSUE TITLE
Mongodb never runs

### ISSUE THREAD

**Issue by borisn70** [bitnami/bitnami-docker-mongodb#334]
### Name and Version

bitnami/mongodb:latest

### What steps will reproduce the bug?

Trying to run bitnami/mongodb:latest on MacBook PRO M1 (macOS Monterey 12.30) via docker-compose.yml file (see below)

```yaml
version: "3.3"
services:
  mongodbwh1:
    container_name: mongodbwh
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_DATABASE=mongodbwh
      - MONGODB_USERNAME=some_username
      - MONGODB_PASSWORD=some_password
      - MONGODB_ROOT_USER=root_username
      - MONGODB_ROOT_PASSWORD=root_password
      - BITNAMI_DEBUG=1
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/database:/bitnami/mongodb
    networks:
      - webapp-network
    restart: always
networks:
  webapp-network:
    driver: bridge
```

### What is the expected behavior?

MongoDB should run inside the container or give any error if there is something wrong.

### What do you see instead?

I see the following:

```bash
mongodb 17:49:40.73 
mongodb 17:49:40.75 Welcome to the Bitnami mongodb container
mongodb 17:49:40.77 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 17:49:40.79 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 17:49:40.81 
mongodb 17:49:40.83 INFO  ==> ** Starting MongoDB setup **
mongodb 17:49:40.99 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 17:49:41.17 INFO  ==> Initializing MongoDB...
mongodb 17:49:41.38 INFO  ==> Deploying MongoDB from scratch...
mongodb 17:49:41.43 DEBUG ==> Starting MongoDB in background...
```
<img width="930" alt="Screen Shot 2022-04-26 at 9 50 49 PM" src="https://user-images.githubusercontent.com/3252282/165362497-f406d648-44ce-4f70-a83b-3e27e4533ac7.png">

### Additional information

On Debian Linux the provided docker-compose.yml  works as expected. 

Here is the Docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.1)
  compose: Docker Compose (Docker Inc., v2.3.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.765GiB
 Name: docker-desktop
 ID: NOSP:ZUC2:5NGC:HPXU:R6TH:HBBS:DCBX:2ESK:YBXG:7KSY:XUAW:I6PA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

docker-compose version 1.29.2, build 5becea4c
