### ISSUE TITLE
Hostname/IP does not match certificate's altnames

### ISSUE THREAD

**Issue by linuxmail** [bitnami/bitnami-docker-mongodb#341]
### Name and Version

bitnami/mongodb:latest

### What steps will reproduce the bug?

1. Have a KVM VM Debian Buster
2. Have a **wildcard** self signed cert mounted into the containers
3. Try to add TLS params to docker compose
4. Start MongoDB cluster

### What is the expected behavior?

Get a working MongoDB 5.x cluster working with enabled TLS

### What do you see instead?

```
dfuchs@fra-dev-buster-05:~/git/sandbox$ docker logs -f sandbox-mongodb-01-sandbox.example.local-1
mongodb 08:10:44.72 
mongodb 08:10:44.72 Welcome to the Bitnami mongodb container
mongodb 08:10:44.72 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 08:10:44.72 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 08:10:44.72 
mongodb 08:10:44.72 INFO  ==> ** Starting MongoDB setup **
mongodb 08:10:44.76 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 08:10:44.84 INFO  ==> Initializing MongoDB...
mongodb 08:10:44.88 INFO  ==> Deploying MongoDB from scratch...
MongoNetworkError: connect ECONNREFUSED 172.19.0.2:27017
mongodb 08:10:49.03 INFO  ==> Creating users...
mongodb 08:10:49.03 INFO  ==> Creating root user...
Current Mongosh Log ID:	62971f0c92529878701d9eb4
Connecting to:		mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&tls=true&tlsCertificateKeyFile=%2Fcerts%2Ffull-chain-key.pem&tlsCAFile=%2Fcerts%2Fcacert.pem&appName=mongosh+1.4.2
MongoServerSelectionError: Hostname/IP does not match certificate's altnames: IP: 127.0.0.1 is not in the cert's list: 
mongodb 08:10:54.19 INFO  ==> Stopping MongoDB...
```

As example ... 

### Additional information

* docker-compose parts:

```yaml
  mongodb-01-sandbox.example.local:
    image: 'bitnami/mongodb:latest'
    networks:
      - app-mongodb
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-01-sandbox.example.local
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_EXTRA_FLAGS=--tlsMode=requireTLS --tlsCertificateKeyFile=/certs/full-chain-key.pem --tlsClusterFile=/certs/full-chain-key.pem --tlsCAFile=/certs/cacert.pem
      - MONGODB_CLIENT_EXTRA_FLAGS=--tls --tlsCertificateKeyFile=/certs/full-chain-key.pem --tlsCAFile=/certs/cacert.pem
    volumes:
      - certs:/certs:ro
      - 'mongodb-01-sandbox.example.local_data:/bitnami'
  mongodb-02-sandbox.example.local:
    image: 'bitnami/mongodb:latest'
    networks:
      - app-mongodb
    depends_on:
      - mongodb-01-sandbox.example.local
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-02-sandbox.example.local
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-01-sandbox.example.local
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_EXTRA_FLAGS=--tlsMode=requireTLS --tlsCertificateKeyFile=/certs/full-chain-key.pem --tlsClusterFile=/certs/full-chain-key.pem --tlsCAFile=/certs/cacert.pem
      - MONGODB_CLIENT_EXTRA_FLAGS=--tls --tlsCertificateKeyFile=/certs/full-chain-key.pem --tlsCAFile=/certs/cacert.pem
    volumes:
      - certs:/certs:ro
      - 'mongodb-02-sandbox.example.local_data:/bitnami'
  mongodb-arbiter-sandbox.example.local:
    image: 'bitnami/mongodb:latest'
    networks:
      - app-mongodb
    depends_on:
      - mongodb-01-sandbox.example.local
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter-sandbox.example.local
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-01-sandbox.example.local
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_EXTRA_FLAGS=--tlsMode=requireTLS --tlsCertificateKeyFile=/certs/full-chain-key.pem --tlsClusterFile=/certs/full-chain-key.pem --tlsCAFile=/certs/cacert.pem
      - MONGODB_CLIENT_EXTRA_FLAGS=--tls --tlsCertificateKeyFile=/certs/full-chain-key.pem --tlsCAFile=/certs/cacert.pem
    volumes:
      - certs:/certs:ro
      - 'mongodb-arbiter-sandbox.example.local_data:/bitnami'
```

MongoDB works if TLS is disabled / not used.
