### ISSUE TITLE
How do I run mongodb container as root user

### ISSUE THREAD

**Issue by Ed87** [bitnami/bitnami-docker-mongodb#342]
### Name and Version

docker.io/bitnami/mongodb:4.4.6-debian-10-r0

### What steps will reproduce the bug?

I have kubectl access only to our k8s cluster and when I attempt to do:

```
mongodump -u aaa -p abc123 --authenticationDatabase admin -d TestDb --gzip --out /var/backups/dump-25-05-22/mybackup.gz
```

via` kubectl exec -t <pod_name> --bash` I am getting an error:

```
Failed: error dumping metadata: error creating directory for metadata file /var/backups/...: permission denied
```

These are my current permissions on the mount path (/var/backups):

```console
$ ls -la 
drwxr-xr-x 2 root root 4096 Jun 11  2021 .
drwxr-xr-x 1 root root 4096 Jun 11  2021 ..
```

The manifest for the MongoDB deployment is as below:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: labs
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
securityContext:
        fsGroup: 1001
        sysctls: []
      containers:
      - name: mongodb
        image: docker.io/bitnami/mongodb:4.4.6-debian-10-r0
        imagePullPolicy: "IfNotPresent"
        securityContext:
            runAsNonRoot: true
            runAsUser: 1001
        ports:
          - containerPort: 27017
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-ls51
                  key: mongodb-root-password
            - name: ALLOW_EMPTY_PASSWORD
              value: "no"
            - name: MONGODB_SYSTEM_LOG_VERBOSITY
              value: "0"
            - name: MONGODB_DISABLE_SYSTEM_LOG
              value: "no"
            - name: MONGODB_DISABLE_JAVASCRIPT
              value: "no"
            - name: MONGODB_ENABLE_JOURNAL
              value: "yes"
            - name: MONGODB_ENABLE_IPV6
              value: "no"
            - name: MONGODB_ENABLE_DIRECTORY_PER_DB
              value: "no"
            - name: MONGODB_EXTRA_FLAGS
              value: "--wiredTigerCacheSizeGB=1"
        volumeMounts: 
            - mountPath: /data/db
              name: mongodb-vol
      volumes:
      - name: mongodb-vol
        persistentVolumeClaim:
          claimName: mongodb-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: labs
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017 
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless-service
  namespace: labs
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017 `

I have added a dedicated user in the database  for backups as:

```
db.createUser( {user: "aaa", pwd: "abc123", roles: ["userAdminAnyDatabase", "dbAdminAnyDatabase", "readWriteAnyDatabase","backup"], mechanisms:["SCRAM-SHA-1"]})
```

### What is the expected behavior?

mongodump should run as expected and produce backup files on the provided path.

### What do you see instead?

I see an error that entails that the user under which the container is running has no write permissions to any directory, including the backup directory /var/backups :

```
Failed: error dumping metadata: error creating directory for metadata file /var/backups/...: permission denied
```

### Additional information

I was only doing `kubectl exec -it` as a test case, I wanted to _verify_ if I can do backups first with the mongo user I created. But eventually, this backup functionality will run _**as a k8s CronJob**_ that targets this mongo deployment: [link](https://simodev.medium.com/how-to-automate-backup-mongodb-using-kubernetes-b07c61a8a6ec)

I have also tried the following :
1.
```console
$ sudo chmod 777 -R /var/backups/
bash: sudo: command not found
```

2.
```console
$chmod 777 -R /var/backups/ 
error changing permissions of '/var/backups/': Operation not permitted
```

3. Tried to enable sudo mode (Requires password and I don't know it)
```
$su -
```

Having done a lot of digging around this the best solution I have is to tweak the mongo Dockerfile and build my own custom image. The only feasible solution I found is at this [link](https://stackoverflow.com/questions/44781889/permission-error-with-mongo-when-running-docker) and it says _**"Configure mongo to run as root via editing the mongo config and copying it during the docker build process. This assumes you're using a docker file to build that image. Then it will have no problem accessing the attached volume."**_

My question(s):

1. _What should I change_ in the dockerfile/yaml to enable privileges. It seems odd to me that the permissions are disabled by default. Granted I do not want to keep the backups in the same volume mount as the instance but rather just run the backup and then move files to another pod.

2. Given an example Dockerfile as below how would I make the so-called mongod user run as root ? Is it even recommended to build custom bitnami mongodb images  like my case or I am missing something else obvious:

```Dockerfile
FROM docker.io/bitnami/mongodb:4.4.6-debian-10-r0`
COPY entrypoint.sh /root/entrypoint.sh
RUN chown -R mongodb:mongodb /var/log /data/db 
USER mongodb
ENTRYPOINT ["/root/entrypoint.sh"]`
```

3. At which level is this mongodb user accessible ? I have checked the users in the mongodb container but they is no entry for such (Unless Im missing something obvious) .  I was sure that I should have necessary rights under **/data/db/** directory since it is the home directory of mongod user:
```console
$ cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats`
```
