### ISSUE TITLE
Macos M1 unable to connect to database

### ISSUE THREAD

**Issue by MohamadTahir** [bitnami/bitnami-docker-mongodb#343]
### Name and Version

bitnami/mongodb:5.0.8

### What steps will reproduce the bug?

run the container on a macOS m1 machine with docker desktop version v4.9.0 then try to connect with MongoDB compass or any client.

### What is the expected behavior?

being able to connect.

### What do you see instead?

not being able to connect, I get a connection time out trying to connect.

### Additional information

I am using a docker compose and here is the file 

```
services:
  mongodb:
    image: 'bitnami/mongodb:5.0.8'
    environment:
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_PORT_NUMBER=27017
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=123456
    ports:
      - 27018:27017
```

and this is my connection string `mongodb://root:root@localhost:27018/`

I would like to point out that I tried running MongoDB docker image by MongoDB and everything worked fine

docker compose file
```
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
```

connection string `mongodb://root:root@localhost:27018/`
