### ISSUE TITLE
What is the exact format for Mongo-URI when connecting to Kubernetes MongoDB instance

### ISSUE THREAD

**Issue by Ed87** [bitnami/bitnami-docker-mongodb#344]
### Name and Version

docker.io/bitnami/mongodb:4.4.6-debian-10-r0

### What steps will reproduce the bug?

1. `kubectl exec -it <pod_name> -- sh`
2. Run mongodump command while passing a MongoURI to the command

### What is the expected behavior?

I want to setup backups for my MongoDB instance and the k8s cron job that executes these backups **_will need a Mongo-URI_** in order to connect to the deployment .

If the CronJob connects successfully it will execute the backup and dump the files at a path specified in the job Dockerfile.

I expect to be able to test  a MongoURI value first before I plug it into the job. To do this I exec into the pod and attempt to do mongodump .

I am following the example given [here](https://simodev.medium.com/how-to-automate-backup-mongodb-using-kubernetes-b07c61a8a6ec)

### What do you see instead?

I want to backup a database named **platforms** using the _default built-in root user_ (specified [here](https://docs.bitnami.com/aws/infrastructure/mongodb/administration/backup-restore-mongodb/)) and I am getting the following errors :

a)  `kubectl exec -it <pod_name> -- sh`
`mongodump --uri="mongodb://root:PASSWORD@mongo-headless-service.svc.cluster.local:27017/platforms" --authenticationDatabase admin --gzip --out /var/backups/dump-25-05-22/mybackup.gz`

I get error 
`2022-06-10T12:37:41.690+0000    Failed: can't create session: could not connect to server: server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: mongo-headless-service.svc.cluster.local:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : dial tcp: lookup mongo-headless-service.svc.cluster.local: no such host }, ] }`

b)  `kubectl exec -it <pod_name> -- sh`
`mongodump --uri="mongodb://root:PASSWORD@mongodb-headless-service/platforms?authSource=admin" --gzip --out /var/backups/dump-25-05-22/mybackup.gz`

I get error 
`Failed: can't create session: could not connect to server: connection() : auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.`

c)   `kubectl exec -it <pod_name> -- sh`
`mongodump --uri="mongodb://root:PASSWORD@mongo-headless-service.svc.cluster.local:27017/admin" -d admin --gzip --out /var/backups/dump-25-05-22/mybackup.gz`
I also get an error
`2022-06-10T11:36:38.578+0000    Failed: can't create session: could not connect to server: server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: mongo-headless-service.svc.cluster.local:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : dial tcp: lookup mongo-headless-service.svc.cluster.local: no such host }, ] }`

I tried to verify if the default built-in user can indeed authenticate against the admin db :
`use admin`
`db.auth('root','PASSWORD')`

It also fails with Authentication Failed (Shouldn't the built in root connect by default ?? )

### Additional information

For context I intend to use the Mongo-URI value in my CronJob as below :

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongodump-backup
spec:
  schedule: "0 */6 * * *" #Cron job every 6 hours
  startingDeadlineSeconds: 60
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mongodump-backup
              image: microfunctions/microfunctions-mongodump
              imagePullPolicy: "IfNotPresent"
              env:
                - name: DB_NAME
                  value: "microfunctions"
                - name:  MONGODB_URI
                  value: <mongo-URI-here>
              volumeMounts:
                - mountPath: "/mongodump"
                  name: mongodump-volume
              command: ['sh', '-c',"./dump.sh"]
          restartPolicy: OnFailure
          volumes:
            - name: mongodump-volume
              persistentVolumeClaim:
                claimName: mongodb-backup
```

My MongoDB Deployment :

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: labs
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: docker.io/bitnami/mongodb:4.4.6-debian-10-r0
        imagePullPolicy: "IfNotPresent"
        securityContext:
            runAsNonRoot: true
            runAsUser: 1001
        ports:
          - containerPort: 27017
        env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret-amended
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret-amended
                  key: mongo-root-password
        volumeMounts: 
            - mountPath: /data/db
              name: mongodb-vol
      volumes:
      - name: mongodb-vol
        persistentVolumeClaim:
          claimName: mongodb-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: labs
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017 
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless-service
  namespace: labs
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017 
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-single-clusterip
  namespace: labs
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
```
