### ISSUE TITLE
Cannot connect to ReplicaSet using MongoDB Compass

### ISSUE THREAD

**Issue by adamcole123** [bitnami/bitnami-docker-mongodb#346]
### Name and Version

bitnami/mongodb:latest

### What steps will reproduce the bug?

Use this docker-compose setup
```
version: "3.7"

services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

    volumes:
      - 'mongodb_master_data:/bitnami'

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
volumes:
  mongodb_master_data:
    driver: local
```

Try to connect to the database with mongodb compass using this URI
`mongodb://root:password123@localhost:27017/`

For reference, i am following instructions [here](https://github.com/bitnami/bitnami-docker-mongodb#optional-create-a-replication-hidden-node)

### What is the expected behavior?

I am expecting for it to connect and show some databases

### What do you see instead?

I am getting an error saying this: `getaddrinfo ENOTFOUND mongodb-secondary`

![image](https://user-images.githubusercontent.com/32772788/173347503-72c4a759-4660-42c6-97e6-4bc96c6e8667.png)
