### ISSUE TITLE
Mongo Replicaset - MongoServerError: Authentication failed.

### ISSUE THREAD

**Issue by kaykhan** [bitnami/bitnami-docker-mongodb#353]
### Name and Version

bitnami/mongodb:5

### What steps will reproduce the bug?

1. docker-compose up

**docker-compose.yml**
```
version: '2'

services:
  mongodb-primary:
    image: docker.io/bitnami/mongodb:5.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=rootpassword
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=rs0
    ports:
      - 27017:27017
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'

  mongodb-secondary:
    image: docker.io/bitnami/mongodb:5.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=localhost
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=rootpassword
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=rs0

  mongodb-arbiter:
    image: docker.io/bitnami/mongodb:5.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=localhost
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=rootpassword
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=rs0

volumes:
  mongodb_master_data:
    driver: local

networks:
  default:
    name: my_network


```

### What is the expected behavior?

expect arbiter and secondary to authenticate

### What do you see instead?

```
mongodb-arbiter_1    | MongoServerError: Authentication failed.
mongodb-secondary_1  | MongoServerError: Authentication failed.
```

### Additional information

```
mongodb-primary_1    | {"t":{"$date":"2022-07-06T10:51:38.267+00:00"},"s":"I",  "c":"ACCESS",   "id":20250,   "ctx":"conn9","msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-256","speculative":true,"principalName":"__system","authenticationDatabase":"local","remote":"127.0.0.1:57162","extraInfo":{}}}
mongodb-primary_1    | {"t":{"$date":"2022-07-06T10:51:38.267+00:00"},"s":"I",  "c":"ACCESS",   "id":20250,   "ctx":"conn7","msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-256","speculative":true,"principalName":"__system","authenticationDatabase":"local","remote":"127.0.0.1:57160","extraInfo":{}}}
mongodb-primary_1    | {"t":{"$date":"2022-07-06T10:51:38.267+00:00"},"s":"I",  "c":"ACCESS",   "id":20250,   "ctx":"conn6","msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-256","speculative":false,"principalName":"__system","authenticationDatabase":"local","remote":"127.0.0.1:57158","extraInfo":{}}}
mongodb-primary_1    | {"t":{"$date":"2022-07-06T10:51:38.267+00:00"},"s":"I",  "c":"ACCESS",   "id":20250,   "ctx":"conn5","msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-256","speculative":false,"principalName":"__system","authenticationDatabase":"local","remote":"127.0.0.1:57156","extraInfo":{}}}
mongodb-arbiter_1    | MongoNetworkError: connect ECONNREFUSED 192.168.64.3:27017
mongodb-arbiter_1    | mongodb 10:51:38.98 INFO  ==> Creating users...
mongodb-arbiter_1    | mongodb 10:51:38.98 INFO  ==> Users created
mongodb-arbiter_1    | mongodb 10:51:38.98 INFO  ==> Writing keyfile for replica set authentication...
mongodb-arbiter_1    | mongodb 10:51:38.99 INFO  ==> Configuring MongoDB replica set...
mongodb-arbiter_1    | mongodb 10:51:39.00 INFO  ==> Stopping MongoDB...
mongodb-secondary_1  | MongoNetworkError: connect ECONNREFUSED 192.168.64.4:27017
mongodb-secondary_1  | mongodb 10:51:39.04 INFO  ==> Creating users...
mongodb-secondary_1  | mongodb 10:51:39.05 INFO  ==> Users created
mongodb-secondary_1  | mongodb 10:51:39.05 INFO  ==> Writing keyfile for replica set authentication...
mongodb-secondary_1  | mongodb 10:51:39.06 INFO  ==> Configuring MongoDB replica set...
mongodb-secondary_1  | mongodb 10:51:39.06 INFO  ==> Stopping MongoDB...
mongodb-primary_1    | {"t":{"$date":"2022-07-06T10:51:39.216+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"192.168.64.1:33168","uuid":"19a99163-0858-4110-ae3f-e9f9a8315ed0","connectionId":11,"connectionCount":6}}
mongodb-primary_1    | {"t":{"$date":"2022-07-06T10:51:39.216+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn11","msg":"client metadata","attr":{"remote":"192.168.64.1:33168","client":"conn11","doc":{"driver":{"name":"mongo-java-driver|sync","version":"4.4.1-s3t"},"os":{"type":"Linux","name":"Linux","architecture":"amd64","version":"5.13.0-52-generic"},"platform":"Java/Eclipse Adoptium/17.0.2+8","application":{"name":"Studio 3T"}}}}
mongodb-primary_1    | {"t":{"$date":"2022-07-06T10:51:42.036+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"192.168.64.1:33172","uuid":"aa8ac335-a4c4-43a2-9faa-40bdb5c1d56e","connectionId":12,"connectionCount":7}}
mongodb-primary_1    | {"t":{"$date":"2022-07-06T10:51:42.036+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn12","msg":"client metadata","attr":{"remote":"192.168.64.1:33172","client":"conn12","doc":{"driver":{"name":"mongo-java-driver|sync","version":"4.4.1-s3t"},"os":{"type":"Linux","name":"Linux","architecture":"amd64","version":"5.13.0-52-generic"},"platform":"Java/Eclipse Adoptium/17.0.2+8","application":{"name":"Studio 3T"}}}}
mongodb-arbiter_1    | mongodb 10:51:42.83 INFO  ==> Trying to connect to MongoDB server localhost...
mongodb-arbiter_1    | mongodb 10:51:42.83 INFO  ==> Found MongoDB server listening at localhost:27017 !
mongodb-secondary_1  | mongodb 10:51:42.92 INFO  ==> Trying to connect to MongoDB server localhost...
mongodb-secondary_1  | mongodb 10:51:42.92 INFO  ==> Found MongoDB server listening at localhost:27017 !
mongodb-primary_1    | {"t":{"$date":"2022-07-06T10:51:43.616+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"192.168.64.1:33174","uuid":"3f9ac453-0e45-4249-97c6-787fcbe7310e","connectionId":13,"connectionCount":8}}
mongodb-primary_1    | {"t":{"$date":"2022-07-06T10:51:43.616+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"192.168.64.1:33176","uuid":"f3d2e90a-bde5-4d9e-978b-d9246fdca08b","connectionId":14,"connectionCount":9}}
mongodb-primary_1    | {"t":{"$date":"2022-07-06T10:51:43.616+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"192.168.64.1:33178","uuid":"e5640d12-f904-454b-84fa-382f84a5af0a","connectionId":15,"connectionCount":10}}
mongodb-primary_1    | {"t":{"$date":"2022-07-06T10:51:43.616+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn13","msg":"client metadata","attr":{"remote":"192.168.64.1:33174","client":"conn13","doc":{"driver":{"name":"mongo-java-driver|sync","version":"4.4.1-s3t"},"os":{"type":"Linux","name":"Linux","architecture":"amd64","version":"5.13.0-52-generic"},"platform":"Java/Eclipse Adoptium/17.0.2+8","application":{"name":"Studio 3T"}}}}
mongodb-primary_1    | {"t":{"$date":"2022-07-06T10:51:43.616+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn14","msg":"client metadata","attr":{"remote":"192.168.64.1:33176","client":"conn14","doc":{"driver":{"name":"mongo-java-driver|sync","version":"4.4.1-s3t"},"os":{"type":"Linux","name":"Linux","architecture":"amd64","version":"5.13.0-52-generic"},"platform":"Java/Eclipse Adoptium/17.0.2+8","application":{"name":"Studio 3T"}}}}
mongodb-primary_1    | {"t":{"$date":"2022-07-06T10:51:43.620+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn15","msg":"client metadata","attr":{"remote":"192.168.64.1:33178","client":"conn15","doc":{"driver":{"name":"mongo-java-driver|sync","version":"4.4.1-s3t"},"os":{"type":"Linux","name":"Linux","architecture":"amd64","version":"5.13.0-52-generic"},"platform":"Java/Eclipse Adoptium/17.0.2+8","application":{"name":"Studio 3T"}}}}
mongodb-arbiter_1    | MongoServerError: Authentication failed.
mongodb-secondary_1  | MongoServerError: Authentication failed.
mongodb-primary_1    | {"t":{"$date":"2022-07-06T10:51:44.886+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"192.168.64.1:33180","uuid":"72fbdf6b-d054-4e9e-9886-f0905cf7db61","connectionId":16,"connectionCount":11}}
mongodb-primary_1    | {"t":{"$date":"2022-07-06T10:51:44.887+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn16","msg":"client metadata","attr":{"remote":"192.168.64.1:33180","client":"conn16","doc":{"driver":{"name":"mongo-java-driver|sync","version":"4.4.1-s3t"},"os":{"type":"Linux","name":"Linux","architecture":"amd64","version":"5.13.0-52-generic"},"platform":"Java/Eclipse Adoptium/17.0.2+8","application":{"name":"Studio 3T"}}}}
mongodb-arbiter_1    | MongoServerError: Authentication failed.
mongodb-secondary_1  | MongoServerError: Authentication failed.
```
