### ISSUE TITLE
unable to restart replica set primary node after running docker-compose down

### ISSUE THREAD

**Issue by Loosetooth** [bitnami/bitnami-docker-mongodb#355]
### Name and Version

bitnami/mongodb:4.4.14

### What steps will reproduce the bug?

We start with a simple `docker-compose.yml` to start a replica set with a single primary node, and a volume to persist db data:

```yml
version: '3.9'
services:
  mongo:
    image: bitnami/mongodb:4.4.14
    container_name: mongo
    ports:
      - 27030:27017
    volumes:
      - mongodata:/bitnami/mongodb
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=ThisIsAUniqueKeyThatShouldBeChanged123

volumes:
  mongodata:
    driver: local
```

Running `docker-compose up` the first time results in the replica set correctly starting with a single primary node:
```
...
"msg":"Transition to primary complete; database writes are now permitted"
```

Now stop the containers (by pressing ctrl+c in cli or `docker-compose stop` if running in detached mode) and run `docker-compose down`

Try to restart the container:
`docker-compose up`

Results in the following output:
```
..."msg":"This node is not a member of the config"
..."msg":"Replica set state transition","attr":{"newState":"REMOVED","oldState":"STARTUP"}
```

So it looks like the node did not start back up in primary mode. Please note that when using `docker-compose stop` and then `docker-compose start` it does seem to be able to restart correctly.

### What is the expected behavior?

I should be able to restart a primary node from volume data.

### What do you see instead?

Unable to restart primary node.
