### ISSUE TITLE
Changing port leads to ECONNREFUSED

### ISSUE THREAD

**Issue by TheLegendarySpark** [bitnami/bitnami-docker-mongodb#357]
### Name and Version

bitnami/mongodb:latest

### What steps will reproduce the bug?

1. Create an env file
```
MONGO_PORT=26015 # change this port to anything except 27017
MONGO_INITDB_ROOT_PASSWORD=testing123
```
2. Construct a docker compose file
```yml
services:
  mongodb:
    # container_name: mongodb
    image: bitnami/mongodb:latest
    # restart: always
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb
      - MONGODB_ADVERTISED_PORT_NUMBER={MONGO_PORT}
      - MONGODB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_PORT_NUMBER=26015
    networks:
      - network_mongo
    volumes:
      - ./mongo/data:/bitnami

  mongodb-secondary:
    image: bitnami/mongodb:latest
    depends_on:
      - mongodb
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER={MONGO_PORT}
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: bitnami/mongodb:latest
    depends_on:
      - mongodb
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER={MONGO_PORT}
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
  
networks:
  network_mongo:
    driver: bridge
```
3. Execute this on SSH terminal
```
docker compose up --build
```
*I didn't add the `--scale` flag above as it was necessary to see all of the mongo services output at once.*

### What is the expected behavior?

MongoDB successfully establishing a connection between secondary and arbiter

### What do you see instead?

Common errors:
- `Read concern majority reads are currently not possible.` - Secondary and arbiter node wasn't recognized
- `MongoNetworkError: connect ECONNREFUSED 172.29.0.2:27017` - Attempted to connect to 27017 when the environment specified to run MongoDB replica on port 26015 (given in the example above)

### Additional information

Similar issue #355 with a different port specified
