### ISSUE TITLE
replication and arbiter containers can't authenticate to primary db

### ISSUE THREAD

**Issue by dottgonzo** [bitnami/bitnami-docker-mongodb#81]
i'm using docker on docker swarm. i've tried to run the mongodb service with replication and arbiter, as described in your docs. My docker-compose is:

```
version: '3.3'

networks:
  mongodb:
    external: true


services:
  mongoprimary:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ROOT_PASSWORD: XXXXXXXX
      MONGODB_REPLICA_SET_KEY: replicasetkey123

    volumes:
      - /cloud/volumes/services/mongodb/dbdata:/bitnami
    networks:
      - mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s


  mongosecondary:
    image: bitnami/mongodb:latest
    depends_on:
      - mongoprimary
    environment:
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_PRIMARY_HOST: mongodb_mongoprimary
      MONGODB_PRIMARY_ROOT_PASSWORD: XXXXXXXX
      MONGODB_REPLICA_SET_KEY: replicasetkey123
    networks:
      - mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s

  mongoarbiter:
    image: bitnami/mongodb:latest
    depends_on:
      - mongoprimary
    environment:
      MONGODB_REPLICA_SET_MODE: arbiter
      MONGODB_PRIMARY_HOST: mongodb_mongoprimary
      MONGODB_PRIMARY_ROOT_PASSWORD: XXXXXXXX
      MONGODB_REPLICA_SET_KEY: replicasetkey123
    networks:
      - mongodb
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s
```

but i see always this error loop

```
mongodb_mongoprimary.1.dcgg1dxopes2@manager1    | 2017-08-28T14:02:08.263+0000 I NETWORK  [thread1] connection accepted from 10.0.12.3:46888 #1 (1 connection now open)
mongodb_mongoprimary.1.dcgg1dxopes2@manager1    | 2017-08-28T14:02:08.284+0000 I -        [conn1] end connection 10.0.12.3:46888 (1 connection now open)
mongodb_mongoprimary.1.dcgg1dxopes2@manager1    | 2017-08-28T14:02:08.335+0000 I NETWORK  [thread1] connection accepted from 10.0.12.3:46890 #2 (1 connection now open)
mongodb_mongoprimary.1.dcgg1dxopes2@manager1    | 2017-08-28T14:02:08.338+0000 I NETWORK  [conn2] received client metadata from 10.0.12.3:46890 conn2: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.7" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 8 (jessie)"", architecture: "x86_64", version: "Kernel 4.10.0-32-generic" } }
mongodb_mongoprimary.1.dcgg1dxopes2@manager1    | 2017-08-28T14:02:08.346+0000 I ACCESS   [conn2] SCRAM-SHA-1 authentication failed for root on admin from client 10.0.12.3:46890 ; UserNotFound: Could not find user root@admin
mongodb_mongoprimary.1.dcgg1dxopes2@manager1    | 2017-08-28T14:02:08.349+0000 I -        [conn2] end connection 10.0.12.3:46890 (1 connection now open)
```

"Could not find user root@admin" ???

i can't understand why, maybe i've to create some sort of database before run the cluster??

**Comment by jotadrilo** [comment]
Hi @dottgonzo,

It seems the mongodb data is not properly set, so the default admin user `root@admin` does not exist.

Could you paste the logs you are getting at container startup? They would be useful to understand the way of the containers are being initialized.

Also, could you list the content of the mounted folder `/cloud/volumes/services/mongodb/dbdata`? If it is pre-populated data that you can run with mongodb it should fit some conditions so the container recognizes it as proper data.

The logs will help to understand this issue.

**Comment by Zsomx** [comment]
Any news?

**Comment by jotadrilo** [comment]
Hi @Zsomx!

As we requested in the past, would you mind pasting the logs that you are getting at container startup (in both first time and recreation) and listing the content of the `/bitnami/mongodb` folder inside the container (and the folder linked to `/bitnami` in the host).

It sounds like data volume is not properly set and MongoDB fails to load previous data.

**Comment by Zsomx** [comment]
Hi @jotadrilo !

Compose file:

version: '3'
services:
  mongodb-primary:
    image: 'bitnami/mongodb:3.6.0-r1'
    networks:
      - parse_network
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=tralala
      - MONGODB_ROOT_PASSWORD=123456789
  mongodb-secondary:
    image: 'bitnami/mongodb:3.6.0-r1'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_ROOT_PASSWORD=tralala
      - MONGODB_REPLICA_SET_KEY=123456789
      - MONGODB_PRIMARY_ROOT_USER=root
    networks:
      - parse_network
networks:
    parse_network:
        driver: bridge
        ipam:
          driver: default

_(No volume attached.)_ 

First time it works well, but after the docker-compose down & docker-compose up commands, the log shows some kind of authentication error:
`mongodb-primary_1    | Welcome to the Bitnami mongodb container
mongodb-primary_1    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb-primary_1    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb-primary_1    | Send us your feedback at containers@bitnami.com
mongodb-primary_1    |
mongodb-primary_1    | nami    INFO  Initializing mongodb
mongodb-secondary_1  |
mongodb-secondary_1  | Welcome to the Bitnami mongodb container
mongodb-secondary_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb-secondary_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb-secondary_1  | Send us your feedback at containers@bitnami.com
mongodb-secondary_1  |
mongodb-secondary_1  | nami    INFO  Initializing mongodb
mongodb-primary_1    | mongodb INFO  ==> Creating root user...
mongodb-primary_1    | mongodb INFO  ==> Enabling authentication...
mongodb-primary_1    | mongodb INFO  ==> Writing keyfile for replica set authentication
mongodb-primary_1    | mongodb INFO  ==> Configuring MongoDB replica set
mongodb-secondary_1  | mongodb INFO  ==> Writing keyfile for replica set authentication
mongodb-secondary_1  | mongodb INFO  ==> Configuring MongoDB replica set
mongodb-primary_1    | mongodb INFO  ==> Configuring MongoDB primary node
mongodb-secondary_1  | mongodb INFO  ==> Configuring MongoDB secondary node
mongodb-secondary_1  | INFO  Trying to connect to MongoDB server
mongodb-secondary_1  | INFO  Found MongoDB server listening at mongodb-primary:27017
mongodb-secondary_1  | INFO  Cannot connect to MongoDB server. Retrying in 5 seconds...:
mongodb-secondary_1  | 2018-01-22T11:01:17.106+0000 I NETWORK  [thread1] Socket recv() Connection reset by peer 172.18.0.2:27017
mongodb-secondary_1  | 2018-01-22T11:01:17.106+0000 I NETWORK  [thread1] SocketException: remote: (NONE):0 error: SocketException socket exception [RECV_ERROR] server [172.18.0.2:27017]
mongodb-secondary_1  | 2018-01-22T11:01:17.107+0000 E QUERY    [thread1] Error: network error while attempting to run command 'isMaster' on host 'mongodb-primary:27017'  :
mongodb-secondary_1  | connect@src/mongo/shell/mongo.js:251:13
mongodb-secondary_1  | @(connect):1:21
mongodb-secondary_1  |
mongodb-secondary_1  |
mongodb-secondary_1  | exception: connect failed
mongodb-secondary_1  |
mongodb-primary_1    | mongodb INFO
mongodb-primary_1    | mongodb INFO  ########################################################################
mongodb-primary_1    | mongodb INFO   Installation parameters for mongodb:
mongodb-primary_1    | mongodb INFO     Root Password: **********
mongodb-primary_1    | mongodb INFO     Replication Mode: primary
mongodb-primary_1    | mongodb INFO   (Passwords are not shown for security reasons)
mongodb-primary_1    | mongodb INFO  ########################################################################
mongodb-primary_1    | mongodb INFO
mongodb-primary_1    | nami    INFO  mongodb successfully initialized
mongodb-primary_1    | INFO  ==> Starting mongodb...
mongodb-primary_1    | INFO  ==> Starting mongod...
mongodb-primary_1    | 2018-01-22T11:01:18.465+0000 I CONTROL  [initandlisten] MongoDB starting : pid=114 port=27017 dbpath=/opt/bitnami/mongodb/data/db 64-bit host=05cb79703b3d
mongodb-primary_1    | 2018-01-22T11:01:18.465+0000 I CONTROL  [initandlisten] db version v3.6.0
mongodb-primary_1    | 2018-01-22T11:01:18.465+0000 I CONTROL  [initandlisten] git version: a57d8e71e6998a2d0afde7edc11bd23e5661c915
mongodb-primary_1    | 2018-01-22T11:01:18.465+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
mongodb-primary_1    | 2018-01-22T11:01:18.465+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongodb-primary_1    | 2018-01-22T11:01:18.465+0000 I CONTROL  [initandlisten] modules: none
mongodb-primary_1    | 2018-01-22T11:01:18.465+0000 I CONTROL  [initandlisten] build environment:
mongodb-primary_1    | 2018-01-22T11:01:18.465+0000 I CONTROL  [initandlisten]     distmod: debian81
mongodb-primary_1    | 2018-01-22T11:01:18.465+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongodb-primary_1    | 2018-01-22T11:01:18.465+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mongodb-primary_1    | 2018-01-22T11:01:18.465+0000 I CONTROL  [initandlisten] options: { config: "/opt/bitnami/mongodb/conf/mongodb.conf", net: { bindIp: "0.0.0.0", port: 27017, unixDomainSocket: { enabled: true, pathPrefix: "/opt/bitnami/mongodb/tmp" } }, processManagement: { fork: false, pidFilePath: "/opt/bitnami/mongodb/tmp/mongodb.pid" }, replication: { replSetName: "replicaset" }, security: { authorization: "enabled", keyFile: "/opt/bitnami/mongodb/conf/keyfile" }, setParameter: { enableLocalhostAuthBypass: "false" }, storage: { dbPath: "/opt/bitnami/mongodb/data/db", journal: { enabled: true } }, systemLog: { destination: "file", logAppend: true, path: true } }
mongodb-primary_1    | 2018-01-22T11:01:18.466+0000 I -        [initandlisten] Detected data files in /opt/bitnami/mongodb/data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
mongodb-primary_1    | 2018-01-22T11:01:18.466+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=487M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
mongodb-primary_1    | 2018-01-22T11:01:18.943+0000 I STORAGE  [initandlisten] WiredTiger message [1516618878:943358][114:0x7f1cc6ffca00], txn-recover: Main recovery loop: starting at 2/15872
mongodb-primary_1    | 2018-01-22T11:01:19.029+0000 I STORAGE  [initandlisten] WiredTiger message [1516618879:29060][114:0x7f1cc6ffca00], txn-recover: Recovering log 2 through 3
mongodb-primary_1    | 2018-01-22T11:01:19.239+0000 I STORAGE  [initandlisten] WiredTiger message [1516618879:239586][114:0x7f1cc6ffca00], txn-recover: Recovering log 3 through 3
mongodb-primary_1    | 2018-01-22T11:01:20.845+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/opt/bitnami/mongodb/data/db/diagnostic.data'
mongodb-primary_1    | 2018-01-22T11:01:20.845+0000 I REPL     [initandlisten] Did not find local voted for document at startup.
mongodb-primary_1    | 2018-01-22T11:01:20.846+0000 I REPL     [initandlisten] Did not find local replica set configuration document at startup;  NoMatchingDocument: Did not find replica set configuration document in local.system.replset
mongodb-primary_1    | 2018-01-22T11:01:20.847+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
mongodb-primary_1    | 2018-01-22T11:01:22.162+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:47890 #1 (1 connection now open)
mongodb-primary_1    | 2018-01-22T11:01:22.163+0000 I NETWORK  [conn1] received client metadata from 172.18.0.3:47890 conn: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version:"3.6.0" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 8 (jessie)"", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
mongodb-primary_1    | 2018-01-22T11:01:22.164+0000 I ACCESS   [conn1] SCRAM-SHA-1 authentication failed for root on admin from client 172.18.0.3:47890 ; UserNotFound: Could not find user root@admin
mongodb-primary_1    | 2018-01-22T11:01:22.166+0000 I NETWORK  [conn1] end connection 172.18.0.3:47890 (0 connections now open)
mongodb-secondary_1  | INFO  Cannot connect to MongoDB server. Retrying in 5 seconds...:
mongodb-secondary_1  | 2018-01-22T11:01:22.165+0000 E QUERY    [thread1] Error: Authentication failed. :
mongodb-secondary_1  | DB.prototype._authOrThrow@src/mongo/shell/db.js:1608:20
mongodb-secondary_1  | @(auth):6:1
mongodb-secondary_1  | @(auth):1:2
mongodb-secondary_1  |
mongodb-secondary_1  |
mongodb-secondary_1  | exception: login failed
mongodb-secondary_1  |
mongodb-primary_1    | 2018-01-22T11:01:27.218+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:47892 #2 (1 connection now open)
mongodb-primary_1    | 2018-01-22T11:01:27.218+0000 I NETWORK  [conn2] received client metadata from 172.18.0.3:47892 conn: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version:"3.6.0" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 8 (jessie)"", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
mongodb-primary_1    | 2018-01-22T11:01:27.220+0000 I ACCESS   [conn2] SCRAM-SHA-1 authentication failed for root on admin from client 172.18.0.3:47892 ; UserNotFound: Could not find user root@admin
mongodb-primary_1    | 2018-01-22T11:01:27.222+0000 I NETWORK  [conn2] end connection 172.18.0.3:47892 (0 connections now open)
mongodb-secondary_1  | INFO  Cannot connect to MongoDB server. Retrying in 5 seconds...:
mongodb-secondary_1  | 2018-01-22T11:01:27.221+0000 E QUERY    [thread1] Error: Authentication failed. :
mongodb-secondary_1  | DB.prototype._authOrThrow@src/mongo/shell/db.js:1608:20
mongodb-secondary_1  | @(auth):6:1
mongodb-secondary_1  | @(auth):1:2
mongodb-secondary_1  |
mongodb-secondary_1  |
mongodb-secondary_1  | exception: login failed
mongodb-secondary_1  |
mongodb-primary_1    | 2018-01-22T11:01:32.274+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:47894 #3 (1 connection now open)
mongodb-primary_1    | 2018-01-22T11:01:32.274+0000 I NETWORK  [conn3] received client metadata from 172.18.0.3:47894 conn: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version:"3.6.0" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 8 (jessie)"", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
mongodb-primary_1    | 2018-01-22T11:01:32.276+0000 I ACCESS   [conn3] SCRAM-SHA-1 authentication failed for root on admin from client 172.18.0.3:47894 ; UserNotFound: Could not find user root@admin
mongodb-primary_1    | 2018-01-22T11:01:32.278+0000 I NETWORK  [conn3] end connection 172.18.0.3:47894 (0 connections now open)
mongodb-secondary_1  | INFO  Cannot connect to MongoDB server. Retrying in 5 seconds...:
mongodb-secondary_1  | 2018-01-22T11:01:32.277+0000 E QUERY    [thread1] Error: Authentication failed. :
mongodb-secondary_1  | DB.prototype._authOrThrow@src/mongo/shell/db.js:1608:20
mongodb-secondary_1  | @(auth):6:1
mongodb-secondary_1  | @(auth):1:2
mongodb-secondary_1  |
mongodb-secondary_1  |
mongodb-secondary_1  | exception: login failed
mongodb-secondary_1  |
mongodb-primary_1    | 2018-01-22T11:01:37.334+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:47896 #4 (1 connection now open)
mongodb-primary_1    | 2018-01-22T11:01:37.335+0000 I NETWORK  [conn4] received client metadata from 172.18.0.3:47896 conn: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version:"3.6.0" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 8 (jessie)"", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
mongodb-primary_1    | 2018-01-22T11:01:37.337+0000 I ACCESS   [conn4] SCRAM-SHA-1 authentication failed for root on admin from client 172.18.0.3:47896 ; UserNotFound: Could not find user root@admin
mongodb-primary_1    | 2018-01-22T11:01:37.338+0000 I NETWORK  [conn4] end connection 172.18.0.3:47896 (0 connections now open)
mongodb-secondary_1  | INFO  Cannot connect to MongoDB server. Retrying in 5 seconds...:
mongodb-secondary_1  | 2018-01-22T11:01:37.338+0000 E QUERY    [thread1] Error: Authentication failed. :
mongodb-secondary_1  | DB.prototype._authOrThrow@src/mongo/shell/db.js:1608:20
mongodb-secondary_1  | @(auth):6:1
mongodb-secondary_1  | @(auth):1:2
mongodb-secondary_1  |
mongodb-secondary_1  |
mongodb-secondary_1  | exception: login failed
mongodb-secondary_1  |
mongodb-primary_1    | 2018-01-22T11:01:42.395+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:47898 #5 (1 connection now open)
mongodb-primary_1    | 2018-01-22T11:01:42.396+0000 I NETWORK  [conn5] received client metadata from 172.18.0.3:47898 conn: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version:"3.6.0" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 8 (jessie)"", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
mongodb-primary_1    | 2018-01-22T11:01:42.398+0000 I ACCESS   [conn5] SCRAM-SHA-1 authentication failed for root on admin from client 172.18.0.3:47898 ; UserNotFound: Could not find user root@admin
mongodb-primary_1    | 2018-01-22T11:01:42.399+0000 I NETWORK  [conn5] end connection 172.18.0.3:47898 (0 connections now open)
mongodb-secondary_1  | INFO  Cannot connect to MongoDB server. Retrying in 5 seconds...:
mongodb-secondary_1  | 2018-01-22T11:01:42.398+0000 E QUERY    [thread1] Error: Authentication failed. :
mongodb-secondary_1  | DB.prototype._authOrThrow@src/mongo/shell/db.js:1608:20
mongodb-secondary_1  | @(auth):6:1
mongodb-secondary_1  | @(auth):1:2
mongodb-secondary_1  |
mongodb-secondary_1  |
mongodb-secondary_1  | exception: login failed
mongodb-secondary_1  |
mongodb-primary_1    | 2018-01-22T11:01:47.451+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:47900 #6 (1 connection now open)
mongodb-primary_1    | 2018-01-22T11:01:47.452+0000 I NETWORK  [conn6] received client metadata from 172.18.0.3:47900 conn: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version:"3.6.0" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 8 (jessie)"", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
mongodb-primary_1    | 2018-01-22T11:01:47.454+0000 I ACCESS   [conn6] SCRAM-SHA-1 authentication failed for root on admin from client 172.18.0.3:47900 ; UserNotFound: Could not find user root@admin
mongodb-primary_1    | 2018-01-22T11:01:47.455+0000 I NETWORK  [conn6] end connection 172.18.0.3:47900 (0 connections now open)
mongodb-secondary_1  | INFO  Cannot connect to MongoDB server. Retrying in 5 seconds...:
mongodb-secondary_1  | 2018-01-22T11:01:47.454+0000 E QUERY    [thread1] Error: Authentication failed. :
mongodb-secondary_1  | DB.prototype._authOrThrow@src/mongo/shell/db.js:1608:20
mongodb-secondary_1  | @(auth):6:1
mongodb-secondary_1  | @(auth):1:2
mongodb-secondary_1  |
mongodb-secondary_1  |
mongodb-secondary_1  | exception: login failed
mongodb-secondary_1  |
mongodb-primary_1    | 2018-01-22T11:01:52.511+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:47902 #7 (1 connection now open)
mongodb-primary_1    | 2018-01-22T11:01:52.512+0000 I NETWORK  [conn7] received client metadata from 172.18.0.3:47902 conn: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version:"3.6.0" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 8 (jessie)"", architecture: "x86_64", version: "Kernel 4.9.49-moby" } }
mongodb-primary_1    | 2018-01-22T11:01:52.514+0000 I ACCESS   [conn7] SCRAM-SHA-1 authentication failed for root on admin from client 172.18.0.3:47902 ; UserNotFound: Could not find user root@admin
mongodb-primary_1    | 2018-01-22T11:01:52.516+0000 I NETWORK  [conn7] end connection 172.18.0.3:47902 (0 connections now open)
mongodb-secondary_1  | INFO  Cannot connect to MongoDB server. Retrying in 5 seconds...:
mongodb-secondary_1  | 2018-01-22T11:01:52.515+0000 E QUERY    [thread1] Error: Authentication failed. :
mongodb-secondary_1  | DB.prototype._authOrThrow@src/mongo/shell/db.js:1608:20
mongodb-secondary_1  | @(auth):6:1
mongodb-secondary_1  | @(auth):1:2
mongodb-secondary_1  |
mongodb-secondary_1  |
mongodb-secondary_1  | exception: login failed
mongodb-secondary_1  |`

**Comment by jotadrilo** [comment]
Hello @Zsomx,

It seems you mistyped some environment variables in your Compose configuration. You can apply this diff to fix them:

```
diff --git a/docker-compose.yml b/docker-compose.yml
index 3140323..96aed63 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -14,11 +14,9 @@ services:
       - mongodb-primary
     environment:
       - MONGODB_REPLICA_SET_MODE=secondary
+      - MONGODB_REPLICA_SET_KEY=tralala
       - MONGODB_PRIMARY_HOST=mongodb-primary
-      - MONGODB_PRIMARY_PORT_NUMBER=27017
-      - MONGODB_PRIMARY_ROOT_PASSWORD=tralala
-      - MONGODB_REPLICA_SET_KEY=123456789
-      - MONGODB_PRIMARY_ROOT_USER=root
+      - MONGODB_PRIMARY_ROOT_PASSWORD=123456789
     networks:
       - parse_network
 networks:
```

Basically, the `MONGODB_REPLICA_SET_KEY` env var must be the same in all the nodes and the `MONGODB_PRIMARY_ROOT_PASSWORD` env var (secondary) must match the `MONGODB_ROOT_PASSWORD` env var (primary). The `docker-compose.yml` file should look like the one below:

```
version: '3'
services:
  mongodb-primary:
    image: 'bitnami/mongodb:3.6.0-r1'
    networks:
      - parse_network
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=tralala
      - MONGODB_ROOT_PASSWORD=123456789
  mongodb-secondary:
    image: 'bitnami/mongodb:3.6.0-r1'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_REPLICA_SET_KEY=tralala
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=123456789
    networks:
      - parse_network
networks:
    parse_network:
        driver: bridge
        ipam:
          driver: default
```

Additionally, Note that your Compose configuration will prevent data from being persisted. (You may want this to happen, though). Example:

1. Create a collection

```
$ docker-compose exec mongodb-primary mongo admin -u root -p 123456789 --eval 'db.createCollection("gh-issues-81");'
MongoDB shell version v3.6.0
connecting to: mongodb://127.0.0.1:27017/admin
MongoDB server version: 3.6.0
{
	"ok" : 1,
	"operationTime" : Timestamp(1516705396, 1),
	"$clusterTime" : {
		"clusterTime" : Timestamp(1516705396, 1),
		"signature" : {
			"hash" : BinData(0,"xuCE6BVyGd1CWeuoiVrmr81VyLI="),
			"keyId" : NumberLong("6514199021219741697")
		}
	}
}
```

2. Get all collections

```
$ docker-compose exec mongodb-primary mongo admin -u root -p 123456789 --eval 'db.getCollectionNames();'
MongoDB shell version v3.6.0
connecting to: mongodb://127.0.0.1:27017/admin
MongoDB server version: 3.6.0
[ "gh-issues-81", "system.keys", "system.users", "system.version" ]
```

3. Re-create containers and get collections

```
$ docker-compose down
$ docker-compose up
$ docker-compose exec mongodb-primary mongo admin -u root -p 123456789 --eval 'db.getCollectionNames();'
MongoDB shell version v3.6.0
connecting to: mongodb://127.0.0.1:27017/admin
MongoDB server version: 3.6.0
[ "system.keys", "system.users", "system.version" ]
```

As you can notice, the collection we created no longer exists.

I hope this helped to solve your issue!

**Comment by Zsomx** [comment]
Hi @jotadrilo !

Thanks for your response.

I corrected my mistypes but I get the same error again.
Compose: 

```
version: '3'
services:
  mongodb-primary:
    image: 'bitnami/mongodb:3.6.0-r1'
    networks:
      - parse_network
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=12345
      - MONGODB_ROOT_PASSWORD=6789
  mongodb-secondary:
    image: 'bitnami/mongodb:3.6.0-r1'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_PRIMARY_ROOT_PASSWORD=6789
      - MONGODB_REPLICA_SET_KEY=12345
    networks:
      - parse_network
networks:
    parse_network:
        driver: bridge
        ipam:
          driver: default
```

Any idea?
