### ISSUE TITLE
Not able to connect to the replica set from another mongo client or cli

### ISSUE THREAD

**Issue by prem911** [bitnami/bitnami-docker-mongodb#84]
**Description**

Not able to connect to the replica set from another mongo client or cli

**Steps to reproduce the issue:**

1. Use the docker compose steps for starting the replica set with all default values
2. The primary node has additional change of ports - 27017:27017
3. Once the nodes are up, from the mongo shell try the following
```
mongo "mongodb://public-ip:27017/admin?replicaSet=replicaset"
```

**Describe the results you received:**

MongoDB shell version v3.4.10
connecting to: mongodb://public-ip:27017/admin?replicaSet=replicaset
2017-12-02T00:49:24.621+0530 I NETWORK  [thread1] Starting new replica set monitor for replicaset/public-ip:27017
2017-12-02T00:49:26.610+0530 I NETWORK  [thread1] Successfully connected to public-ip:27017 (1 connections now open to public-ip:27017 with a 5 second timeout)
2017-12-02T00:49:26.904+0530 I NETWORK  [thread1] changing hosts to replicaset/172.18.0.2:27017,172.18.0.3:27017 from replicaset/public-ip:27017
2017-12-02T00:49:27.197+0530 W NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Failed to connect to 172.18.0.2:27017, in(checking socket for error after poll), reason: Connection refused
2017-12-02T00:49:31.908+0530 W NETWORK  [thread1] Failed to connect to 172.18.0.3:27017 after 5000ms milliseconds, giving up.
2017-12-02T00:49:32.415+0530 W NETWORK  [thread1] Failed to connect to 172.18.0.3:27017, in(checking socket for error after poll), reason: Connection refused
2017-12-02T00:49:37.420+0530 W NETWORK  [thread1] Failed to connect to 172.18.0.2:27017 after 5000ms milliseconds, giving up.
2017-12-02T00:49:37.420+0530 W NETWORK  [thread1] No primary detected for set replicaset
2017-12-02T00:49:37.420+0530 I NETWORK  [thread1] All nodes for set replicaset are down. This has happened for 1 checks in a row.
2017-12-02T00:49:37.924+0530 W NETWORK  [thread1] Failed to connect to 172.18.0.3:27017, in(checking socket for error after poll), reason: Connection refused
2017-12-02T00:49:42.929+0530 W NETWORK  [thread1] Failed to connect to 172.18.0.2:27017 after 5000ms milliseconds, giving up.
2017-12-02T00:49:42.929+0530 W NETWORK  [thread1] No primary detected for set replicaset
2017-12-02T00:49:42.929+0530 I NETWORK  [thread1] All nodes for set replicaset are down. This has happened for 2 checks in a row.
2017-12-02T00:49:42.936+0530 E QUERY    [thread1] Error: connect failed to replica set replicaset/public-ip:27017 :
connect@src/mongo/shell/mongo.js:237:13
@(connect):1:6
exception: connect failed

**Describe the results you expected:**

Excepted the mongo shell to work as usual. If we execute 
```
mongo "mongodb://public-ip:27017/admin"
```
then it works and gives us the shell access.

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-92-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.303GiB
Name: devmongo
ID: I547:PWY4:M2S7:SCX2:BV4Z:YPE2:TKZO:G35R:MA27:YCWE:3ZUT:EM4I
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.15.0, build e12f3b9
docker-py version: 2.4.2
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by tompizmor** [comment]
Hello @prem911,

Could you please share the docker-compose file that you are using?

I was able to connect to the replica set using a different mongo-cli with this configuration:

```
version: '2'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
    volumes:
      - 'mongodb_master_data:/bitnami'

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary

  mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary

  mongo-cli:
    image: 'bitnami/mongodb:latest'
volumes:
  mongodb_master_data:
    driver: local
```

Then exec into the mongo-cli container and connect to the replica set:

```
$ docker-compose exec mongo-cli bash
$ mongo "mongodb://mongodb-primary:27017/admin?replicaSet=replicaset"
```

**Comment by prem911** [comment]
If you have primary, secondary and mongo-cli in the same host, the mongodb can be connected. Works for me too.

I m struggling to connect to the replicaset from a different host.
e.g., mongo replica docker is running in one AWS EC2 instance with ip 100.200.100.100
Neither my applications nor my mongo client ( Robo 3T or mongo studio ) is able to connect using the replica set settings.
Am I missing something silly here?

**Comment by martin-voigt** [comment]
Unfortunately, we face the same issue. After a first successful access over the external IP and port, it then reuses the internal IP and port.

`
...
connecting to: mongodb://EXT_IP:27018/admin?replicaSet=replicaset
2018-01-08T13:55:23.199+0100 I NETWORK  [thread1] Starting new replica set monitor for replicaset/136.243.47.194:27018
2018-01-08T13:55:23.199+0100 I NETWORK  [ReplicaSetMonitorWatcher] starting
2018-01-08T13:55:23.200+0100 I NETWORK  [thread1] Successfully connected to EXT_IP:27018 (1 connections now open to EXT_IP:27018 with a 5 second timeout)
2018-01-08T13:55:28.201+0100 W NETWORK  [thread1] Failed to connect to 172.31.0.4:27017 after 5000ms milliseconds, giving up.
2018-01-08T13:55:33.202+0100 W NETWORK  [thread1] Failed to connect to 172.31.0.2:27017 after 5000ms milliseconds, giving up.
2018-01-08T13:55:33.202+0100 W NETWORK  [thread1] No primary detected for set replicaset
...
`
In that way, the replicatset functionality is no usable.

**Comment by tompizmor** [comment]
Hi @prem911, @martin-voigt 

I could reproduce the issue now. The problem is that the members of the replicaset are configured with the internal ip of the machine and mongo is trying to connect using that ip. 
You can check the ips of each node by logging into the primary host and executing the following command:

```
replicaset:PRIMARY> rs.conf().members
[
	{
		"_id" : 0,
		"host" : "172.18.0.2:27017",
		"arbiterOnly" : false,
		"buildIndexes" : true,
		"hidden" : false,
		"priority" : 5,
		"tags" : {

		},
		"slaveDelay" : NumberLong(0),
		"votes" : 1
	},
	{
		"_id" : 1,
		"host" : "172.18.0.3:27017",
		"arbiterOnly" : true,
		"buildIndexes" : true,
		"hidden" : false,
		"priority" : 0,
		"tags" : {

		},
		"slaveDelay" : NumberLong(0),
		"votes" : 1
	},
	{
		"_id" : 2,
		"host" : "172.18.0.4:27017",
		"arbiterOnly" : false,
		"buildIndexes" : true,
		"hidden" : false,
		"priority" : 1,
		"tags" : {

		},
		"slaveDelay" : NumberLong(0),
		"votes" : 1
	}
]
```

Your application should have connectivity to these ips in order to the replicaset to work.

**Comment by Gp2mv3** [comment]
I had the exact same issue and found the MONGODB_ADVERTISED_HOSTNAME env variable (in the doc of this repo).
Using it solves the issue. Here is my secondary service:
```
  mongodb-secondary:
    image: 'bitnami/mongodb:${MONGO_VERSION:-3.2}'
    depends_on:
      - mongodb-primary
    deploy:
      replicas: 3
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_REPLICA_SET_NAME=${REPLICASET_NAME:-rs}
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
```
