### ISSUE TITLE
Unable to login to mongodb

### ISSUE THREAD

**Issue by nathanaherne** [bitnami/bitnami-docker-mongodb#91]
I am using Docker Compose 3 to setup the mongodb container.

I am setting the values:

```
    environment:
      MONGODB_ROOT_PASSWORD: password

      MONGODB_USERNAME: testing
      MONGODB_DATABASE: testing
      MONGODB_PASSWORD: password
```

I have tried to login to mongodb from within the container to check if things are working with the following command `mongo -u 'root' -p 'password' --authenticationDatabase admin`

I have tried a number of other strings to see if I was missing something but I am unable to connect to mongo. I am obviously missing something, could someone please point out what it is?
